rr-debugger/rr

CMakeLists.txt
src/kernel_supplement.h
src/record_syscall.cc
src/syscalls.py
src/test/getrandom.c
src/test/rrutil.h

Resolves #1379.
Pretty straightforward so I'm going to directly merge this.  It's so much more pleasant to add support for new syscalls now! :)

Add support for the getrandom syscall.

---

src/fast_forward.cc

Nothing interesting here, will just merge

Attempt to fix warning from older gcc.

---

src/test/rrutil.h

Resolves #1442.  Should fix the travis-ci build.

Ensure that the seccomp test builds on older systems

---

src/PerfCounters.cc

Added support for Intel Core i7-5820K, FC-LGA4, Haswell-E, 2011-3

Added support for Core i7 variant

---

src/GdbServer.cc
src/test/when.py

Similar to the `when` command which displays the current event number,
the `when-ticks` command displays the current ticks count.

Add a `when-ticks` command

---

src/GdbConnection.cc
src/GdbConnection.h
src/GdbServer.cc
src/GdbServer.h
src/ReplayCommand.cc

@huonw, can you verify that this actually works with rust-gdb?

add a -d option to replay for specifying a custom debugger

---

src/PerfCounters.cc

Resolves #1607 
Seems to work fine on my Skylake machine. All tests pass on my machine.

Add Intel Skylake support

---

src/RecordSession.cc

Some filesystem weirdness makes the cp call fail under Docker (it can't access /proc/pid/fd/3), and this works.
Example of it failing (after creating pulse.conf):
```
$ docker run -t -i --rm -v /build:/build --cap-add SYS_PTRACE --security-opt apparmor:unconfined ubuntu:14.04 
root@7d43bcf99b81:/# /build/rr/obj/bin/rr ls
rr: Warning: Your CPU frequency governor is 'ondemand'.  rr strongly
recommends that you use the 'performance' governor.  Not using the
'performance' governor can cause rr to be at least 2x slower
on laptops.
On Fedora-based systems, you can enable the 'performance' governor
by running the following commands:
$ sudo dnf install kernel-tools
$ sudo cpupower frequency-set -g performance
rr: Saving the execution of `ls' to trace directory `/root/.local/share/rr/ls-0'.
bin …
```

Change create_pulseaudio_config to copy pulse.conf using read/write instead of executing `cp`.

---

README.md
src/test/thread_exit_signal.run
src/test/unshare.c
src/test/util.sh

Let me know if you'd prefer separate pull requests.

A few small changes

---

src/AutoRemoteSyscalls.cc
src/RecordSession.cc
src/RecordTask.cc
src/Registers.cc
src/Registers.h
src/ReplayCommand.cc
src/ReplaySession.cc
src/Scheduler.cc
src/Session.cc
src/Task.cc
src/Task.h
src/ftrace.cc
src/kernel_abi.cc
src/kernel_abi.h
src/kernel_metadata.cc
src/kernel_supplement.h
src/record_signal.cc
src/record_syscall.cc

Don't include as many system headers in rr's headers

---

src/test/ptrace.c

Sorry, this took a bit longer, I wanted to make sure I fully understood what was happening.
See the essay in ptrace.c as to what the problem was (I can put this in the commit message
if you prefer, but I wanted to make sure people in the future would find it - which isn't always easy with commits if the go through reformats etc.). This is a regression from f3b7fb7fdb3c56b7317e38a91088ebc32fc2795f (cc @khuey) since before
the tracee did not execute any signal handlers.

Fix intermittent ptrace test failure

---

CMakeLists.txt
src/RecordTask.cc
src/Task.cc
src/test/bad_ip.c
src/test/ptrace_remote_unmap.c
src/test/sigprocmask_exec.c
src/test/sigrt.c

Various small issues. See individual commit messages for details.

Fix a number of issues seen on Ubuntu 16.10

---

src/ReplaySession.cc

Increase SKID_SIZE to 100

---

src/replay_syscall.cc

Such as the dynamic linker, which can be run as an executable in order to test
changes to the dynamic linker itself. If a dynamic linker is present, that's
where the ip will be right after the execve, so in order to find the main
executable, we simply have to find a file that does have an executable
segment, but of which no segment contains the ip. If there is only one file
with executable segments, the file is likely statically linked (it is probably
theoretically possible for an executable to be its own dynamic linker, thus
putting two copies of the same file in memory, but even that should work,
since the only use of finding the main executable is for GDB and naming
the rr threads).
Fixes #1880

Allow replay of executables that end in `.so`

---

CMakeLists.txt
src/RecordSession.cc
src/Task.cc
src/Task.h
src/kernel_supplement.h
src/preload/preload.c
src/preload/preload_interface.h
src/record_signal.cc
src/record_syscall.cc
src/replay_syscall.cc
src/test/ptrace_change_patched_syscall.c
src/test/ptrace_singlestep.c
src/test/ptrace_traceme.c

Mostly as discussed on IRC. See individual commit messages for details.

Misc improvements to ptrace emulations

---

CMakeLists.txt
src/RecordTask.cc
src/RecordTask.h
src/Registers.h
src/Task.cc
src/Task.h
src/kernel_supplement.h
src/record_syscall.cc
src/replay_syscall.cc
src/syscalls.py
src/test/kill_ptracee.c
src/test/ptrace.c
src/test/ptrace_tls.c

As usual, see commit messages for details. Also, don't worry, @rocallahan, I'm almost through my backlog of local changes (3-4 commits left), so the PR storm will be over soon.

ptrace emulation improvements, round 2

---

src/PerfCounters.cc

Add support for Kabylake micro-architecture

---

CMakeLists.txt
src/kernel_supplement.h
src/record_syscall.cc
src/syscalls.py
src/test/keyctl.c
src/test/nsutils.h
src/test/pivot_root.c
src/test/prctl_caps.c
src/test/privileged_net_ioctl.c

All of these system calls are pretty boring from our perspective, so the bulk of this is tests.

More syscall coverage improvements

---

CMakeLists.txt
src/RecordTask.cc
src/Registers.h
src/ReplayTask.cc
src/Task.cc
src/Task.h
src/record_syscall.cc
src/test/mount_ns_exec.c
src/test/personality.c
src/test/self_shebang.c

See the second commit for details. The first commit is unrelated. I just had it lying around.

Don't fail if the tracee is in a different mount ns 

---

src/util.cc

In ea04c71b4283f18bf20a5d20e22b70882d155e15, I added a test to checksum_sanity
to handle the case where there was a mapping entirely beyond the end of it's
underlying file. If during replay, this mapping is crated using trace data,
the replayer will automatically create a SIGBUS region and that commit adjusted
the checksumming code to recognize and ignore such regions. However, if the
mapping is created from a cloned file (e.g. because /tmp is a btrfs file system),
we do not create a separate SIGBUS region, instead relying on the regular
semantics for mapping files to apply. The above commit caused a problem
for this case, because we wouldn't record the checksum for the mapping beyond
the end of the underlying file, expecting it to be the special SIGBUS region
during replay. However, it …

Fix checksum_sanity test when tmp files were cloned

---

src/RecordCommand.cc
src/RecordSession.cc
src/RecordSession.h

* Allow specifying a particular CPU to bind to
* Take into account current cpuset CGroup when picking a random CPU
* Fix document about CPU binding

Improve CPU binding

---

src/ReplayTimeline.cc

Fixes #1959 hopefully (at least it fixed the specific failure caught
on the buildbot).

When running to mid point, don't accidentally go to end

---

src/test/nsutils.h

I think this does fix the issue in #1978, but I suspect we do still have an rr issue that is hidden by avoiding the signal during clone.

Add proper waitpid to nsutils

---

src/PerfCounters.cc

The infrastructure for collecting instructions retired is not used
anymore.

Delete dead code.

---

src/record_syscall.cc

This fixes src/test/gcrypt_rdrand.run on fedora 27. It was failing
because the newer glibc implements open with SYS_openat.

Expand the gcrypt handling to openat.

---

src/test/util.h

[test] Remove duplicated include of <sys/mount.h>

---

Vagrantfile

Requires VMware Fusion 10 or Workstation 14.

Added Vagrant support

---

CMakeLists.txt
src/GdbCommand.cc
src/ReplaySession.cc
src/ReplaySession.h
src/test/elapsed_time.c
src/test/elapsed_time.py
src/test/elapsed_time.run

Implements #2126 
I'm running the tests locally right now but it's taking a while so I'm going to open this PR for now and report back on the results of the tests.

GDB Command for elapsed time since start of recording

---

src/GdbCommand.cc
src/GdbServer.cc

Maybe not the greatest docs, but they're docs.

Document restart, checkpoint commands

---

src/TraceStream.cc

https://github.com/mozilla/rr/issues/2219

Fixed issue 2219: Trailing comma gives compilation error

---

src/record_syscall.cc

Truncate ioctl request code to 32-bits

---

CMakeLists.txt
src/LsCommand.cc
src/TraceStream.cc
src/TraceStream.h

I hadn't noticed the trace_save_dir() weirdness. It came in with 9767272. I fixed it but left it more or less as-is, since I couldn't tell where the right place to expose something like that would be. A static member of StreamWriter, maybe? But I figure there's not much point in me guessing when you can just tell me.

CLI `ls` command

---

src/GdbConnection.cc

I would want to propose part of the solution for https://github.com/mozilla/rr/issues/820 issue, where I replaced manually memory management for combining a packet string with `std::stringstream`.
Moreover I found little bug in previous implementation: `maxlen` variable didn't counted dot sign from `"p%02x.%02x,"` in `snprintf`, therefor value was lesser than it probably should be.

Remove manual memory management in `GdbConnection::reply_get_thread_list()`

---

src/test/util.sh

This is useful when running the tests through a test harness that checks the exit code for failure rather than parsing the test output.
This change also renames leave_data to test_passed (and inverts the "y"/"n" logic), since the variable is now used for more than just choosing whether or not to retain the test data.  As part of that, I've changed the comparisons to always compare to "y", on the idea that any bug that causes a non-"y"-or-"n" value should be treated as a failure.
Tested by confirming that the results of "make check" are consistent before and after this change, on a setup with a handful of pre-existing test failures.

Emit a nonzero exit code from the test-runner when a test fails.

---

src/test/copy_file_range.c

This is needed to support versions of glibc older than 2.27, per https://manpages.debian.org/unstable/manpages-dev/copy_file_range.2.en.html.

Use syscall() to invoke copy_file_range, to support older glibc versions.

---

CMakeLists.txt
src/kernel_abi.cc
src/kernel_abi.h
src/record_syscall.cc
src/test/ioctl_sg.c
src/test/util.h

Add ioctls SG_GET_VERSION_NUM and SG_IO with test.

---

src/PerfCounters.cc

Added PmuConfig for Intel Cometlake.

---

src/log.cc

This allows to capture multiple runs of RR into
a single log file.

Add RR_APPEND_LOG_FILE.

---

src/Task.cc

After fork() in a multithreaded program, the child can safely call only
async-signal-safe functions, and malloc is not one of them (see man
fork). This e.g. breaks with tcmalloc.

Don't use heap allocations after fork before exec.

---

src/Dwarf.cc

(Flagged by Lintian, the Debian QA tool.)
Signed-off-by: Stephen Kitt <steve@sk2.org>

“Unknown” spelling fix

---

src/preload/syscallbuf.c

This makes one of our test cases about 25x faster. It's still not
great - about 3.5x overhead total, but acceptable for the moment.
It looks to me like the remaining overhead is essentially all due
to context switches for syscallbuf flushing.

Add syscall buffering for statx/rmdir

---

src/util.cc

Amir Goldstein pointed out to me on linux-fsdevel that the
copy_file_range syscall has a number of tricks that it can
play that the naive fallback implementation cannot get away
with. For example, if the source and the target are on the
same filesystem, it can apply a clone operation even if a
regular clone would fail with EXDEV (I had written to ask
whether that latter restriction could be lifted - since I
noticed we weren't cloning files across mount namespace
boundaries). Of course, even if it can't do anything fancy,
doing the copy entirely in the kernel avoids costly round-trips
to userspace, so when the syscall is available, it's probably
always preferable.

Try to use copy_file_range in copy_file fallback

---

src/RecordCommand.cc
src/record_syscall.cc

Mention --preserve-env=HOME for --setuid-sudo

---

src/util.cc

Fix build if SYS_copy_file_range is not defined

---

src/Monkeypatcher.cc

Vsyscall build fix

---

src/AddressSpace.cc
src/CPUIDBugDetector.cc
src/kernel_abi.cc

We're getting close to having something usable on master - quite exciting. Here's just two minor commits while I get one of the bigger ones ready.

Two small aarch64 tweaks

---

src/preload/syscallbuf.c

Some legacy syscalls are undefined on aarch64. Build their hooks conditionally,
and replace them with the flags or *at versions where we need to call them manually.

Build fixes for undefined aarch64 syscalls in syscallbuf

---

src/Monkeypatcher.cc
src/assembly_templates.py

Mostly straightforward. The only difficulty is that the immediate is not at a byte boundary in the instruction on Aarch64 so our current AssemblyTemplate magic wasn't quite powerful enough to handle it.

Aarch64 vdso patching support

---

src/ReplayTimeline.cc
src/ReturnAddressList.cc
src/ReturnAddressList.h
src/Task.cc

Disable ReturnAddressList on aarch64 

---

src/RecordSession.cc
src/Registers.h
src/ReplaySession.cc
src/kernel_abi.h
src/record_syscall.cc
src/replay_syscall.cc
src/test/bad_ip.c
src/test/blocked_bad_ip.c

No real unifying theme here other than "I tried things and this is what broke".
Should all be relatively straightforward.

Aarch64 grabbag

---

src/RecordSession.cc
src/RecordTask.cc
src/SeccompFilterRewriter.cc
src/record_syscall.cc
src/replay_syscall.cc
src/syscalls.py
src/test/blocked_sigill.c
src/test/break_int3.py
src/test/int3.c
src/test/int3_ok.c
src/test/sigill.c
src/test/signal_checkpoint.py
src/test/signal_stop.py
src/test/util.h

As before, these are the collection of misc standalone changes that I'm cherry-picking from my WIP branch. Generally they each correspond to one test. I have a couple bigger changes in the oven, but they're still cooking, since I'm still finding ways in which they're not quite right. These changes on the other hand are hopefully small/simple enough that I won't find any surprises here later.

Misc aarch64 changes (part 4)

---

src/record_syscall.cc

aarch64 does not have the pause syscall. glibc uses ppoll with all
zero arguments which has the same effect. However, this requires
more register modifications, so we need to do some work to avoid
TaskSyscallState trying to point our registers at the scratch.

Switch pause to ppoll

---

src/DiversionSession.cc
src/PerfCounters_aarch64.h
src/Registers.cc
src/Registers.h
src/ReplaySession.cc
src/ReplayTimeline.cc
src/Task.cc
src/Task.h
src/ThreadDb.cc

Just a collection of misc aarch64 issues I saw in the tests, plus two fixes for prior commits that already got merged, but had issues.

Fix misc aarch64 issues

---

src/ExtraRegisters.cc
src/RecordSession.cc
src/Task.cc
src/ThreadDb.cc
src/kernel_abi.h
src/record_signal.cc
src/util.cc
src/util.h

Sorry for the delay. This PR is related to #2597.
The given 6 commits help to build current git in a debian stable VM.
It passes all tests except these:
```
The following tests FAILED:
898 - nested_detach_wait (Failed)
899 - nested_detach_wait-no-syscallbuf (Failed)
1118 - nested_detach (Failed)
1119 - nested_detach-no-syscallbuf (Failed)
```
From my point of view it looks like the child process started by the nested rr has no valid instruction pointer.
I would be glad to get some feedback to change some of the hacks to proper patches.

[WIP] Improve 32 bit build.

---

src/PerfCounters.cc
src/PerfCounters_x86.h

add Intel Icelake

---

src/RerunCommand.cc

Obtain Task from session again in `src/RerunCommand.cc`

Obtain task from session again in rr rerun loop

---

src/ExtraRegisters.cc

It was observed on kernel 5.2.3 that the PKRU register was occasionally being modified after involuntary context switches. This can make the PKRU feature appear to be "in use", which negatively impacts trace portability by making the trace unreplayable on CPUs which do not support the PKRU feature.
This is apparently caused by the kernel not fully updating the PKRU register if the associated feature bit is not set. To work around this, we should always set the PKRU bit after resetting the registers if the feature is supported by the CPU, so that any intended register modifications are consistently applied.

Set PKRU bit after reset if CPU supports it

---

src/PerfCounters_x86.h

Before 610884f, what is now in reset_arch_extras was only run if
supports_txcp is set, but this check was replaced with
!running_under_rr(). The test is however necessary, presumably, on all
x86 platforms that don't support txcp.
Fixes #2657

Skip x86 reset_arch_extras when supports_txcp is not set

---

src/ExtraRegisters.cc

Check for the PKRU bit in XCR0

---

src/PerfCounters.cc
src/PerfCounters_x86.h

Support for AMD Zen-based processors

---

src/PerfCounters_x86.h

Also fix comments that switched Matisse and Rome/Castle Peak
Fixes #2679

Fix microarch id for Zen Renoir

---

scripts/zen_workaround.py

- Add a --check argument that tells the current status.
- Try to detect if the workaround sticks or not.

zen_workaround: Various improvements

---

scripts/zen_workaround.py

It has been confirmed that the workaround sticks when SSB mitigation is
either fully enabled or disabled, as opposed to configurable per
process.

zen_workaround: Don't enable SSB mitigation when the kernel doesn't allow it

---

src/record_syscall.cc
src/test/sioc.c

Implement ETHTOOL_GPERMADDR

---

src/test-monitor/test-monitor.cc

The way we're using the test monitor, we have two independent file
descriptors that refer to the same file. This results in corruption
of the logs if one of the later tasks the dumping does results in
rr outputting additional output to stderr (e.g. assertion failures
in the GDB server or on process exit).
I believe this should fix the log file corruption I saw in #2699,
but unfortunately, that issue also stopped reproducing for me,
so I'm not 100% sure.

test-monitor: Adjust stderr position after dumping process state

---

src/PackCommand.cc

The new `rr pack --symlink` option creates symlinks in the trace directory instead of hashing and copying files into the trace.

Add symlink option to pack command

---

src/Task.cc

Closes: mozilla#2605
On top of 051fdb32 all tests passed on the first run except:
* x86-64: VM at Intel CPU: record_replay succeeded on second attempt, deliver_async_signal_during_syscalls failed
* x86-64: directly at Ryzen CPU: conditional_breakpoint_offload succeeded on second attempt
* x86-32: VM at Intel CPU: record_replay succeeded on second attempt

Notify kernel about moving VDSO to a different location.

---

src/Session.cc

See also https://github.com/rr-debugger/rr/issues/2682#issuecomment-727237488.
Thanks to @JohannesEbke.

Fix wrong breakpoint address reported in log

---

src/Monkeypatcher.cc
src/assembly_templates.py

_dl_runtime_resolve has a weird stack frame (because of how the PLT trampolines into it). When the function is entered the return address is *not* at %rsp. The dynamic linker has CFI directives to tell a debugger what's going on, but if we jump out of the binary into our patch code there's no clue for gdb what's going on. Gdb decides that whatever's at %rsp must be the return address (per the normal x86-64 ABI at function entry) and writes a breakpoint there. But that location is actually pointing to data associated with the PLT! Bad things ensue.
Fixes #2757

Use a call rather than a jump to get to the _dl_runtime_resolve patch.

---

src/Task.cc
src/test/detach_state.c

rr clears MAP_GROWSDOWN from any mappings it creates and emulates
the effect itself. As a result, when iterating over the kernel
maps, these flags do not show up. However, they are still present
in the AddrSpace copy of these mappings, so iterate over that to
make sure they get appropriately restored after detach. Writing a
test for this is a bit tricky as the linux kernel is not very
consistent about whether or not it actually allows a map to grow.
However, all factors simply depend on kernel boot parameters and
the address layout, so this test forks, creates a new GROWSDOWN map
in the same place and simply checks if the kernel will grow it.
If not, the test is skipped.

In detach, use the proper MAP_* flags

---

src/Task.cc

Issue #2777 pointed out that regions that are shared between
the tracee and rr get zeros rather than preserved during detach.
This is not usually a problem, as we don't really want to use
those regions anymore after rr detaches. The one execption to
this is that we still need to sucessfully get out of the syscallbuf
if we happen to currently be in it (we do lock the syscallbuf, but
it's possible that the syscall that caused the detach was patched).
This is usually not a problem either, but on x86, the
_switch_stack_vsyscall code uses the preload thread locals as
a scratch area, so if we zero the thread locals and we happened
to enter the syscallbuf through that path things would crash
(as in #2777). Now, the thread-locals are a bit special because
rr manages them itself, so this is simply …

Detach: Properly restore rr-private regions

---

src/PerfCounters.cc
src/PerfCounters_x86.h

Add Intel Tigerlake
See issue #2811

Adding Intel Tigerlake

---

src/PerfCounters.cc

As discussed in #2720, we regularly encounter the
`!counting_period || interrupt_val <= adjusted_counting_period`
assertion on AMD systems. Since recording capability doesn't seem
otherwise affected and it is possible that this is just a
manifestation of overlong NMI interrupts on AMD systems, turn
this assertion into a warning during record. On replay, we would
have overshot our ticks target, so leave that as a fatal assertion.
Of course, in theory, we could always try again on replay, since this is an
intermittent effect. However, for now, just try to make sure not to
unnecessarily abort during record, which (for us) is the more critical
operation.

Turn ticks overshoot assertion into a warning

---

CMakeLists.txt
src/syscalls.py
src/test/chmod.c

This resolves #2822. I noticed that the chmod.c test already tests `access` so I just added the 2 extra lines there
to test faccessat rather than duplicating the file.

Fix faccessat2

---

src/ReplaySession.cc
src/util.cc
src/util.h

Give a loud warning for unrecorded extended AMD CPUID leaves

---

src/Monkeypatcher.cc

This could lead to a spurious Event::patch_syscall() being added to trace.
Also:
- Don't print any LOG message that you've patched syscall unless
you've already exit_syscall_and_prepare_restart()-ed successfully
- Tweak LOG message. Use word "Patching" instead of "Patched" to account
for situation in which patching may actually fail when attempted.

patch_syscall_with_hook() can fail; don't assume it always succeeds

---

src/DiversionSession.cc
src/GdbServer.cc
src/test/call_exit.py

Just a couple of small fixes for issues I stumbled upon when working on something else.

Diversion exit fixes

---

src/DiversionSession.cc
src/GdbServer.cc
src/ReplaySession.cc
src/ReplayTimeline.cc
src/Session.cc
src/Session.h

This should address #2881.
@bernhardu: Would you mind testing this to make sure it resolves the problem?

Fix task use after free from `DiversionSession::diversion_step`

---

CMakeLists.txt
src/test/vdso_parts.c

I noticed that the commit 3857152 did just modify the 64-bit rrpage.
Are these sections expected to be part of the 32-bit rrpage too?

Ensure our 32-bit VDSO has the same additional sections like 64-bit VDSO.

---

src/kernel_abi.cc
src/kernel_abi.h
src/kernel_supplement.h
src/record_syscall.cc
src/test/seccomp.c
src/test/util.h

Implement GET_ACTION_AVAIL and GET_NOTIF_SIZES for seccomp

---

src/TraceStream.cc

fixes #2843
issue and code change originally posted by @jbapple

fix -Werror=class-memaccess #2843

---

src/GdbCommandHandler.cc

fixes #2922
also calculates the not changing string length only once

hardening gdb_unescape

---

src/ReplaySession.cc
src/SourcesCommand.cc

More spelling fixes identified by Lintian, the Debian QA tool.
Signed-off-by: Stephen Kitt <steve@sk2.org>

Spelling fixes

---

src/log.cc

This adds a small patch which I'd forgotten to upstream to move the
`flush_log_buffer` before the non-interactive abort case, to make
sure the log buffer gets printed in that case. While we're at it,
also prevent `dump_last_events` from overwriting the buffer with
lots of debug spew as we read back the trace.

Slight log printing improvement for FATAL errors

---

README.md

This badge shows whether or not CI is passing on the latest commit on the `master` branch.
Additionally, clicking on the badge will bring the user to the Buildkite dashboard[^1] for this repository.
[^1]: https://buildkite.com/julialang/rr

Add the Buildkite CI badge to the README

---

src/util.cc

`rr` defaults with its choice of debugger PID to `(short)getpid()`
(which is useful because the port correlated to the PID, so it's
easy to see what it's connected to)  and then does a linear probe
from there. However, as seen in [1], this causes trouble when
`(short)getpid()` happens to be `0`, because that tells to kernel
to just pick a port. Also it's not quite as useful on busy machines
since they tend to have large PID spaces, so `(short)getpid()`
may look little like the actual PID (in decimal).
This fixes the issue by reading the assigned port from the kernel,
but it also stops the linear probing and just asks the kernel to
assign a port if the first choice of port is unavailable.
While we're here also fix the DONT_PROBE path to actually print the
error message, rather than simply …

Fix debugger port probing code

---

scripts/zen_workaround.py

If a PermissionError is thrown when trying to write to MSR, we try checking for if Secure Boot is enabled.
If the check succeeds, and secure boot is enabled, tell the user to try disabling it. If the check fails, we still hint the user to try disabling secure boot.

Zen Workaround - added check for Secure Boot

---

src/util.cc

When choosing a CPU to bind to, we need to be sure not to attempt
to bind to a CPU that is disallowed by cgroup configuration. We
had existing to code that tried to do this by reading the
appropriate config out of /sys/fs/cgroup/cpuset.
However, the cgroup does not necessarily need to be mounted inside
the container. In such cases rr would crash with a fatal error (if
CPUID faulting is unavilable). Fortunately, the same information
is available in `/proc/self/status`, which is already required to
be available in order for rr to work at all.
Fixes #3100
cc @staticfloat @DilumAluthge

Make cgroup read robust against /sys/fs/cgroup not being mounted

---

.buildkite/pipeline.yml

With #3109 addressed, we should be able to use more parallelism on CI.
Let's try it.

CI: Use More parallelism

---

src/PerfCounters_x86.h

rr seems to be broadly working and tests passing

Add AMD Van Gogh APU CPUID

---

.buildkite/pipeline.yml

CI: update the rootfs to v5.6

---

src/Monkeypatcher.cc

Missed two callers of updated functions in #3154

Fix monkey patch page offset

---

src/Task.cc

As noted in #3159, if one of the ticks assertions fails, we then subsequently
crash when attaching the emergency debugger, because rr doesn't think the
process is stopped.

Mark threads as stopped earlier

---

src/test/invalid_interpreter.c

This minimize the call to libc functions that might uses things from the linker.
On ArchLinux ARM the stack guard code in string scanning functions uses something
in the linker.
While we are at it, also make sure that we actually unmapped something and the test isn't a no-op.
Of course this isn't water tight yet, the libc version of mmap can still do something unexpected and causes a crash. This is enough to get the test to pass as intended on aarch64 at least....

Unmap the linker page only after the iteration finishes

---

src/test-monitor/test-monitor.cc

* Keep retry reading from the child if it hasn't exited yet.
* Add a 30 seconds timeout to the command. This helps when the remote side hangs.
Without this the test would hang indefinitely when the gdb remote connection hangs. I initially wrote the non-blocking loop since I thought the child was sleeping waiting for the pipe buffer to clear. I'm not sure that can happen anymore since the EOF should only be sent with the child has closed the file... In any case, I don't think there's a way to implement a timeout with popen easily so I'm just using the non-blocking loop to implement the timeout for now...

Make test-monitor more robust

---

src/util.cc
src/util.h

Limit CPU choices to the CPUs that are actually online

---

src/GdbServer.cc
src/GdbServer.h
src/ReplayCommand.cc
src/ReplayTimeline.h
src/test/barrier.c
src/test/expect_in_exit.py
src/test/fork_exec_info_thr.run

Implement rr replay -e/--goto-exit that stops the replay at the exit of a process

---

src/record_syscall.cc

handle_ptrace_exit_event() has logic to detect this case and would otherwise record a ghost clone in the trace which would really confuse the replay.
I'm not 100% sure if this is the right fix though I'm 90% sure this is what's causing ~5-10 tests to fail randomly.

Set state of new task as if just exiting from the syscall

---

src/preload/tweak_librrpage.py

At replay time, we map the last section of librrpage.so to 0x70000000
and claim that the mapping size from there is PRELOAD_LIBRARY_PAGE_SIZE.
While this is the case at record time since the page we are mapping
is the second last one, the page we map at replay time is the last page
which may not be completely filled in the file. Then if the runtime page size
is less than PRELOAD_LIBRARY_PAGE_SIZE, we'll get an error when trying to read
between 0x70000000 + page_size() and 0x70000000 + PRELOAD_LIBRARY_PAGE_SIZE.
This happens when Gdb tries to find our symbol table and unwind info on aarch64.

Make sure the librrpage.so file is large enough for replay

---

src/Monkeypatcher.cc

Implement patch_at_preload_init_arch for aarch64

---

src/PerfCounters.cc

Coming out of some refactoring for more generally support of PMUs on ARM systems with asymmetric cores.

Two cleanup of perf counter code

---

src/record_syscall.cc

It appears that these are implemented and also used by rr itself.
This causes issue when recording a replay session without syscallbuf.

Implement PTRACE_(PEEK|POKE)(TEXT|DATA) on AArch64

---

src/test/rseq.c
src/test/rseq_syscallbuf.c

* Implement the restartable sequence on aarch64
* Use hidden symbol to make sure we are refering to the correct one

Fix rseq test

---

src/ReplaySession.cc
src/fast_forward.cc
src/remote_code_ptr.h

Fix code that assumes the pc points to after the breakpoint instruction
after hitting the breakpoint.

Fix more breakpoint handling on aarch64

---

CMakeLists.txt
src/GdbConnection.cc
src/GdbConnection.h
src/GdbServer.cc
src/test/gdb_qpasssignals.c
src/test/gdb_qpasssignals.py
src/test/gdb_qpasssignals.run

Implements features from #2175

Implement handling for QPassSignals

---

src/preload/syscallbuf.c

poll does not exist on aarch64 and the glibc wrapper always call ppoll instead.

Implement syscallbuf for ppoll

---

src/preload/syscallbuf.c

The initial content of `*optval` is actually used by the syscall
(i.e. it's an in-out parameter) and this is actually used by the netfilter test.
This causes intermittent netfilter test failure when the content
of the info causes the syscall to return an error not handled by the test.
(In most cases it just return `ENOENT` signaling that the table doesn't exist)
The man pages for getsockopt does not seem to mention this issue somehow and I accidentally noticed this due to a one-off test failure on aarch64. The man page does seem to mention that `optval` can be null and it seems that the old code intends to handle null `optlen` (even though it does so incorrectly) so I added a simple bail out case for it. We can probably handle that without bailing out too if it's important...

Fix syscallbuf for getsockopt

---

src/AutoRemoteSyscalls.cc

before having a chance to report the syscall exit to us.
This seems to be causing a hang in `cont_race` test recording a few % of the time on M1...

Do not block forever if the tracee died right after recieving the fd

---

src/RecordTask.cc

This actually happens the most often when I run the `cont_race` test in a racy way (multiple run sharing the same `fifo`)....

Handle unexpected tracee exit in syscallbuf initialization

---

src/test/vm_readv_writev.c

Based on the observation on the aarch64 test machine with `5.4.0-90-generic #101-Ubuntu SMP` kernel.
Ref a327ab1ce252e143c5dd527fa51b487787882598
Ref https://github.com/rr-debugger/rr/pull/3235#issuecomment-1168702535, should fix the test failure in `vm_readv_writev` on CI.

Handle different process_vm_readv and process_vm_writev return values

---

src/preload/syscallbuf.c
src/record_signal.cc

On the current asahi kernel and on the test machine (but not on the rb5 kernel
or the ArchLinux x86_64 kernel), somehow the `getsockopt` in `netfilter` test
takes 10-20 times longer to finish and may also return `EFAULT` when interrupted
by a signal. This broke restart of the syscall, which expect `ERESTART*` instead.
I strongly suspect both of these are caused by the `CONFIG_BPFILTER_UMH` kernel option
and in particular the `int bpfilter_send_req(struct mbox_request *req)`
in `bpfilter_kern.c` that talks to the user mode helper.
Assuming I understood how this works, it seems that this function
always returns `EFAULT` on error no matter what the error was.
While this can happen for user code regardless of rr,
it would be nice to reduce the effect of signals caused by rr.
For now, this …

Fix getsockopt syscallbuf signal restart

---

.buildkite/lib/types.jl

To be merged once #3307 is in.
cc @yuyichao

CI: Enable commit-status reporting for aarch64

---

.android/build.sh
.android/cloudbuild.yaml
CMakeLists.txt
src/GdbConnection.cc
src/preload/overrides.c

These are the final non-test patches I'm carrying for bionic, and I think they should be straightforward.
Using the "rr-android-testing" on GCP (which I control) is a kludge until Google gets something more permanent set up here.

Build on Android

---

src/syscalls.py
src/test/clock.c

Requested by @maleadt from this CI failure log: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2022-07/20/InterProcessCommunication.primary.log

Support clock_settime

---

src/RerunCommand.cc
src/kernel_abi.h
src/util.cc

Backports fixes from https://github.com/JuliaPackaging/Yggdrasil/pull/5202 found while trying to build rr for aarch64 on the julia deployment infrastructure.

A couple small build improvements

---

src/RecordTask.cc

Should hopefully fix the CI failure in [1].
[1] https://buildkite.com/julialang/rr/builds/808#01822373-7bf8-4584-a03f-20253923dde1

Mark thread as dying when PTRACE_SETSIGMASK fails

---

CMakeLists.txt
src/RecordCommand.cc
src/RecordSession.cc
src/RecordTask.cc
src/RecordTask.h
src/ReplayCommand.cc
src/Scheduler.cc
src/Scheduler.h
src/Task.cc
src/WaitManager.cc
src/WaitManager.h
src/record_syscall.cc
src/util.cc

@Keno @khuey you might want to look at this, it's somewhat invasive.

Wait manager

---

src/PerfCounters_x86.h

Add the CPU type code for Zen4 desktop processors

---

src/record_syscall.cc
src/test/ioctl_sg.c

Fixes https://github.com/rr-debugger/rr/issues/3394 .  Allows use with [cdparanoia](https://xiph.org/paranoia).

Support some more SG_ ioctls

---

CMakeLists.txt
src/AddressSpace.cc
src/test/watchpoint_unaligned2.c
src/test/watchpoint_unaligned2.py
src/test/watchpoint_unaligned2.run
src/util.h

I don't think I can explain this any more concisely than I did in the code comment.

Fix watchpoints on AArch64

---

.buildkite/lib/generate.jl

We've updated our buildkite tags a bit, this matches the new configuration

Adjust buildkite setup

---

src/SourcesCommand.cc

By convention, the DWP for `/path/to/exe` is at `/path/to/exe.dwp`. This adds codes to `rr sources` to go looking for the DWP for any binary that has any DWOs. If found, a DWP is reported under `extra_debug_info` with a new type of `dwp`.
Some consumers (e.g. pernosco-submit) will want to skip the DWOs when a DWP is present. This adds a `build_id` field to the DWO entries that allows a consumer to match the binary containing DWOs to the binary the DWP is for. There's no actual guarantee that all the DWOs are in the DWP but I don't intend to support partial DWPs for Pernosco.

Teach rr sources about dwp files.

---

src/preload/overrides.c

Right now we're triggering a deadlock reentering the allocator when jemalloc calls into our pthreads hooks, we call dlsym for pthread_mutexattr_setprotocol, and then dlsym allocates.
Fixes #3427

Restore some of the pre-2.34 behavior for pthread_mutexattr_setprotocol to fix Firefox

---

src/PerfCounters_x86.h
src/counters-test/counters.c

this patch fix the issue https://github.com/rr-debugger/rr/issues/3431

add support for intel cpu type 0x506c0, fix #3431

---

CMakeLists.txt

Previous discussion is in #2890.

Add cmake option to build with address sanitizer.

---

CMakeLists.txt

This would be a preparation for two of the ASAN patches in #2890.

Build main.cc with the same flags as other rr sources.

---

src/util.cc

Avoids error message:
```
Running thread 2156188 was not suspended. False leaks are possible.
ERROR: LeakSanitizer: detected memory leaks
```
Affected tests:
```
clone_cleartid_coredump
```

ASan: Disable LSan after fork in coredumping_signal_takes_down_entire_vm.

---

src/test/sioc.c

Followup to e5a6c868d211.
This issue is currently just observed at host amdci1 within the CI infrastructure.
This run shows the output of the test at amdci1 (manually forced the test to fail):
https://buildkite.com/julialang/rr/builds/1124
And a succeeding run at amdci1:
https://buildkite.com/julialang/rr/builds/1125

Allow some more ioctl in sioc tests to return EADDRNOTAVAIL.

---

src/GdbCommandHandler.cc
src/test/madvise_dontfork.c
src/test/madvise_dontfork.py

Encode and decode UTF-8 in gdb_escape & gdb_unescape

---

src/preload/syscallbuf.c

This is a bit tricky because this syscall has multiple names. On amd64 and arm64 it's newfstatat (which we ignore elsewhere in rr and just call fstatat), and on i386 it's fstatat64.

Buffer fstatat family of syscalls.

---

src/PerfCounters_x86.h

One line patch I needed to do to support my N5095.

Add support for Celeron N5095

---

CMakeLists.txt
src/MemoryRange.h
src/kernel_abi.h
src/record_syscall.cc
src/test/bpf_query.c

Support BPF_PROG_{QUERY,ATTACH,DETACH}

---

src/test/chmod.c

chmod test: fix for fchmodat2 `test_assert`

chmod test: fix for fchmodat2 test_assert

---

src/PerfCounters_x86.h

honor suppress_environment_warnings for Zen warning

---

src/test/util_syscall.h

```diff
-#define RRUTIL_SYSCLAL_H
+#define RRUTIL_SYSCALL_H
```

fix typo in #define

---

src/AddressSpace.cc

When running a program under rr, we remove MAP_GROWSDOWN from the stack mapping. If rr in chaos mode subsequently places a mapping immediately above the stack, it will actually get merged into the same VMA.
This is a problem because glibc actually looks at /proc/self/maps to dig out the stack top in pthread_attr_getstack; this will be wrong if the stack VMA is actually merged with another one. I believe the kernel will not actually do this on its own; it won't, without some prompting, map memory above the stack and leaves a gap below the stack.
glibc source: https://sourceware.org/git/?p=glibc.git;a=blob;f=nptl/pthread_getattr_np.c;h=1e91874767d894ef16b0bd62649a22990ca2eeae;hb=HEAD#l85
Thanks to @rianmcguire for working on this with me

Don't allow chaos mode to map memory such that it merges with the stack

---

src/test/group_stop_thundering_herd.c
src/test/ptrace_group_stop.c

follow up to ec66b21 + 5d72fce fixing (part of) the build on RHEL8

use sys_gettid
