rr-debugger/rr

src/GdbServer.cc
For example, if we do an `emergency_debug()` while the Task is being initialized.  This fix was useful in me tracking down the new issue in #16, so I'm going to go ahead it even though there are probably lots of other sites that assume a vm exists.  Found by valgrind.
=> Tasks may not have an address space if in an inconsistent state.

src/test/getrandom.c
__NR_getrandom may not be defined on the build system, and I forgot that the libc `syscall` helper sets errno for you.  Followup to #1379.
=> Fix the getrandom test.

src/Command.cc, src/HelpCommand.cc, src/main.cc, src/main.h
This changes the help command to print to stdout and to exit with
status 0.  The rationale for stdout that this makes "rr help | more"
work nicely.  The rationale for "exit 0" is that the command worked as
requested.
=> make the help command print to stdout and exit 0

CMakeLists.txt, src/record_syscall.cc, src/syscalls.py, src/test/intr_pselect.c
The Qt framework uses pselect6 in its eventloop and when creating subprocesses.
[pselect6](http://lxr.free-electrons.com/source/fs/select.c?v=3.18#L700) has a sigmask param, but I'm not storing it in src/record_syscall.cc. Following the example of ppoll. I assume that only the parameters that must be stored for replay are passed to syscall_state.reg_parameter(). We record the signals that the process receives, so the sigmask serves no purpose for replay.
Was uncertain about using IN_OUT for the timeout param. The man page for pselect states that it does not update its timeout argument, but [the syscall does](http://lxr.free-electrons.com/source/fs/select.c?v=3.18#L310). The glibc wrapper hides that:
int
__pselect (int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds,
const …
=> Support pselect6 syscall.

src/generate_syscalls.py, src/test/cpuid.run, src/test/util.sh
Specifying the exact version makes python invocation less ambiguous and
eases its usage on systems which don't link python to python2.
Hopefully nowadays the python2 symlink is installed on all modern
distributions.
=> Invoke python more precisely

src/record_syscall.cc, src/test/prctl.c
DNS server BIND is not going to work without this.
=> Support prctl PR_GET_KEEPCAPS and PR_SET_KEEPCAPS

src/test/xattr.c
This also fix an access to uninitialized string `path`.
=> Fix superfluous mkstemp call in xattr test case.

doc/rr.html, src/GdbServer.cc, src/test/breakpoint_overlap.py, src/test/read_big_struct.py, src/test/rrutil.py, src/test/step_thread.py
=> Use "(rr)" for the gdb command prompt rather than "(gdb)"

doc/rr.html, src/main.cc
Fedora since 22 has replaced YUM with DNF, which uses largely the same syntax.
=> Replace references to Fedora's YUM with DNF.

CMakeLists.txt
Fixes the following assertion that happens when i run 
$ rr echo
$ rr replay
[FATAL /home/dannas/code/external/rr/src/AutoRemoteSyscalls.cc:451:check_syscall_result() errno: 0 'Success'] 
(task 11774 (rec:26039) at time 14)
->  Assertion `false' failed to hold. Syscall openat failed with errno ENOENT opening usr/local/bin/rr_page_64_replay
=> Add rr_page_{32,64}_replay as install targets.

CMakeLists.txt, src/record_syscall.cc, src/test/tiocgpgrp.c
Fixes replay for mpv, which uses tcgetpgrp(0) to check if the terminal is in foreground.
----
Finally found something that I can reasonably do for this project :D
Hopefully I did everything right.
Fun fact: the mpv bug i'm dealing with is related to xv shared memory, but there's another conditional branch in the same function for when shared memory isn't supported, and I didn't know any better way to test that branch than using rr, taking advantage of the fact that it disables shm. And that's how this rr patch happened. Now I know that the non-shm code is just as broken as the shm code. Yay.
Also there's a typo in src/test/tiocgwinsz.c (which i obviously used for inspiration), it says "TIOCWINSZ" in the printf instead of "TIOC**G**WINSZ". I didn't touch that because I don't like to …
=> Add support for TIOCGPGRP ioctl

index.html
Drop linear-gradient global background. This background reduces contrast a lot, at least at the document's beginning, and makes the style of titles inconsistent across the document.
I understand this is a bikeshed-prone matter and I'm not an expert designer (my training is basically [this](https://www.goodreads.com/book/show/10875750-the-non-designer-s-design-book)), so apologies for sending a PR, but when I visited your website intending to hear more on your project, this was seriously my first reaction (I don't usually do this). I was in relatively low-light conditions, but still.
=> Improve contrast by dropping background

src/RecordSession.cc, src/Registers.cc, src/test/block.c, src/test/scm_rights.c
GCC 5.2.1 reports these as strict aliasing rule violation.
=> Fix strict aliasing violation.

src/script/setup_travis.sh
This should fix the travis-ci build that regressed with 0e3a9c9.
=> Install the gdb packet on travis-ci

CMakeLists.txt
This fixes several oddities in the CMake code, like bugs when built out-of-source and reimplementation of things that CMake can handle alone.
Btw: the canonical way in CMake to build both 32 and 64 bit code is to have 2 build directories and build both version independently.
=> Cleanup CMake code

src/assembly_templates.py
As noted in #1696, I accidentally left those instructions in when refactoring.
=> Remove superflous instructions in x86 hook template

src/test/cpuid_loop.S, src/test/ptrace_sysemu.c
- Inlining of my_geteuid caused a duplicate label
- cpuid_loop clobbered registers that the compiler expected to be preserved.
=> Fix failures when building rr with optimizations

src/GdbConnection.cc
Adding and removing an element at the end of the array should be cheap the vast majority of the time, so we may as well do this.
=> Log sent GdbConnection packets again.

src/RecordSession.cc
dc23125f make `rr record` do $PATH lookup on its own to check the
executable, but only checks if a matching file has the executable bit,
which is true of directories. In some corner case, where a directory of
the same name as a program is in one of the directories in $PATH, this
makes `rr record` fail with:
execve of '...' failed (EACCES)
So first check if a matching file is a regular file.
=> Only consider files when looking up executables in $PATH

src/test/sigreturn.c
On my machine (with `cc (GCC) 6.1.1 20160602`), the sigreturn-32 tests were failing due to the fact that the memcpy in [sigreturn.c:147](https://github.com/mozilla/rr/blob/05ead1f2d9699d44980e3e6cd8e7b95937306b6a/src/test/sigreturn.c#L147) got compiled to
```asm
movdqa xmm_bad,%xmm0
movaps %xmm0,-0x18(%ebp)
```
which would of course overwrite `%xmm0` before we get a chance to verify its contents were restored correctly. The fix is to simply initialize `xmm` with bad values beforehand.
=> Don't clobber registers in sigreturn test.

src/main.cc
a9fb580 removed the -W (aka --wait-secs) option, but left one
reference to it in the --help output.  This patch removes the
straggler.
=> Remove -W from help

src/ThreadDb.cc, src/ThreadDb.h
ThreadDb::initialized was unused.  While looking into this, I realized
that when clearing the symbol map, we might need to destroy any
existing internal handle; because td_ta_new might need symbol values
in order to work.  This patch replaced |initialized| with
internal_handle as a sentinel and arranges for
get_symbols_and_clear_map to destroy the old internal handle.
=> clean up ThreadDb initialization

src/test/sioc.c
They don't support a number of the tested ioctls, causing this test
to fail.
=> In sioc, ignore tun/tap devices

CMakeLists.txt, src/FdTable.cc, src/FdTable.h, src/FileMonitor.h, src/MagicSaveDataMonitor.h, src/MmappedFileMonitor.cc, src/MmappedFileMonitor.h, src/PreserveFileMonitor.h, src/ProcFdDirMonitor.cc, src/ProcFdDirMonitor.h, src/ProcMemMonitor.cc, src/ProcMemMonitor.h, src/RecordSession.cc, src/RecordTask.h, src/ReplayTask.cc, src/StdioMonitor.h, src/VirtualPerfCounterMonitor.h, src/kernel_abi.cc, src/kernel_abi.h, src/preload/preload_interface.h, src/record_syscall.cc, src/replay_syscall.cc, src/test/clone_newflags.c, src/test/gcrypt_rdrand.run, src/test/mmap_shared_write.c, src/test/proc_fds.c, src/test/shared_map.c, src/util.cc, src/util.h
The heavy lifting here is hiding all of rr's private fds from Chromium's sandboxing code.  To do this, we get rid of the constant MAGIC_SAVE_DATA_FD (replacing it with a syscall that hands out a dynamically constructed fd instead) and hide rr's remaining fd's beyond the current fd limit.  It's not necessary for chromium, but we could lie about the maximum fd limit to stop the tracee from raising the current limit into rr's private area.
We also have to disable RDRAND support in both OpenSSL (BoringSSL thankfully uses the same env var) and gcrypt (used by chromium's native password keyring integration).
Chromium builds SQLite in a special way that uses mmap for reading but syscalls for writing.  Support for that is added for the simple cases (the fd being written to and the fd that was …
=> Get rr working with chromium

src/AddressSpace.cc, src/AutoRemoteSyscalls.cc, src/ElfReader.cc, src/Monkeypatcher.cc, src/RecordTask.cc
This is part of #16. I wanted to be able to run valgrind on rr since I seem to have a tendency to forget to initialize variables ;). The second commit fixes the issues valgrind complained about during `valgrind rr record ls`. None of them too serious, but there was a string out of bounds access, which I suppose could cause a crash if you're unlucky.
For those following along at home, I have a valgrind patch for perf events ioctls, which may be needed: https://bugs.kde.org/show_bug.cgi?id=368419.
=> Fix running valgrind on rr and issues identified it

CMakeLists.txt, src/RecordTask.cc, src/RecordTask.h, src/kernel_abi.h, src/record_syscall.cc, src/test/intr_pselect.c, src/test/ppoll.c, src/test/sigprocmask_rr_sigs.c
The recent changes to more aggressively verify that our signal states are correct exposed a bug when running Chromium.  We're not handing ppoll and pselect6's adjustments to the sigmask at all.
This PR generalizes the infrastructure used for sigprocmask a bit and then uses it for ppoll and pselect6.
=> Handle the sigmask modifying aspects of ppoll and pselect6.

CMakeLists.txt, src/AddressSpace.cc, src/AddressSpace.h, src/ReplayTask.cc, src/test/jit_proc_mem.c, src/test/jit_proc_mem.py, src/test/jit_proc_mem.run
JITs sometimes use /proc/self/mem or proc_vm_writev to write data
directly to an RX page. See #1821 for a description on why this
caused problems before. This commit fixes that case (scenario 1 in
that issue), but does not fix the more complicated cases.
=> Don't fall over if a system call modifies a breakpoint location

CMakeLists.txt
Unlike librrpreload, librr is not private to rr, so it should go into
the main /usr/lib directory.
I don't feel too strongly about this one, but if we're being
pedantic about library paths, this seems like the correct thing
to do. This was changed in 7781ab8971387a096c77ee212b2dda26d9f3d645, though perhaps not intentionally. cc @skitt
=> Install librr (if enabled) in /usr/lib

src/test/fxregs.c
The `cpuid` function gives back `ecx` and `edx`, not `ebx` and `ecx`.
=> Fix AVX detection in fxregs test

src/MmappedFileMonitor.cc, src/MmappedFileMonitor.h, src/record_syscall.cc, src/replay_syscall.cc, src/test/mmap_shared_write.c
While we're at it, keep track of whether or not that's the case, to avoid having
to scan all mappings in the system on every write.
Reported by @yuyichao
=> Allow `write` on fds that were MAP_SHARED if all mappings have been unmapped

CMakeLists.txt, src/FdTable.cc, src/FdTable.h, src/FileMonitor.cc, src/FileMonitor.h, src/MagicSaveDataMonitor.h, src/MmappedFileMonitor.cc, src/MmappedFileMonitor.h, src/ProcMemMonitor.cc, src/ProcMemMonitor.h, src/StdioMonitor.cc, src/StdioMonitor.h, src/Task.cc, src/Task.h, src/VirtualPerfCounterMonitor.cc, src/VirtualPerfCounterMonitor.h, src/record_syscall.cc, src/test/mmap_shared_write.c, src/test/proc_mem.c
We used to only support pwrite on `/proc/*/mem` and any fd, whose backing
file was mapped MAP_SHARED into a Task's address space. For a
regular `write` system call, we can't easily get the offset to write at
by just looking at the register state (which we need to know in order
to reflect these changes appropriately into memory). Luckily, the kernel
allows us to query a file descriptor's current position by reading
/proc/*/fdinfo. Use that to get the offset, but take care to only read
it when we're actually going to need it.
This time actually fixes the issue @yuyichao reported.
=> Support `write` calls on monitored file descriptors

src/AddressSpace.cc, src/RecordTask.cc, src/Session.cc, src/Task.cc, src/record_syscall.cc, src/test/mmap_replace_most_mappings.c, src/test/mmap_self_maps_shared.c, src/test/no_mask_timeslice.c, src/test/ptrace_remote_unmap.c
Came up in the review of #1867 as a desirable stylistic property.
=> Run clang-tidy's readability-braces-around-statements over the codebase

src/Monkeypatcher.cc, src/preload/preload.c, src/preload/preload_interface.h
On Ubuntu 16.10, the glibc read syscall wrapper is not patched, due to
what rr thinks is an interfering branch. In reality, it's just an unfortunate
subsequence of a different instruction in a different function. We can
fix this (and the severe performance regression caused by it) by improving
the heuristic, since this unfortunate byte sequence appears to target,
one byte after the end of the syscall instruction, which is not a valid
jump target for an actual interfering branch.
=> Improve Monkeypatcher interfering branch heuristic

CMakeLists.txt, src/Scheduler.cc, src/Task.h, src/test/kill_ptracee.c
When an emulated ptracee gets killed while in a ptrace/signal stop,
we would fail to notice the PTRACE_EXIT_EVENT for that task, since
we never waited on it, instead looking only for SIGCONT. If the parent
is waiting for the child to die, this causes a deadlock under rr.
=> Fix deadlock when a ptracee gets killed

CMakeLists.txt, src/RecordSession.cc, src/Task.cc, src/replay_syscall.cc, src/test/map_shared_syscall.c, src/test/ptrace_sysemu_syscall.c
This fixes a bug when replaying a syscall instruction that's on a MAP_SHARED page
(see second commit). While attempting to understand this issue, I wrote a test, which
encountered a small different bug (fixed in the first commit).
=> Fix replay of syscall instructions on MAP_SHARED pages

src/AddressSpace.cc, src/Registers.cc, src/test/timer.c
See commit message for detailed description. Also fix a formatting issue in the log I noticed while debugging this.
=> Fix rare corner cases in timer expiration

src/test/ptrace_tls.c
Without an explicit return value, this function fails to compile if warnings are
treated as errors:
"error: control reaches end of non-void function [-Werror=return-type]"
=> Add explicit return value to `main()` in `ptrace_tls.c`

CMakeLists.txt, src/test/timer.c
The current code throws "error: ‘for’ loop initial declarations are only allowed in C99 mode" for these
two loops. Adding `-std=c99` to `CMakeLists.txt` causes "error: implicit declaration of function ‘asm’
[-Werror=implicit-function-declaration]" for `asm()` in `src/test/blocked_sigill.c:20`. Changing these
loops to out-of-line the declaration seems like the simplest solution.
=> Drop loop initial declarations in `timer.c`.

src/PerfCounters.cc
As discussed in #1642, this is needed for rr to work on KNL. Still about a hundred failing tests or so, which I'll have to investigate, but it's a start.
=> Add Intel KNL cpuid

src/MonitoredSharedMemory.cc, src/Session.cc, src/Session.h
This function is only supposed to be used with mappings that were previously
created using create_shared_mmap. MonitorSharedMemory tried to use it on an
outside MAP_SHARED mapping, which happened to work if you got lucky and
extract_name came up with a name that was valid. However, since the name
in general doesn't have to follow any particular scheme, it was easy to come
up with one that wasn't (e.g. that contained slashes). Add a new function
(steal_mapping) that does what was intended here: replace an arbitrary mapping
with one shared with rr.
=> Fix incorrect use of recreate_shared_mmap

src/preload/breakpoint_table.S, src/preload/preload.c, src/preload/syscall_hook.S
The first three changes are general improvements to the unwind info in our preload library. They should be fairly uncontroversial, and in fact, with these changes (and manually telling the unwinder about our jump stubs), in a simple program I was able to determine that we have complete and correct unwind info at every instruction exercised in that program (it of course didn't go through all the paths in the preload library, but still something).
Unfortunately, gdb does not just use CFI to unwind, but relies on CFI coupled with a very large number of heuristics, which can override the CFI. It doesn't happen all that often, but sometimes gdb gets very angry at our stack switching scheme and aborts unwinding. The last commit implements an ugly workaround for this (x86_64 only, for now). The …
=> Various changes having to do with unwinding

CMakeLists.txt, src/AddressSpace.cc, src/AddressSpace.h, src/record_syscall.cc, src/replay_syscall.cc, src/test/checksum_sanity.c, src/test/mmap_zero_size_fd.c, src/util.cc
This was problematic both during record and during replay. During record,
we'd get -1 back from read_bytes_fallible since we can't read any bytes
from the mapping, and during replay, we'd run into problems, because
the memory map looks differently due to us creating special SIGBUS
regions. Address both and add a test to checksum_sanity that always
covers this case.
=> Fix -C for mmap entirely beyond its backing file

CMakeLists.txt, src/DiversionSession.cc, src/test/diversion_syscall.c, src/test/diversion_syscall.py, src/test/diversion_syscall.run
Otherwise a syscall that gets called during the diversion will try to interpret
the syscallbuf as its own data, wrecking all kinds of havok. Add a simple test
for this scenario.
=> Lock the syscallbuf during diversions

CMakeLists.txt, src/AutoRemoteSyscalls.cc, src/Monkeypatcher.cc, src/RecordSession.cc, src/RecordTask.cc, src/RecordTask.h, src/Registers.h, src/ReplaySession.cc, src/ReplaySession.h, src/Task.cc, src/Task.h, src/kernel_abi.cc, src/kernel_abi.h, src/preload/raw_syscall.S, src/record_syscall.cc, src/replay_syscall.cc, src/syscalls.py, src/test/cross_arch.c, src/test/mmap_replace_most_mappings.c, src/test/modify_ldt.c, src/test/set_tid_address.c
As mentioned on IRC, when using `int $0x80`, the kernel behaves as if the process were 32bit, contrary to rr's expectation, which is that it's just a different spelling of `syscall`. This adds some best-effort code to handle this. In my testing this works surprisingly well, and runs a couple of
the test cases I had tried, but I made no effort or attempt at rigorous testing of this functionality. There's a new warning message that gets printed in the log when a cross-arch syscall is detected though, so we should be able to figure out what's going on if we come across any real applications we care about that do this.
While I'm at it (it being weird corners of the x86 architecture), also clean up the modify_ldt support commit I had lying around locally. With both of these commits, I was also …
=> Best effort support for cross-architecture syscalls

src/preload/syscall_hook.S
Since this hook, skips on frame in the call chain, it needs special
unwind info. The generic unwind info includes the intermediate
frame, but with an invalid address (one past the end of that function),
confusing unwinders.
=> Special case CFI for 5a_5e_c3 hook

CMakeLists.txt
Prior to this commit, target platforms with older, pre-seccomp kernels would
hit a compilation failure when their compiler failed to find linux/seccomp.h.
This change makes CMake check for the required header during configuration and
present an earlier, more friendly error.
Resolves #1920 
----
I don't have a complete array of kernels on hand to test but on the machines I do, this check correctly errors on Linux 3.0 and passes on 3.17 and 4.4. Please let me know if you want anything changed to make it acceptable. Thanks.
=> Check for seccomp dependency during configuration

CMakeLists.txt, src/DumpCommand.cc, src/kernel_abi.cc, src/kernel_abi.h, src/kernel_supplement.h, src/record_syscall.cc, src/syscalls.py, src/test/flock_ofd.c, src/test/netfilter.c, src/test/ppoll.c, src/test/prctl.c, src/test/sigprocmask.c, src/test/tgkill.c, src/test/timer.c
As always, see commit messages for details. The first one `dump -t` is a small feature to filter dump entries by tid. The others are various bug fixes and missing syscall coverage I ran into recently. I probably have a few more of those coming, but wanted to get these in to avoid diverging too much from upstream. It's already a little large. If you want me to split up the PR, let me know.
=> Miscellaneous bugfixes/syscall coverage improvement + small new feature

src/RecordTask.cc, src/test/intr_pselect.c
After `pselect` returns, avoid restoring the sigmask if `sigmask=NULL`.
```
[FATAL /home/ted/Downloads/rr/rr/src/RecordTask.cc:1083:restore_sigmask() errno: SUCCESS] 
(task 16743 (rec:16743) at time 5157)
-> Assertion `has_previously_blocked_sigs' failed to hold. 
```
https://github.com/mozilla/rr/issues/1912
https://github.com/mozilla/rr/pull/1913
=> Handle sigmask=NULL in pselect

CMakeLists.txt, src/PsCommand.cc, src/RecordCommand.cc, src/RecordSession.cc, src/RecordTask.cc, src/RecordTask.h, src/Task.cc, src/TraceStream.cc, src/TraceTaskEvent.h, src/kernel_abi.h, src/record_syscall.cc, src/test/netfilter.c, src/test/nsutils.h, src/test/rr_ps_ns.c, src/test/rr_ps_ns.run, src/util.cc, src/util.h
The first commit is fairly straightforward, just a bit big due to reorganization in the test code. It records new threads' pids with respect to their own PID namespace in the trace stream and prints those during `rr ps`.
The second commit makes working with privileged executables easier. I played with a couple of variants, but in the end came up with this, which is fairly simple and seems to work quite nicely. See commit message for details.
=> Usability improvements for pid namespaces/setuid binaries

src/Task.cc
Kernels that have the DirtyCOW exploit mitigation patch (i.e. 4.9
and most stable kernels by now) will hang when trying to write to
a PROT_READ page that is backed by a transparent huge page and causes
a COW (which happens rather frequently for rr when it first sets up
a new address space). A kernel patch to fix this is pending at
http://marc.info/?l=linux-kernel&m=148359462917379&w=2, but until
then, we should avoid trying to pwrite to PROT_READ pages that may
be backed by transparent huge pages.
=> Work around kernel bug pwriting to PROT_READ thp

src/Task.cc
Not sure why the previous version worked when I first introduced it,
but with this version, I can see the string_instructions test pass
again on KNL. Fixes #1947.
=> Fix singlestep string instructions workaround for KNL

CMakeLists.txt, src/RecordSession.cc, src/Task.cc, src/test/checksum_sanity_noclone.run, src/test/sigreturn_checksum.run, src/util.cc, src/util.h
See first commit. 2048 bytes is not enough to hold the sigframe on KNL (or other microarchitectures with AVX512). 
Additionally, something I forgot to add to the last PR, which is checksum_sanity, but with cloning force-disabled, to make sure to cover the corner cases of both code paths.
=> Fix sigframe size for KNL

src/PerfCounters.cc
There isn't really a need for the useless counter, unless we deschedule our own counters. We only do so, if we have the IOC_PERIOD bug.
It so happens that this restores functionality on all kernel versions I have access to, but of course that may be a coincidence. Still, better than nothing.
=> Workaround #1957

src/test/async_kill_with_threads.c, src/test/async_kill_with_threads_main_running.c, src/test/async_kill_with_threads_thread_running.c, src/test/async_segv.c, src/test/async_signal_syscalls.c, src/test/async_usr1.c, src/test/util.sh
Some tracees need to set up signal handlers, etc. Fixes #1896
=> In async signal tests, wait for tracees to be ready

src/GdbServer.cc
'python-interactive' is for interactive shells. You need to put 'end' at
the end.
This was messing up a script I use that uses rr in an automated way. Let me know if there was a reason the gdbinit was this way and I can figure out something else.
=> Make rr gdbinit use 'python' correctly.

src/kernel_abi.cc, src/kernel_abi.h, src/kernel_supplement.h, src/record_syscall.cc
That would be:
- HCIGETDEVLIST (dumpcap enumerates bluetooth devices)
- HCIGETDEVINFO (not actually needed but i felt like recording hciconfig)
- SIOCBONDINFOQUERY (pretty much the same as SIOCETHTOOL)
- SIOCGSTAMPNS
- SIOCGSTAMP (not actually needed but it's the same as the one above)
Known issues:
- No tests. Could write them if needed. HCIGETDEVINFO is likely not testable without a real bluetooth device plugged in, but the rest are probably good enough.
- HCI\* structures don't use RR_VERIFY_TYPE. I think that's unavoidable given how they are not normally included in kernel headers.
- Having a real bluetooth device plugged in breaks the recording of dumpcap because it decides to do the rest of the sniffing, and I don't care about bluetooth _that_ much. I just wanted to record …
=> Some ioctls to get wireshark/dumpcap working

src/PerfCounters.cc
This is the CPUID returned by the new Xeon mobile processor.
Not all tests passes on this (most do) trying to get a list of failing tests now...
=> More Kabylake CPUID

src/test/nsutils.h
Thanks to @Keno . Supposedly this should fix most (all?) of the failing tests that I'm seeing.
Ref https://github.com/torvalds/linux/blob/99378fd26803328cbab64ae60fa98e1394d07a6d/include/linux/user_namespace.h#L123-L129
=> Do not fail test if USER_NS is disabled in the kernel.

src/test/privileged_net_ioctl.c
Some kernels do not support veth device creation. Admittedly, finding
one that supports user namespaces, but not veth devices is a little
rare, but they exist.
=> Skip privileged_net_ioctl test if unsupported

src/test/rrutil.h
Newer versions of glibc are deprecating the implicit sys/sysmacros.h
include via sys/types.h, so include it explicitly.
=> tests: include sys/sysmacros.h for minor/major funcs

src/GdbServer.cc
I'm building rr on Linux using Clang trunk from ~last week, and I'm getting this build warning (treated as an error):
````
rr/src/GdbServer.cc:1369:10: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
return move(dbg);
^
rr/rr/src/GdbServer.cc:1369:10: note: remove std::move call here
return move(dbg);
^~~~~   ~
````
Source link:
https://github.com/mozilla/rr/blob/2e4fd448052aec5592871c82e1de500a3925aaeb/src/GdbServer.cc#L1364-L1369
Turns out the "move" wrapper here is unnecessary (and somewhat problematic for optimizations, as noted in the warning).  Easy fix: just drop the "move", as the compiler suggests.  It's fine to return unique_ptr by value -- see the sample function "pass_through" on …
=> Drop unnecessary "move()" from await_connection()

CMakeLists.txt, src/AutoRemoteSyscalls.cc, src/AutoRemoteSyscalls.h, src/Task.h, src/test/string_instructions_async_signals_shared.c, src/test/string_instructions_async_signals_shared.run
But be careful not to restore it if the new wait_status is meaningful.
The call_exit tests will fail if we restore it unconditionally, because
the ptrace exit notification from the diversion session will be lost.
More generally, if a remote syscall were to trigger a signal or similar
we shouldn't squash that.
David Baron has a recording where a SCHED is being delivered to an ip
that contains a repeating string instruction (strlen). We fast forward
through the string instruction, but the remote syscalls triggered
by a kernel bug workaround (see #2005) clobber the expected SIGTRAP, and
when we continue searching for the context switch point rr asserts
because the tracee appears to be in an unexpected syscall (because its
wait_status is the remnant of a remote syscall).
Issue #2005 is going …
=> Save and restore Task::wait_status when performing a remote syscall.

src/GdbConnection.cc, src/GdbConnection.h, src/GdbServer.cc, src/GdbServer.h, src/ReplayCommand.cc
I am opening a pull request for the progress made in #1990. I still haven't gotten around to writing tests for this, but I will very soon :-) I am mostly creating this pull request to be able use CI for my fork. In the mean time, this option has received a couple of weeks of actual testing "in the field" from me and I am happy to report that it has been really useful so far. I will let you know when I commit the tests.
=> Add option for persisting the debug server after detaching

src/GdbConnection.cc
I was taking a look at my commits from some time ago and discovered this mistake.
We should bail if the connection is not alive anymore, not the other way around.
I am amazed that this typo did not break anything :-)
=> Fix typo in GdbConnection.cc

src/syscalls.py, src/test/numa.c
Follow up to #2030. Running this test alone (ie `./obj/bin/numa`) works just fine. Inside the test harness, however, it fails with the following error. I'm not sure what to make of it. Could some more experienced comment?
```
$  bash basic_test.run numa
./util.sh: line 236: 23261 Aborted                 (core dumped) _RR_TRACE_DIR="$workdir" test-monitor $TIMEOUT replay.err rr $GLOBAL_OPTIONS replay -a $replayflags > replay.out 2> replay.err
Test 'numa' FAILED: : error during replay:
--------------------------------------------------
process 23262 sent SIGURG
====== /proc/23262/status
Name:   rr
Umask:  0022
State:  S (sleeping)
Tgid:   23262
Ngid:   0
Pid:    23262
PPid:   23261
TracerPid:      0
Uid:    1000    1000    1000    1000
Gid:    100     100     100     100
FDSize: 64
Groups: …
```
=> [RFC] Test for get_mempolicy outparams

src/test/adjtimex.c
This fixes #2038. On my 64-bit Ubuntu machine, clang trunk (version 5.0.0 from svn revision 304217) spams a `-Wabsolute-value`  warning for an abs() call in adjtimex.c (getting the absolute value of the difference between two time_t values).  Clang suggests using labs() instead, since on that compiler/platform, this time_t subtraction produces a 'long' rather than an 'int'.  This pull request accepts that suggestion from clang.
=> Use labs() in adjtimex.c to avoid clang warning

src/AddressSpace.h, src/replay_syscall.cc, src/test/overflow_branch_counter.c, src/util.h
* `#include <functional>` explicitly for `std::function`
* Use correctly sized variable in assembly
* Suppress fallthrough warnings
=> Fix compilation error on GCC 7

CMakeLists.txt, src/test/check_environment_test.run
Without that all tests fail without clear indication what happened. I had to look at the source to find out what's going on.
=> Detect misconfigured environment as a first test

CMakeLists.txt
This is required when attempting to install an rr built with librr.so,
into a global prefix (executing from the build directory worked find
even without this change).
=> When building librr.so, tell CMake to set rpath on install

third-party/blake2/blake2b-load-sse41.h
When building for systems that define `HAVE_SSE41`, `blake2b-round.h` includes `blake2b-load-sse41.h`. That file did not exist in the rr source tree, so the build would fail.
This commit fixes that problem by copying `blake2b-load-sse41.h` from BLAKE2/BLAKE2@5cbb39c9ef8007f0b63723e3aea06cd0887e36ad, which is the same place the rest of the files in `third-party/blake2` came from.
=> Fix build for systems that HAVE_SSE41

src/PerfCounters.cc
`raw_fd` is 4bytes so the target register needs to be 4bytes too.
Triggered by https://github.com/mozilla/rr/commit/6b62b15f94ef975ea0f7efba95b2f7d4acc5a6fd#diff-af3b638bc2a3e6c650974192a53c7291L47 on GCC 7.1, not sure why. Maybe something got optimized out before?
=> Fix release build

src/test/seccomp.c
Starting with glibc 2.26, it uses SYS_openat to implement open.
This fixes a test failure on fedora 27.
=> Use syscall directly in test.

src/test/seccomp_sigsys_sigtrap.c
Starting with glibc 2.26, it uses SYS_openat to implement open.
This fixes a test failure on fedora 27.
=> Use syscall directly in another test.

src/test/util.py
It is not clear why, but we have to sleep before
BufferedRWPair.close() (which is called from gdb_rr.close). If we
don't, python freezes instead of exiting.
=> Sleep before gdb_rr.close.

src/GdbServer.cc, src/GdbServer.h, src/ReplayCommand.cc
This pull request adds support for remote debugging of  `rr replay` by allowing the user to specify a host address (via `-h` or `--dbghost`) for the gdbserver to listen on. Previously, this address was hardcoded to `127.0.0.1` (localhost).
Example usage:
```
rr replay --dbghost 0.0.0.0 /home/doom/.local/share/rr/LostKey-5
```
If the switch is not used, the host address defaults to localhost (as it exists now). 
I refrained from opting-in emergency debugging to this change as it didn't seem appropriate. It will only bind to localhost.
=> Remote replay debugging via user specified host address

CMakeLists.txt
The brotli library needs to be built with fPIC to be incorporatable into the rr library.
=> Fix RR_BUILD_SHARED build

configure
FreeBSD, for example, has no bash in the default installation,
and when it's installed, it resides in /usr/local/bin.
This is the first of a series of patches to port `rr` to FreeBSD.
=> [build] Use env to improve portability on other systems.

src/chaos-test/chaosutil.h, src/chaos-test/mmap_adjacent.c, src/chaos-test/mmap_bits.c
The former is the POSIX way of handling this.
cc: @rocallahan 
cc: @sfwhittaker
cc: @espindola
=> [chaos-test] Use sysconf(_SC_PAGE_SIZE) instead of PAGE_SIZE.

src/kernel_abi.h
__unused is reserved by compilers somehow (even though it's an
extension) so compiling this code with clang on FreeBSD results
in an error, i.e.
```
/home/davide/rr/src/kernel_abi.h:1046:27: error: expected member
name or ';' after declaration specifiers
unsigned_long __unused[4];
~~~~~~~~~~~~~         ^
```
Rename to avoid the clash.
=> [kernel-abi] Don't use a reserved keyword.

src/test-monitor/test-monitor.cc
On FreeBSD, this fails because the file uses std::string and
errno without including the correct header. On Linux, it happens
to work because those headers are transitively included by some
other header. Let's bee more explicit here.
=> [test-monitor] Include headers used explicitly.

src/ftrace/ftrace_helper.c
This removes an undefined behaviour and also suppresses a warning
on FreeBSD + clang.
cc: @rocallahan 
cc: @sfwhittaker
cc: @espindola
=> [ftrace] Make sure all paths to the exit of the functions return.

src/PerfCounters.cc
lscpu:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 71
Model name:            Intel(R) Core(TM) i5-5675C CPU @ 3.10GHz
Stepping:              1
CPU MHz:               3093.052
CPU max MHz:           3600.0000
CPU min MHz:           800.0000
BogoMIPS:              6186.10
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              4096K
L4 cache:              131072K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme …
```
=> Add support for CPU 0x40670 (Intel Core i5-5675C)

src/ReplayTimeline.cc
=> #2191 Set current_at_or_after_mark to non-nullptr value in ReplayTimeline::seek_before_key()

src/RecordCommand.cc, src/RecordSession.cc, src/RecordSession.h, src/TraceStream.cc, src/TraceStream.h
Sorry, I am really new to using git. I think I destroyed something in my repository of the git history.
I forked again, added the changes, and made one commit. Everything is the same. Sorry for the circumstances...
This commit adds the ability to set a trace-directory with `-o=<DIR>`
The `<DIR>` path is then the trace directory. The name of the directory can be choosen by the user and doesn't need to be `<application>-<x>`.
Latest Trace is not updated, because I think it's not a good way to add a latest-trace symlink to this "temporary" trace-dir.
Replay is only possible by given the path name.
I wanted to add this feature, to store traces in more than one directory, by not changing the environment variable `_RR_TRACE_DIR` every time. When the option is not set, every works as it worked …
=> add ability to set a temporary trace directory

CMakeLists.txt, src/record_syscall.cc, src/test/prctl_speculation_ctrl.c
Implementation is trivial, but the test for this is a bit tricky as it
depends on Linux kernel, CPU, firmware, etc.
recording LibreOffice on Fedora 28 we get:
[FATAL /home/roc/rr/rr/src/record_syscall.cc:4877:rec_process_syscall_arch()] 
(task 27472 (rec:27472) at time 23038)
-> Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'prctl' but got result -6 (errno ENXIO); unknown prctl(0x35)
=> support prctl PR_GET_SPECULATION_CTRL/PR_SET_SPECULATION_CTRL

src/PerfCounters.cc
A previous issue (https://github.com/mozilla/rr/issues/1642) discussed the lack of support for deterministic counters for CPUID 0x30670. 
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               55
Model name:          Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz
Stepping:            8
CPU MHz:             1533.173
CPU max MHz:         2582.3000
CPU min MHz:         499.8000
BogoMIPS:            4333.08
Virtualization:      VT-x
L1d cache:           24K
L1i cache:           32K
L2 cache:            1024K
NUMA node0 CPU(s):   0,1 …
```
=> Added support for CPU 0x30670 (Intel Silvermont)

CMakeLists.txt
This supports GNUInstallDirs and should offer a safe fallback for platforms its not available. This makes it easier to install rr to a system with the correct paths.
Also see this similar PR for cubeb which pointed me towards rr which has the same issue.
https://github.com/kinetiknz/cubeb/pull/455
=> cmake: Support GNUInstallDirs.

src/RecordCommand.cc, src/RecordSession.h, src/Scheduler.cc, src/Scheduler.h
Fixes issue #1738.
While it seems good for --chaos to randomize the number of cores, there are times when I would like to control the core count separately from scheduler randomization. This implementation allows passing --num-cores=N with or without --chaos, and will override chaos mode's setting if both are given (but scheduling will still be randomized, it will just use the given number of cores.)
It also slightly helps resolve the confusion that people have about rr reporting 1 core by default. Though I could have been more explicit about that in the usage message, I suppose. ("default is 1 core, or a random number from 1-8 if chaos mode is enabled"?)
=> Implement rr record --num-cores=N

CMakeLists.txt, src/assembly_templates.py, src/chaos-test/harness.py, src/syscalls.py, src/test/break_block.py, src/test/break_clock.py, src/test/break_clone.py, src/test/break_mmap_private.py, src/test/check_syscall_perf_interval.py, src/test/clone_interruption_finder.py, src/test/fxregs.py, src/test/get_thread_list.py, src/test/mprotect_step.py, src/test/reverse_step_threads_break.py, src/test/signal_numbers.py, src/test/step_thread.py, src/test/util.py
test: `pylint3 -rn -E $(find . -name "*.py")`
Should make the code compatible with both python2 and python3.
Add silent CMake rule to prefer python 3 over python2
mostly regexes:
```
sed -i 's/\<xrange\>/range/g' $(find . -name "*.py")
sed -i 's/\<iteritems\>/items/g' $(find . -name "*.py")
sed -i 's/\<iterkeys\>/keys/g' $(find . -name "*.py")
```
manually transformed print -> print() and import it from the future
(This should address issue: https://github.com/mozilla/rr/issues/2174)
=> python3 support

src/test/hooks.c
Explicitly specify ".text" before generating code, to avoid code being
placed in the non-executable data section.
=> fix hooks test

src/ReplayTimeline.cc
constraints.ticks_target == 0 means unlimited ticks, so do nothing in
that case.
(I was able to trigger this with the AMD Family 15h Model 30h code I'm working on; I'm not sure whether it's possible to trigger this on Intel CPUs.)
=> Don't make assumptions about the minimal step count

src/replay_syscall.cc
The old code would fail to coalesce mappings in some cases
(https://github.com/mozilla/rr/commit/8f5a8b5ed63d2389da81865c6f3c0931abb332f0#r30518535).
It would be really nice to have a test for this that fails with the old code (on non-Debian systems).
=> Split up mmaps that extend past the end of a file

src/LsCommand.cc
I've been running `./mach mochitest --debugger=rr ...` and I want to check on the traces that accumulate before the entire run is over. That mostly means running `rr ls` to see what's there, then `rr ps` on each trace to see if there's a -11 exit value.
But currently `rr ls` crashes out if it finds an in-progress trace.
=> Fix crash in `rr ls` when a trace is incomplete

CMakeLists.txt, scripts/rr_completion, src/main.cc
Add --list-commands option to rr which is the first part of the current --help display.
Use it to generate rr completion (calling rr help command, and parsing the output).
This should also address https://github.com/mozilla/rr/issues/2253
=> add bash completion script

src/PerfCounters.cc, src/PerfCounters.h, src/Task.cc, src/Task.h, src/VirtualPerfCounterMonitor.cc, src/record_signal.cc
* support using the difference of two PMCs as tick count
* support AMD family 15h model 30h CPUs that way.
I revisited the issue of running rr on my AMD bdver3 (family 15h, model 30h) laptop, which I unfortunately appear  to be stuck with for a while. I'm not sure whether it's due to a microcode update, but it appears that there are now two performance counters whose difference is predictable enough to run rr:
0xc4 (taken branches including exceptions, interrupts, far branches, and syscalls) and 0xc6 (exceptions, interrupts, far branches, and syscalls).
The difference, of course, is the count of taken near branches, conditional or not. I think that's good enough for us.
Most tests pass without a syscallbuf, and those that do not appear to fail for unrelated reasons.  I'm still looking at …
=> WIP: AMD Family 15h model 30h support

CMakeLists.txt
The `install()` command specified a path under `${CMAKE_CURRENT_BINARY_DIR}`, but that path is in the build directory, not the install directory.
Furthermore, the completion scripts in the completions/ directory must have the same name as the command they provide completions for. The script is therefore renamed to `rr` upon installation.
=> Fix the installation command for the bash completion script

CMakeLists.txt
The destination specified `share/` under `${CMAKE_INSTALL_DATADIR}`, which is usually `/usr/share`, giving `/usr/share/share`.
=> Fix the installation command for the bash completion script (take 2)

Vagrantfile
Now the cmake use hardcode python3 (See [cmake](https://github.com/Kitware/CMake/blob/9df49ba020ebfa15571ce818631bed6043368c8e/Utilities/Release/linux64_release.cmake#L35)) as ${PYTHON_EXECUTABLE}, which will throw the error `ImportError: No module named 'pexpect'`.
This PR set the system python as ${PYTHON_EXECUTABLE} to let cmake works.
=> vagrant: use system python in cmake

src/main.cc
The (undocumented and unused) --cpu-unbound definition in main.cc hides the (correct and intended) definition in RecordCommand.cc, with the result that this option doesn't work.  Removing the definition from main.cc fixes that issue.
=> Remove erroneous --cpu-unbound definition from main.cc

src/util.cc, src/util.h
Fixes #820.
The tests still use an inlined version of xmalloc from src/test/util.h, which is unaffected by this removal.
=> Remove xmalloc, which is no longer used.

src/AddressSpace.cc
I ran into this error when trying to use rr in our (somewhat-weird) environment, and spent a while tracking down the Linux error code and figuring out where rr was actually looking for the file.  I thought I'd add a better error message for the next person to run into the same issue -- which is probably going to be me again!
=> Provide better error when rr_page_* file isn't found.

src/kernel_supplement.h
The current version only happens to work because all users (by luck) already include stdint.h before including kernel_supplement.h.  However, precompiling the header alone will fail.
=> Add missing include to kernel_supplement.h.

src/log.cc
This additionally clarifies that the pointer value, not the string contents, is the map key.
=> Replace char* with void* in unordered_map keys.

src/test/util.sh
This allows relative OBJDIRs to work correctly even though we later cd into a working directory.
=> Always pass OBJDIR through realpath.

src/LsCommand.cc
Note: This is required per fine print in https://en.cppreference.com/w/cpp/algorithm/sort.
=> Const-qualify arguments on sort-compare functions.

src/RecordTask.cc, src/record_syscall.cc, src/replay_syscall.cc
This fixes all warnings I found with -Wimplicit-fallthrough.  It also cleans up a couple of meaningless "default: break;" clauses that I noticed because we implicitly fell through into one of them.
=> Add RR_FALLTHROUGH as appropriate.

src/TraceStream.h
The function `min`
https://github.com/mozilla/rr/blob/40cc1f47fd27922e01643cc042d5d8611d771851/src/replay_syscall.cc#L859
requires the types of two arguments are the same. But this contract is not always valid since `data.data_offset_bytes` has type `uint64_t`: e.g. on system where `size_t != uint64_t`, the contract is invalidated.
The PR changes the types of fields in `TraceStream`.
=> use size_t (instead of uint64_t) in TraceStream

src/kernel_supplement.h, src/record_syscall.cc, src/replay_syscall.cc
Linux 4.15+ adds support for persistent (non-volatile) memory devices (e.g. Intel Optane DIMM) by introducing two new flags to mmap(): MAP_SHARED_VALIDATE and MAP_SYNC.
This is implemented by defining MAP_SHARED_VALIDATE as MAP_SHARED | MAP_PRIVATE, which forcibly breaks legacy implementations, instead of silently ignoring unrecognized flags. Otherwise, it is equivalent to MAP_SHARED. 
MAP_SYNC is used to ensure consistency for persistent memory throughout the memory hierarchy, by requesting that the that the file be mapped without any intermediate caching (filesystem must be mounted in direct access / DAX mode), such that a cacheline flush + memory barrier is guaranteed to persist changes, even if the system crashes immediately afterwards. Because the trace recorder writes mapped regions …
=> support replaying traces that involve persistent memory

src/AddressSpace.cc, src/Flags.h, src/GdbConnection.cc, src/RecordCommand.cc, src/RecordSession.cc, src/main.cc, src/replay_syscall.cc, src/test/util.sh, src/util.cc, src/util.h
In some cases, we may need to override the default that expects these files to be located relative to the location of the mmap'ed rr executable.  This is particularly relevant when the executable is a symlink, as the symlink is effectively resolved before computing the relative paths, and this may not be the desired behavior.
=> Add --resource-path option.

src/test/util.h
With NDEBUG set, we get a host of undefined-variable and unused-variable warnings.
=> Add a check to make sure asserts work as expected in tests.

src/test/privileged_net_ioctl.c
This duplicates a definition in glibc's netinet/in.h, so we should only define it if we need to.
=> Avoid a macro-redefinition error.

src/PerfCounters.cc
This shouldn't be a behavior change in practice, but it avoids undefined-behavior-sanitizer warnings.
=> Avoid signed integer overflows in PerfCounters.cc.

src/LsCommand.cc
You're right about using all those Readers being big. Especially since they're completely unnecessary; they're only used in one place.
=> Use only one reader at a time

src/chaos-test/pipe_wakeup.c
`main` accepts either 0 or 2 parameters.
=> Fix clang -Wmain warning

src/TraceStream.h
TraceUuid is a struct, not a class -- but currently this header forward-declares it as a class.
In clang 9.0, that gives me a build warning when we get to the actual struct definition (treated as an error via -Werror): "RecordSession.h:49:1: error: 'TraceUuid' defined as a struct here but previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Werror,-Wmismatched-tags]"
Fixed here by correcting the mistaken forward declaration.
=> Fix forward decl of struct TraceUuid

src/ReplayCommand.cc, src/TraceStream.cc, src/TraceStream.h
I was looking at a replay hang, which is looking like it was just a very slow replay, and it was convenient to have a periodic dump showing the speed of the replay relative to the original recording.
You'll probably have a better idea for what to call things (monotonic time vs realtime vs record time), and I can also eliminate the zero-check on every step if you like (by displaying "nan%" for the first dump).
=> Add --stats=N option to replay -a

src/AutoRemoteSyscalls.cc, src/GdbConnection.cc, src/Monkeypatcher.cc, src/Task.cc, src/record_syscall.cc
Although variable-length arrays (VLAs) are standard C, they are not part of standard C++ and lead to warnings in strict compilation modes.  This patch replaces rr's use of them with heap-allocated arrays using std::unique_ptr, so that we get the same lifetime behavior and essentially the same runtime cost aside from the memory allocation.
=> Remove use of variable-length arrays.

src/AutoRemoteSyscalls.cc
I made a user error in testing, and failed to catch a code error.  This fixes it.
=> Fix an error in "Remove use of variable-length arrays" patch.

src/Event.cc, src/TraceStream.cc
There are a couple of functions in rr that return std::string values but have "return nullptr" in unreachable cases.  This now causes warnings with Clang at head, so this patch replaces them with returning an empty string.
=> Fix -Wnonnull warnings converting nullptr to std::string.

src/test/tgkill.c
Seems tgkill was added recently to glibc.
build/32/tgkill.c:7:12: error: static declaration of 'tgkill' follows non-static declaration
static int tgkill(int tgid, int tid, int sig) {
^
/usr/include/bits/signal_ext.h:29:12: note: previous declaration is here
extern int tgkill (__pid_t __tgid, __pid_t __tid, int __signal);
=> Fix build in newer glibc.

src/TraceStream.cc
This fixes the build with libc++ in C++17 mode.
=> Qualify uses of capnp::byte to avoid collisions with std::byte.

src/GdbConnection.cc, src/GdbConnection.h
- Do not use "multiprocess" thread id syntax, unless the client supports it.
- Support "c" packet, which LLDB prefers to use instead of "vCont;c".
=> Support LLDB as a client.

src/PerfCounters.cc
If this happens, the counter values are incorrect.
This happens when e.g. multiple rr instances run
in parallel on the same machine.
=> Detect when the kernel multiplexed hw counters.

src/PerfCounters.cc
It took me quite a bit to figure out what these special numbers mean.
I.e. these docs might be useful for any future reader.
=> Add docs about the perf event ids.

CMakeLists.txt, src/AddressSpace.cc, src/AddressSpace.h, src/GdbServer.cc, src/Monkeypatcher.cc, src/RecordCommand.cc, src/RecordSession.cc, src/RecordSession.h, src/audit/rtld-audit.c, src/audit/rtld-audit.h, src/audit/stap-note-iter.c, src/audit/stap-note-iter.h, src/preload/preload_interface.h, src/record_syscall.cc, src/replay_syscall.cc, src/syscalls.py
Sorry, this is kind of a big one. Some notes:
- I split this into two commits: one adding librraudit, and another actually implementing stap probe support. The auditing library may be useful in its own right for future work, so it seemed logical to break that out into a separate commit.
- The implementation of `AddressSpace::add_stap_semaphore_range` is kind of ugly. I do have a version that implemented the semaphore data structure as the minimal set of disjoint intervals, but the code ended up looking almost comically over-complicated given the objective it fulfilled.
- I'm not sure how you might want the test suite altered to exercise this. FWIW, I did run the suite with `--stap-sdt` and it passed with the exception of one test (which failed due to a watchpoint on mmap'd memory being …
=> Add support for breakpoints on SystemTap probes

src/test/block_clone_checkpoint.c, src/test/block_clone_interrupted.c, src/test/block_clone_syscallbuf_overflow.c, src/test/copy_file_range.c, src/test/direct.c, src/test/execve_loop.c, src/test/mmap_shared_write.c, src/test/mmap_shared_write_fork.c, src/test/pivot_root.c, src/test/sync_file_range.c, src/test/unshare.c
I have been working to package rr as a Fedora Project rpm.   When enabling the various compiler flags using by default for the Fedora Project builds I found some open calls that created files were missing the mode argument and there was a sprintf flagged for possible buffer overrun.  With the -Werror compiler option these would cause the build to fail.  The patches in this branch fix the code in the tests so -Werror can be enabled for the build.
=> Some minor fixes in the tests to allow compilation with -Werror turned on

CMakeLists.txt, src/record_syscall.cc, src/syscalls.py, src/test/sched_attr.c
This is used when spawing firefox with glibc trunk. Seems pretty
straight-forward to support.
=> syscalls: Add support for the sched_getattr syscall.

src/record_syscall.cc
Looking at the manpage, it suffers the same issue as the one
75a83e4ed59accdc590d2b9152ac6079eddbdb39 fixed for sched_getattr.
=> syscalls: Fix ParamSize of sched_getaffinity.

src/syscalls.py, src/test/sched_attr.c
Turns out I do need sched_setattr support, too... glib (not glibc, as I
initially though) calls it on thread startup.
=> syscalls: Handle sched_setattr.

src/EmuFs.cc
Fixes #2442. 
I'm able to compile rr on RHE7 machines now.
=> rewrite create_memfd_file to use syscall

CMakeLists.txt, src/Dwarf.h
These changes allow us to package rr for EPEL7 using its base compiler.
- The additional compilation options are added to avoid errors that arise from -D_FORTIFY_SOURCE=2 and -Werror (in the building of the RPM).
- The conditional implementation of `make_unique` was added as it's not available in C++11.
- _FORTIFY_SOURCE was disabled in the `read_oversize.c` test as it triggers an error.
=> Enable rr to be built on older compilers

CMakeLists.txt, src/Task.cc, src/Task.h, src/record_syscall.cc, src/test/invalid_exec.c
Prior to this patch, passing invalid (as in faulting) addresses as
the path or argv to exec would cause rr to assert because it was
itself trying to read that memory and failing. Instead, we should
go ahead and simply abort processing of the exec on such a fault,
since we know the kernel will fail it with EFAULT as soon as it
gets the chance.
=> Handle invalid path/argv in exec

CMakeLists.txt, src/preload/preload_interface.h, src/record_syscall.cc, src/test/ignore_nested.c, src/test/ignore_nested.run, src/util.cc
As reported in #2451, if the RR_UNDER_RR environment variable does
not get passed down to the nested rr, said rr ignores the
`--ignore-nested` flags, because it assumes (wrongly) that it is
the top-level rr. To fix this, instead of relying on the environment
variable add another custom fake syscall (like the existing rrcalls
used by the preload library) that the inner rr can use to detect
whether or not it's being recorded.
Fixes #2451
=> Better detection for running under rr

src/test/breakpoint.c
On one of our machines this test is failing. Upon investigation,
the reason for this is that the breakpoint for a function is
considered by gdb to be on the line of the opening brace, while
the test driver for this test assumes that the breakpoint for the
function is on the line of the first statement. This is likely
a change in the debug information emitted by the compiler on this
machine (gcc (Ubuntu 9.2.1-31ubuntu1) 9.2.1 20200304), but may also
be a change in GDB (GNU gdb (Ubuntu 9.0.50.20191119-0ubuntu1) 9.0.50.20191119-git).
In either case, it's easy to paper over the difference by making sure
that the opening brace and the first statement are on the same line
(even if it looks a bit ugly).
=> Fix step1 test on newer gcc/gdb versions

src/preload/overrides.c, src/test/chown.c
This fixes two issues I saw locally in the `chown` test
1. My user has more than 32 supplemental groups, so the hardcoded maximum of 32
groups in the chown test caused a failure. Instead, get this limit from sysconf.
2. My euid is larger than 16 bits, but rr was hooking geteuid to use the SYS_geteuid
syscall, rather than the SYS_geteuid32 syscall, which returns the euid of
proper bitwidth.
With fixes for both of these the `chown` test passes again locally.
=> Fix chown test

src/test/string_instructions_multiwatch.c, src/test/string_instructions_multiwatch.py
Using the same gcc/gdb versions as in #2457, I see the
string_instructions_multiwatch test fail, because gdb fails to
properly print the location of the `src` variable in my_memmove.
The reason for this is that it has not yet executed the part
of the prologue that moves the src value from its ABI register into
the register assigned to it for the rest of the function as recorded
in DWARF. However, it didn't mark the instructions that do that as
part of the prologue either. To me, this is a compiler bug, but
given the poor state of DWARF emission in mainstream compilers,
I can't say I'm particularly surprised. This fixes the test by
having the test itself print out the location of the `buf` variable,
rather than relying on the DWARF to be accurate.
=> string_instructions_multiwatch: Work around buggy compiler DWARF

src/preload/overrides.c
As noted in #2459, the previous random_device hack doesn't work
anymore on newer libstdc++ versions. This instead modifies the
passed `token` string in place and points it at the random device
we want to use. This is approach isn't without problem either:
We're modifying a string that's annotated in the source as `const`.
I would expect it to be fairly rare for this to be a problem, but
it's certainly possible.
=> Try a more robust random_device hack

CMakeLists.txt, src/Session.cc, src/Task.cc, src/Task.h, src/test/early_error.c, src/test/early_error.run
The code that attempted to report errors during early
execution doens't quite work. The problem is that it
tries to read the error pipe of the child before the
child has fully exited, thus blocking on the closure
of the child's pipe. The solution here is quite simple:
Just kill the child on error. Coming up with a test is
a bit trickier since the early execution doesn't fail
very often. This uses a small seccomp filter to turn
the first prctl call into a SIGSYS. Without this patch
that would hang. With this patch, we properly get the
expected error message.
=> Properly report unexpected stops during early execution

src/GdbConnection.cc
The GdbRequest struct has padding so memcmp'ing
is undefined behavior. I see this assertion fail intermittently
when this function is triggered, only because of differences
in the padding. We could write a proper comparison function,
but since this is just an assertion that the task exists, it's probably
sufficient to assert that we're targeting the right task.
=> Adjust an assertion that invokes undefined behavior

src/TraceStream.cc
Without this patch, calling peek_frame while there
are pending raw recs clears the raw_recs field and
(if there are any such records) causing them to fail
to be applied. The failure is usually an extremely
subtle discrepancy between the record and replay :/
I'm embarassed to say how many hours finding this took
me. Anyway, it's not an issue on master, because
there's only one use of peek_frame, and the frame it
peeks tends to not have any raw recs, but let's fix
it anyway, for the future sanity of anybody who
might try peeking at frames while raw recs are
pending.
=> Restore raw recs field after peeking in peek_frame

CMakeLists.txt, src/replay_syscall.cc, src/test/vfork.c, src/test/vfork_break_parent.py, src/test/vfork_break_parent.run
Just treat it like any old clone(CLONE_VM) call.
Fixes #2475.
=> Fix accidental removal of breakpoints after vfork

src/Task.cc
When hacking on rr, I find it common to end up in a situation where
the tracee segfaults here, which causes the tracer to enter an infinite
loop of stashing the SIGSEGV signal and re-attempting the syscall only
to receive the same result. To prevent this particular failure mode,
strengthen the unexpected-signal assertion here to fail on
unexpected, deterministic signals (non-deterministic signals get stashed
as usual).
=> enter_syscall: Slightly strengthen an assertion

CMakeLists.txt, src/test/util.sh
Resolves #2449. 
This patch allows users to install the testsuite, and allows us to generate a separate rr-testsuite subpackage. The local installation and usage of the testsuite is shown below.
Assuming that the user is in the build directory and has built rr...
```
sudo make install 
cd /usr/local/lib64/rr/testsuite/obj
ctest -j8
```
`sudo make install` installs rr along with the testsuite. The testsuite contents are located under `/usr/local/lib64/rr/testsuite`, and the directories here follow a similar structure to the source and build directories.
```
/usr/local/lib64/rr/testsuite
│
├── obj
│   └── bin
└── rr
└── src
└── test
```
These directories contain the minimal amount of files needed to run the testsuite successfully.
One point worthwhile noting is that the patch allows users …
=> Add support for installable testsuite

src/AddressSpace.cc, src/AutoRemoteSyscalls.cc, src/AutoRemoteSyscalls.h, src/EmuFs.cc, src/RecordTask.cc, src/ReplayTask.cc, src/ScopedFd.h, src/Session.cc, src/Task.cc, src/kernel_abi.h, src/record_syscall.cc, src/test/protect_rr_fds.c, src/util.cc, src/util.h
Admittedly, this change is primarily motivated by a philisophical
objection to RR_RESERVED_ROOT_DIR_FD, rather than any great practical
need. It just seems to me that if the tracee went through all the
trouble of hiding the real root, then we shouldn't just give it an
easy way to get it back. Of course, I'm not suggesting that this
would be the only issue with running an external rr tracer on a
sanboxed process without compromising that sandbox's security
guarantees - I'm sure there's many others. However, this one's
a pretty obvious one, so I'd like to remove it if possible.
That said, there are a couple of minor practical benefits:
- It's more robust to weird setups (weird mount setups, tmp being
a symlink).
- It's more robust when recording programs that change uid
- As a result, we …
=> Get rid of RR_RESERVED_ROOT_DIR_FD

CMakeLists.txt
This is a followup to #2481 which addresses @Keno's review.
The new configuration uses the basename of the source directory instead of `rr`.
=> Fix pathing for testsuite

src/Monkeypatcher.cc, src/assembly_templates.py, src/preload/syscallbuf.c
1) Fix _dl_runtime_resolve patching when libc is compiled with IBT (as it is on modern Ubuntu)
2) Add syscall buffering for SYS_epoll_pwait
=> Two minor enhancements

src/Session.cc
Obviously replay tasks need to check against the real
thread group id, not the recorded thread group id.
Sorry about that.
=> Fix bug in killing all replay tasks

src/test/clock_time64.c
where the 64 bit time syscalls may not be available.
=> Fix clock_time64 test on older kernels

CMakeLists.txt, src/RecordSession.cc, src/RecordTask.cc, src/RecordTask.h, src/Scheduler.cc, src/Session.cc, src/Task.cc, src/Task.h, src/record_syscall.cc, src/test/fatal_sigsegv_thread.c
The order of events for coredumping signals is extremely confusing,
so I got it slightly wrong. This commit attempts to remidy that.
For my future reference, here are some breadcrumbs of how the
event ordering works for coredumping signals:
1) The thread that receives the coredumping signal will block (without
further event after the injection), until all other threads have passed
their exit events [1]
2) After passing their own exit events, all other threads will block until
the coredump is complete (equivalently until all threads have passed their
exit events). Note that in this state, these tasks are also ignoring SIGKILL.
3) Once the coredump is complete, each task may proceed. The first task to
its exit events, the other tasks to their zombie state.
Of course hidden zombie state …
=> Properly handle event ordering constraints for core dump signals

src/preload/syscallbuf.c
Found by inspection - all my machines are using btrfs as a home device,
so the test doesn't run. Perhaps someone with a machine where this
actually runs can add some sanity checks to the quotactl test that
would have caught us writing garbage here.
=> Fix syscallbuf for quotactl

src/Task.cc, src/ftrace/ftrace_helper.c, src/kernel_abi.h, src/kernel_supplement.h, src/preload/preload_interface.h, src/preload/syscallbuf.c, src/preload/syscallbuf.h, src/record_signal.cc, src/record_syscall.cc
Our system for building universal binaries (https://binarybuilder.org/),
has a bit of a quirky setup where it has very old glibc headers (to
maximize compatibility on old systems, but very new kernel headers).
This commit fixes the build in this environment. There's a few parts
to this:
1) Extra definitions for kernel_supplement.h that the headers don't have
2) Switch prlimit64 to use a raw syscall()
3) Switch the syscallbuf.c file to use linux headers rather than libc headers
The last of these is not strictly required, we could just provide the
missing definitions. However, since the syscallbuf is implementing the
linux ABI rather than the libc ABI, it seems proper that it should be
using the linux headers. That results in a few struct renamings (and
unfortunately, I had to copy in the …
=> Fix build with very old glibc headers

CMakeLists.txt
It would be great if rr could support applications compiled against other libc's, such as musl. Unfortunately, one immediate problem is that rr's preload library relies on certain glibc symbols that may not be otherwise available: `__pthread_mutex_lock`, `__pthread_mutex_trylock`, `__sysconf`, and `__sprintf_chk`. For now, fix the latter by disabling the `FORTIFY_SOURCE` macro which introduces it.
```
rr: Saving execution to trace directory `<snip>'.
Error relocating /usr/local/bin/../lib/rr/librrpreload.so: __sysconf: symbol not found
Error relocating /usr/local/bin/../lib/rr/librrpreload.so: __pthread_mutex_lock: symbol not found
Error relocating /usr/local/bin/../lib/rr/librrpreload.so: __pthread_mutex_trylock: symbol not found
```
=> disable FORTIFY_SOURCE in preload for better binary compatibility with other libc

CMakeLists.txt, src/RecordSession.cc, src/RecordSession.h, src/RecordTask.h, src/Task.cc, src/test/pid_ns_segv.c
The kernel changes the behavior of deterministic fatal signals
for container inits when a ptracer is attached. In regular course
container inits are protected from non-deterministic fatal signals,
but not from deterministic fatal signals. Three years ago, the kernel
was changed [1] such that if a ptracer is attached, container init
is also protected from deterministic fatal signals (since ptrace generated
SIGTRAPs go through the same code path). Unfortunately, this means
that a SEGV inside the container init, will not kill the container
init while we're attached. I don't see anyway to work around this.
The only thing I can come up with is to quickly detach and hope for
the best. I think that's mostly ok, since deterministic signals are
also coredumping, so they won't cause a cleartid …
=> Hack around unkillable container-inits

CMakeLists.txt, src/Monkeypatcher.cc, src/RecordTask.cc, src/Task.cc, src/Task.h, src/TraceStream.cc, src/TraceStream.h, src/record_signal.cc, src/record_syscall.cc, src/test/mmap_tmpfs.run, src/test/mount_ns_exec.c, src/test/mount_ns_exec2.c, src/test/util.h, src/util.cc, src/util.h
In a few places we were accessing paths we obtained from inside
a mount namespace and tried to use them as if they were valid
outside the mount namespace. This usually worked by accident,
since the files inside the mount namespace were either the
same (if not much mounting had happened yet), or didn't
exist in the host file system. However, it's not hard to
get into a situation where this isn't the case (see the included
test), which would cause an un-replayable recording. With
this patch we try harder to only ever access such tracee
files through the various /proc magic files that paper over
mount namespace differences.
=> Fix confusion between paths outside/inside mount ns

src/RecordSession.cc, src/test/clone_cleartid_coredump.c
The child tid does not get cleared for coredumping fatal sigs.
I had thought about this case, but neglected to add it to the
test, so I missed that I had failed to actually pass it through.
Fixes #2472
=> Fix argument to record_exit_event

src/ReplaySession.cc
In issue #2509, we saw a case where the ticks target was 98
ticks after the syscall. With 100 being the skid size, this
would cause us to program a ticks target two ticks before the
syscall and then skid into it. Since the syscall is synchronous,
there's no reason to program a ticks interrupt at all if it'll
be hit before the ticks target. Check for that case and avoid
setting the ticks interrupt.
Fixes #2509
=> Don't program a ticks target if it's after the syscall

src/Scheduler.h
For workloads that are single-active-thread'ed well-syscallbuffered,
I'm consistently seeing the overhead from timeslicing to be quite noticable.
That was the case in #2473, and I'm seeing the same behavior with another,
longer benchmark I'm currently looking at. Here's some results for that benchmark
together with another optimization ("`pwrite`") I'm looking at that increases the amount of
syscallbuffering in this trace (if there's frequent non-buffered syscalls, the timeslice
doesn't really matter). This 5x increase does quite well, cutting about 130s
(30% of baseline) off the record time, but even higher time slices perform even better.
That said, I don't think bumping this even further here is a good idea. I'm gonna look into
some changes to the Scheduler to see if we can avoid …
=> Bump default scheduler intervals 5x

src/RecordSession.cc, src/Session.cc, src/Session.h, src/Task.h, src/TraceStream.cc, src/TraceStream.h, src/test/util.sh, src/util.cc, src/util.h
When running lots of parallel rr instances, it's quite easy for
these to stomp on each other and try to bind to the same CPU.
If that happens, performance tanks for the two rr processes
running on the same CPU. This can be easily observed in the test
suite. On my machine, with an otherwise idle machine, the test suite
currently takes between 165 and 220s depending on how the schedule
happens to work out. With this patch, it takes consistently between
155 and 160s.
The way this works is by creating a lock file (by default in the
_RR_TRACE_DIR, but overwritable by environment variable), where each
process will lock the n-th byte if it has bound itself to the n-th
CPU. When choosing a random CPU, rr will try to acquire this lock
and if it fails try another CPU (until it has tried every CPU …
=> Add a mechanism for rr processes to coordinate CPU usage

src/RecordSession.cc, src/Scheduler.cc, src/Scheduler.h, src/Task.cc, src/Task.h, src/util.h
If there's only one thread that can currently make forward progress,
there's really no reason to try to schedule a time slice interrupt,
since the only thing we could possibly do is re-schedule it. Since
time slice interrupts can have noticable performance overhead for
well-syscallbuffered traces, it's worth trying to avoid this.
This commit does just that, by adding a "turbo mode" to the scheduler
where it runs just one task with unlimited ticks, but listens for
events from all tracees. As soon as the first event comes in,
it switches the tracee back into regular mode and continues on
as usual. This approach appears to work quite well, and gives
a runtime of 444s on the benchmark from #2512 (assuming one
additional optimization, which will be in a separate commit).
=> Add a fast path when only one thread is unblocked

CMakeLists.txt, src/FileMonitor.cc, src/FileMonitor.h, src/SysCpuMonitor.cc, src/SysCpuMonitor.h, src/Task.cc, src/Task.h, src/VirtualPerfCounterMonitor.cc, src/preload/preload_interface.h, src/record_syscall.cc, src/replay_syscall.cc, src/test/sys_cpu_online.c
Glibc uses this to implement sysconf(_SC_NPROCESSORS_ONLN). With this
commit, the tracee sees the results we want, even if the preload library
is not available, (e.g. because the tracee dropped the evnironment).
Also includes a minor bugfix where we weren't emulating the advancement
of the fd ptr during an emulated read (which, with this FileMonitor would
cause an infinite loop).
Fixes #2453
=> Emulate /sys/devices/system/cpu/online

src/RecordCommand.cc
While the Session will happily go pick a new CPU to
run on and bind itself to it, without this patch,
the compression threads all remain bound to the CPU
of the rr process that we just detached from, causing
performance degradation.
=> Reset cpu affinity after detach

src/AutoRemoteSyscalls.cc, src/PerfCounters.cc, src/Task.cc, src/record_syscall.cc, src/replay_syscall.cc
(by marking them CLOEXEC). Also make sure that the clone duping
respects cloexec flags that were present in the original task.
=> Make sure perf fds don't leak into detached clones

CMakeLists.txt, src/preload/syscallbuf.c, src/test/ulimit_low.c
We try to avoid using the low fds to avoid disrupting the tracee (e.g.
the tracee may want to reserve a portion of fd space for its exclusive
management and get confused if we put an fd there). However, if we can't
use a high fd (e.g. because of a ulimit), then this shouldn't be fatal,
since it's not a problem if the tracee doesn't indiscriminately close
file descriptors. We could probably do better in the future, but for
now, let's just close the immediate failure mode with low ulimits.
Part of #2521
=> Make failing to dup the desched fd non-fatal

CMakeLists.txt, src/FileMonitor.h, src/ProcStatMonitor.cc, src/ProcStatMonitor.h, src/SysCpuMonitor.cc, src/preload/preload_interface.h, src/record_syscall.cc, src/replay_syscall.cc, src/test/sysconf_onln.c, src/test/sysconf_onln.run
As I mentioned in #2453, it turns out glibc has a bug in its
parser for /sys/devices/system/cpu/online, so it'll occasionally
fall back to /proc/stat (whenever the chosen sets of cpus is
non-contiguous).
=> Also emulate /proc/stat

CMakeLists.txt, src/RecordSession.cc, src/RecordSession.h, src/Scheduler.cc, src/Session.cc, src/Task.cc, src/Task.h, src/test/futex_exit_race.c, src/test/futex_exit_race_sigsegv.c
When I originall wrote this code, I had somewhat optimistically
added an assertion that we would only see the race in the case
of external fatal signals, in the exepectation that we would
see stable exit events in time to record proper exit events.
However, if there is a large number of threads waiting to exit,
it's quite possible for the kernel to not deliver us those
notifications until we're already trying to kill the tasks.
In principle it's a simple matter to change the assertion.
However, I also noticed that in this case, we don't write
any exit task events, which I know can confuse external tooling,
so let's refactor this whole thing to have RecordSession have
it's own copy of the killing code (half of it was already
record specific anyway), and properly record exit events
for …
=> More thoroughly handle exit event race

src/Task.h
I am unable to build rr from source on 32-bit machines. It seems that it is caused by the inconsistency in the return type (`size_t` and `uint64_t`) of `rr::Task::write_ranges`.
```
/builddir/build/BUILD/rr-aea765894985bd3a516eb3f42390025f36f81baa/src/Task.cc:2507:8: error: no declaration matches 'size_t rr::Task::write_ranges(const std::vector<rr::FileMonitor::Range>&, void*, size_t)'
2507 | size_t Task::write_ranges(const vector<FileMonitor::Range>& ranges,
|        ^~~~
In file included from /builddir/build/BUILD/rr-aea765894985bd3a516eb3f42390025f36f81baa/src/Task.cc:3:
/builddir/build/BUILD/rr-aea765894985bd3a516eb3f42390025f36f81baa/src/Task.h:684:12: note: candidate is: 'uint64_t rr::Task::write_ranges(const std::vector<rr::FileMonitor::Range>&, void*, size_t)'
684 |   uint64_t …
```
=> Make return type consistent for write_ranges.

src/Task.cc, src/Task.h
Follow up to #2528.
> Should probably be uint64_t consistently (sorry about that), since 32-bit applications can still write 64-bit files and this refers to a file size.
@Keno suggested that the return type be consistently set as `uint64_t` instead of `size_t`.
=> Change return type of write_ranges to uint64_t.

CMakeLists.txt, src/Event.h, src/Monkeypatcher.cc, src/Monkeypatcher.h, src/RecordSession.cc, src/ReplaySession.cc, src/ReplaySession.h, src/TraceStream.cc, src/assembly_templates.py, src/kernel_abi.cc, src/kernel_abi.h, src/remote_code_ptr.h, src/rr_trace.capnp, src/test/vsyscall.c
[vsyscall] is a legacy mechanism on x86_64 used to accelerate three
specific syscalls (gettimeofday, time and getcpu) by giving them
well-defined user space entrypoints that code can jump to. This
mechanism was deprecated in 2011 due to functionality limitations
and security considerations of having code mapped at fixed, known
addresses. It was replaced by vdso and on subsequent kernels,
vsyscall started being emulated by intercepting page faults to
these addresses. From the rr perspective, vsyscalls look quite odd.
We get a seccomp trap, but no other kind of syscall trap. We also
can't change any registers or do much of anything else other
than decidign to skip the syscall. Most critically, since we don't
get syscall traps for these, PTRACE_SYSEMU does not stop for
them during replay. As …
=> Support vsyscall

CMakeLists.txt, src/preload/syscallbuf.c, src/test/seccomp_blocks_rr.c, src/test/seccomp_blocks_rr.run, src/test/util.sh
If an external syscall filter vetos unknown syscalls (in particular those
above 1000, used by rr), recording will currently silently proceed (but
without the syscallbuf enabled), but the recording will be broken and
will fail with the `!syscall_bp_vm` assertion during replay. This
happens because we don't see a seccomp trap for the init syscall during
recording (because it gets veto'd by the external seccomp filter),
but we do see the syscall during replay (because PTRACE_SYSEMU will
still stop there). Instead of creating the broken recording, give
an intelligible error message, so the user can explicitly opt into
`-n` (which is adjusted to no longer call the init syscall).
Long term, it might be more sensible to switch these private, internals
syscalls to use a different mechanism …
=> Give an intelligent error if rr is broken by an external seccomp filter

src/AddressSpace.cc, src/AddressSpace.h, src/Task.cc, src/Task.h
Otherwise the tracee may get confused about the state of syscalls
like brk().
=> In nested detach copy kernel memory map

CMakeLists.txt, src/record_syscall.cc, src/test/sigprocmask_evil.c
This was a bear of a bug to track down, but see the included
test case for a situation in which this happens. Essentially,
if we have an input parameter that intersects an output parameter
and the input parameter has a mutator, our attempt to undo those
mutations after the syscall is done, actually clobbers the syscall
output in the same memory region. This doesn't happen very often,
because those memory regions don't tend to overlap and even if
they do, we're often syscallbuffered, which is a bit more robust
to this. When it does happen though, the result can be quite
mysterious, causing long range, mysterious memory modifications
during record.
=> Don't restore mutated memory that intersects output ranges

src/GdbServer.cc, src/kernel_abi.h
The --serve-files option I recently added is very useful for
debugging traces from a different machine, where the original
file system may not be locally available for rr to read symbols
from (similarly if the local file system has been deleted or
the recording is from the inside of a container that the replayer
may not be able to see). However, for dynamic libraries opened
via symlink, we currently fail to serve them using this mechanism,
since we nowhere record the resolved symlink on the record side.
GDB however, is getting these paths from the ld rendezvous struct,
which does record the path that was open()'ed rather than the
resolved path. This patch is a slightly hacky way to still serve
those files: If we didn't find the correct path in our memory
image, we too look for the ld …
=> [GdbServer] Look for missing file in the ld rendezvous

CMakeLists.txt, src/AutoRemoteSyscalls.cc, src/AutoRemoteSyscalls.h, src/GdbServer.cc, src/RecordSession.cc, src/RecordTask.cc, src/RecordTask.h, src/ReplaySession.cc, src/ReplayTask.cc, src/ReplayTimeline.cc, src/ReplayTimeline.h, src/Session.cc, src/Task.cc, src/Task.h, src/ThreadGroup.cc, src/ThreadGroup.h, src/replay_syscall.cc, src/test/vfork_read_clone_stress.c, src/test/vfork_read_clone_stress.py, src/test/vfork_read_clone_stress.run
This fixes #2540 and two other issues I found using the test I wrote for that issue. Details are in the commit messages, but the gist is that we need to rid ourselves of the assumption that FdTable/AddressSpace/ThreadGroups are all the same task set. I originally had a fourth commit that I thought was required, but turns out I had just written a bad test. I'm including it here for posterity. We might need it in the future, but at least for the moment, the code generated by the compiler seems to not cause issues (whereas including it might increase trace size unnecessarily and potentially cause unforeseen problems of its own).
```
commit 2e8ce978619d58991b826cdcf5fafbb560c26401
Author: Keno Fischer <keno@juliacomputing.com>
Date:   Thu May 7 02:51:21 2020 -0400
Protect syscallbuf alt stack …
```
=> Fix various vfork issues

src/syscalls.py
These "generic" syscall numbers are in use by newer architectures
such as aarch64 (ref #1373). They are defined in the following file
in the linux kernel:
https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/unistd.h
=> Add generic syscall numbers to syscall table

src/syscalls.py
At least while I'm here, let me also fix that annoying python syntax
warning about `is` that happens during build.
=> Whoops, fix new syscalls.py logic

src/AddressSpace.cc, src/AddressSpace.h, src/GdbServer.cc, src/kernel_abi.cc, src/kernel_abi.h, src/remote_code_ptr.h
Currently everything is assuming that breakpoint instructions have
length one. This is not true on other architectures. Refactor everything
to remove this assumption.
=> Refactor bpkt insn logic to handle non-x86 breakpoints

src/AddressSpace.h, src/AutoRemoteSyscalls.cc, src/ReplaySession.cc, src/ReplayTask.cc, src/Task.cc, src/ftrace/ftrace_helper.c, src/preload/preload_interface.h, src/preload/syscallbuf.c, src/test/blacklist.c, src/test/block.c, src/test/eventfd.c, src/test/mmap_shared_dev_zero.c, src/test/mmap_shared_multiple.c, src/test/proc_fds.c, src/test/string_instructions_watch.c
This collects all the x86 assumptions I encountered while porting rr to aarch64
that are not part of the core rr logic. That said, I disabled a good number
of tests in my porting effort, so several of them certainly still have x86
assumptions or are x86 specific.
=> Clean up misc x86 assumptions

src/test/timer.c
It's possible for the SIGUSR1 timer and the SIGALRM timer to become pending
at the same time, right after we check  !caught_limit_sig but before we set
`caught_sig = 0;`. In this case the subsequent loop will become essentially infinite,
because the SIGUSR1 sighandler turns off the SIGALRM timer (or rather gives it
a huge period).
Fixes #2555
=> Fix race condition in timer test

src/AutoRemoteSyscalls.cc, src/AutoRemoteSyscalls.h, src/RecordTask.cc, src/Task.cc, src/TraceStream.cc
This happens on aarch64 for me on existing tests that test
races between coredumping signals/group exits and other system
calls. For some reason, the aarch64 kernel appears to take a
while to actually shoot down these other tasks. In particular
a clone could still go through, but then die when we try to
initialize it. I suspect the same could happen on x86 also
and of course there's always the chance of getting an external
SIGKILL, so we might as well be robust to it.
=> Improve robustness to process death during clone

src/Task.cc, src/test/ptrace.c
The second issue found by inspection, the first issue while banging my head against the wall wondering why the test is failing. I've also submitted patches to the ptrace man page as well as the intel architecture manual to correctly describe how the NT_X86_XSTATE actually works,
because it's ... uhm, quite something.
=> Fix two issues with the ptrace test

src/test/ptrace.c
This field has different sizes between user/kernel/hardware.
`-1` makes sure to get the correct value on both x86 and x86_64.
=> Fix value for ptrace test

CMakeLists.txt, src/AddressSpace.cc, src/AddressSpace.h, src/Monkeypatcher.cc, src/RecordCommand.cc, src/RecordSession.cc, src/RecordSession.h, src/record_syscall.cc, src/test/unmap_vdso.run, src/util.cc, src/util.h
This adds `--unmap-vdso` as a record flag, which will unmap
the vDSO from every task's address space after exec and clear
the corresponding entry from the auxv list.
The vDSO patching machinery is a fair bit of complexity. When
porting to new architectures, it can be useful to first try
without it. I suppose it may also be useful if there is ever
a kernel version that has a vDSO entrypoint the Monkeypatcher
doesn't know about.
I'm hoping this will be useful to the next person trying to port to
a new architectures (cc @vchuravy ;) ).
=> Add a record flag to unmap vDSO in new tasks

CMakeLists.txt, src/GdbConnection.cc, src/GdbServer.cc, src/RecordSession.cc, src/Registers.cc, src/Registers.h, src/ReplaySession.cc, src/RerunCommand.cc, src/Task.cc, src/ThreadDb.cc, src/TraceStream.cc, src/TraceStream.h, src/rr_trace.capnp, third-party/gdb/aarch64-core.xml, third-party/gdb/aarch64-fpu.xml, third-party/gdb/aarch64-pauth.xml
Add the GDB mappings and import the GDB .xml files so that the GdbServer will work as soon as we hook up register support. Also add a representation of aarch64 in the trace format.
=> Aarch64 GDB register mappings and trace format support

src/RecordTask.cc, src/Registers.h, src/ReplaySession.cc, src/Task.cc, src/record_syscall.cc
This one's a bit tricky, because the aarch64 syscall ABI differs from x86. Rather than overwriting the syscall number with the return value, instead the kernel overwrites arg1. It does store the value of arg1 at entry internally (for use in restart_syscall), but this is not exposed via ptrace. Also, the currently executing system call is a separate regset, rather than being part of the regular NT_PRSTATUS regset as it is on x86. It's not clear to me whether or not `original_syscall` should be part of `Registers` on aarch64 or not. If it is, `Task` needs to learn how to deal with multiple regsets being potentially independently dirty. The alternative would be to have a `Task::change_syscall` that is eager on aarch64 and modifies the Task's registers on x86. I have a commit that does that …
=> Add aarch64 registers definition

CMakeLists.txt, src/AddressSpace.cc, src/AddressSpace.h, src/RecordSession.cc, src/ReplaySession.cc, src/SeccompFilterRewriter.cc, src/Task.cc, src/Task.h, src/generate_rr_page.py, src/kernel_abi.cc, src/preload/preload_interface.h, src/record_syscall.cc, src/replay_syscall.cc
Also use `X86Arch::user_desc` throughout rather than relying on it being defined by system headers. This is the type of the thread area, which isn't used on aarch64. That said, there is little harm to still having the field in Task, we just need to make sure it compiles.
=> Add rr_page definitions for aarch64

src/ExtraRegisters.cc, src/ExtraRegisters.h, src/GdbRegister.h, src/Task.cc, src/TraceStream.cc, src/kernel_metadata.cc, src/kernel_metadata.h
For the moment, we use the NT_PRFPREG regset. Modern arm chips
have a few additional registers that are not part of this regset
(most notably pointer auth registers). Applications making use of
those features likely won't work here. That said, let's cross that
bridge when we get there. Having the fp/simd registers should get
us far enough for the moment.
=> Add basic ExtraRegisters support for aarch64

src/Registers.h, src/Task.cc, src/kernel_abi.h, src/kernel_metadata.cc, src/kernel_metadata.h, src/kernel_supplement.h, src/record_syscall.cc, src/replay_syscall.cc, src/util.h
ptrace is highly architecture specific. Different architectures support
different ptrace commands and even when they support the same ones, the
number assigned to the PTRACE_* constants can vary (at least for the
low-numbered commands, the numbering scheme was unified in newer kernels).
If they all had the same numbers across architectures (just with some
architectures missing), we could just put everything in kernel_supplement,
but since that's not the case, kernel_abi is probably the right place for
it. This requries a bit of re-organization, but is fairly mechanical.
While we're here, also take care of arch_prctl, but here, since this
syscall is x86_64 specific, we only need to make sure all values we
use are present in kernel_supplement.h
=> Move arch specific ptrace commands into kernel_abi

src/Registers.cc, src/Registers.h, src/RerunCommand.cc, src/Task.cc, src/ThreadDb.cc, src/generate_syscalls.py, src/kernel_abi.cc, src/kernel_abi.h, src/record_signal.cc, src/record_syscall.cc, src/replay_syscall.cc, src/test/legacy_ugid.c, src/test/util.h, src/util.cc
Most not particularly interesting. The one thing I thought was kinda interesting is that of the structs we verify, in kernel_abi.h, there's only one that did not match the layout in BaseArch (semid64_ds), so that's fixed also.
=> Miscellaneous aarch64 build fixes

src/test/thread_open_race.run
I'm seeing this intermittently fail (on x86). Looking at the trace, it made it through 832 iterations in the loop and I see good progress in the log, so I don't think it's stuck, rather I think it might just actually be taking a long time depending on how the scheduling works out and how busy the machine is. Let's see if bumping the timeout helps.
Example record.err from a failing test: https://gist.github.com/Keno/b09a63666efffeb82e8aaa01b1abcdcd
=> Bump timeout in thread_open_race

src/AddressSpace.cc, src/AutoRemoteSyscalls.cc, src/GdbServer.cc, src/Monkeypatcher.cc, src/PerfCounters.cc, src/RecordSession.cc, src/RecordTask.cc, src/Registers.cc, src/Registers.h, src/ReplaySession.cc, src/Task.cc, src/Task.h, src/TraceStream.cc, src/fast_forward.cc, src/generate_rr_page.py, src/record_signal.cc, src/remote_code_ptr.h, src/util.h
As discussed in #2564, aarch64 register definition is a bit tricky,
because the kernel does not give us a way to request orig_x0, so we
need to track it ourselves. This means splitting the register format
in the trace from just a default Arch::user_regs_struct to include
the extra orig_x0. Additionally, we need to make sure to copy x0 to
this field on every syscall entry.
=> Aarch64 task running and register logic

CMakeLists.txt
This test has a .py/.run, but was in the BASIC_TESTS list,
so those were ignored.
=> Move fxregs to correct test category

src/RecordSession.cc, src/ReplaySession.cc, src/Task.cc
There's legitimate reasons to use the increment_by_bkpt_insn_length
function. However, to check whether a breakpoint was reached, we need
to use the undo_executed_bkpt function instead, since the behavior is
arch specific.
=> Fix breakpoint reached checks

src/RecordSession.cc, src/RecordTask.cc, src/RecordTask.h, src/Scheduler.cc
Coredumping signals are extremely annoying. Every task in the
same address space, save for the one doing the coredumping
needs to reach its exit event before that task can proceed.
However, we must make sure not to accidentally continue a
task past its exit state, because otherwise it too will hang
until all other tasks have continued. Unfortunately, we don't
have a "ptrace-continue-unless-in-exit-state" command, so we
try to waitpid beforehand to make sure we're not in this
situation. That seems to work reasonably well on x86, but
for some reason not on aarch64, where I'm routinely observing
the waitpid not reporting hat the task has stopped, but
the subsequent ptrace continue, moving it right past the stop.
This change tries to make that race detection slightly less
necessary by not …
=> More robust exits from coredumping signals

src/kernel_abi.h, src/record_syscall.cc
On non-x86 systems, it appears the kernel will not set ENOSYS for
syscalls that started out negative, if a seccomp trap is incurred.
I would argue this is a bug since a passive ptracer will affect
program execution, but what can you do.
I've also emailed LKML about it to ask if this is really what was intended here: https://lkml.org/lkml/2020/5/22/1216.
=> Work around kernel quirk for invalid syscalls

src/RecordSession.cc, src/ReplaySession.cc
So this one I'm a little unsure about. @rocallahan I think your insight is required. The question here is when to apply the kernel's register modifications for a system call restart before signal delivery. I would have expected us to already need to do this for x86, but I didn't see the code for it. There's something here: https://github.com/mozilla/rr/blob/master/src/RecordSession.cc#L1523-L1534, but that's on the replay side and also only if there isn't a signal handler installed. What I'm doing in this PR seems to work, but I'm not sure it's the correct place to make this register modification.
=> Apply syscall restart register modifications during replay

src/FileMonitor.cc, src/Registers.h, src/record_syscall.cc, src/replay_syscall.cc
On x86, there is no difference between arg1 and orig_arg1, but on aarch64, the former gets overwritten by the syscall result, so we need to look at the orig_arg1 value we save. I had fixed a bunch of these when I introduced Register support, but missed a few. This accumulates all the ones I found during any of the basic tests (and in the vicinity by inspection).
=> Look at the correct arg1 in a few more places

src/RecordSession.cc, src/RecordTask.h
On aarch64, the x8 value for restart_syscall leaks into the
tracee, since it doesn't get overwritten by the syscall result.
As a result, we can't just copy the register state from the
original syscall entry. Also, for signal stops, the restart
errno was already overwritten by the original arg1, so we
need to make sure to save what the errno was (in the
EV_SYSCALL_INTERRUPTION event), so we can look at it when
the signal event arrives.
=> Properly track register modifications for restart_syscall

src/RecordSession.cc, src/RecordTask.cc, src/RecordTask.h, src/Registers.h, src/Task.cc, src/Task.h, src/record_syscall.cc, src/record_syscall.h, src/replay_syscall.cc
During a syscall stop, the kernel lies about x7 and ignores writes to
it. That's usually not a problem as long as we don't look at it. However,
it becomes a problem if we do any AutoRemoteSyscall'ing during the exit
processing. AutoRemoteSyscalls might leave us in either a singlestep
or a syscall exit trap. If the former, then trying to re-apply the
registers that it thought the task had before the AutoRemoteSyscall
will actually end up modifying the real x7 register (because we're
no longer in a syscall stop where the kernel would ignore such a
write).
There's also a few other corner cases (e.g. during restart where
similar tricks need to apply).
In general, we rely on x7 being accurate during syscall entry
(since we expect to enter using a seccomp trap), and then
just copy it to the …
=> Work around aarch64 x7 woes

src/AddressSpace.cc, src/AddressSpace.h, src/Registers.cc, src/Registers.h, src/ReplaySession.h, src/ReplayTimeline.cc, src/Task.cc, src/Task.h, src/fast_forward.cc, src/kernel_abi.h, src/test/watchpoint.c, src/test/watchpoint.py, src/util.h
There's a few notable differences (aarch64 watchpoints fire before applying instruction effects, you get the matched address, but not which one fired), but in general the capabilities provided are similar to x86, so the number of changes is reasonable.
=> Add watchpoint support for aarch64

src/ReturnAddressList.cc, src/ReturnAddressList.h
The memset from ff4802e (#2579) fails to build since remote_ptr is a non-trivial type:
```
In file included from /home/src/github.com/mozilla/rr/rr/src/ReplayTimeline.h:16,
from /home/src/github.com/mozilla/rr/rr/src/GdbConnection.h:17,
from /home/src/github.com/mozilla/rr/rr/src/GdbServer.h:11,
from /home/src/github.com/mozilla/rr/rr/src/CPUFeaturesCommand.cc:4:
/home/src/github.com/mozilla/rr/rr/src/ReturnAddressList.h: In constructor ‘rr::ReturnAddressList::ReturnAddressList()’:
/home/src/github.com/mozilla/rr/rr/src/ReturnAddressList.h:31:63: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘class rr::remote_ptr<void>’; use assignment or value-initialization instead [-Werror=class-memaccess]
31 |   ReturnAddressList() { memset(addresses, 0, …
```
=> Properly clear ReturnAddressList for aarch64

src/AddressSpace.cc, src/GdbConnection.cc, src/GdbConnection.h, src/GdbServer.cc, src/Task.cc, src/record_syscall.cc
This GDB protocol extension allows reporting hardware breakpoints
as a stop reason. Without it, we report hardware breakpoints as
watchpoints, but aarch64 GDB considers them separate (probably
because they're separate hardware registers on aarch64), so it
just ignores hardware breakpoints reported that way.
While we're at it, also add the appropriate ptrace emulation for
aarch64 hardware break/watchpoints.
=> Use GDB "hbreak+" extension

src/SourcesCommand.cc
Most binaries with debug info have a DW_AT_comp_dir which comes from
the build machine. If that directory doesn't exist, "rr sources" can't
list any of the source files for that library. This option allows the
user to manually specify the correct directory containing the source
code for the binary.
In my case there was no source package for a library used by a binary that I was recording. I had to clone the source repository and check out the correct tag to get the correct source files.
=> let the user specify substitute source paths for libraries

src/RecordCommand.cc
On each recording run, the symlink in the default trace directory is updated with the latest trace. However, this can cause a crash if the default trace directory is not already created before `rr record --output-trace-dir <target-dir>` is run, because this flag disables the creation of the default trace directory in favor of creating `<target-dir>`.
This change adds a check to only attempt to update the symlink if the `--output-trace-dir` option is not being used.
=> Don't update latest-trace symlink when using  --output-trace-dir

src/DumpCommand.cc
https://github.com/mozilla/rr/blob/a9024348faf0e1daff77640b03139cc6c4ed70e2/src/DumpCommand.cc#L174-L186
I am wondering about the use of variable `last_time` in the above code snippet. The variable itself is never updated (it always remains zero). 
Now a reasonable conclusion would be that we need to update its value at the end of the while loop. E.g. do
```c
last_time = time;
```
But this would not work for some traces. `time` can remain the same (and not increase) for some trace task events while going around this while loop (e.g. try `exec_from_other_thread` test dump). So if we make above change we will get a fatal error at line 180. 
What is the correct treatment here? Maybe use < instead of <= ?
```c
if (time < last_time) { 
FATAL() << "TraceTaskEvent times non-monotonic"; 
} 
```
=> Check for task event time monotonicity and update var `last_time` in loop

src/Task.cc
We should not need to cycle through all stopped tasks. The first one should be fine...
=> post_exec(): Don't need to cycle through all stopped tasks. The first one should be fine

src/AddressSpace.cc
Thanks for the fast response.
Your proposed change fixed the test at my test system.
Fixes 2633.
=> Leave AddressSpace::verify if Task already exited.

src/RecordSession.cc
Pointing users to relevant man pages here is IMHO good addition to just telling what to do (which might not work on all distributions, see #2638) and can help one understand what is actually needed for `rr` to run properly.
=> Mention man pages in the perf_event_paranoid error

CMakeLists.txt
This is a small fix to address the pathing of the `check_environment` test.
It should use the `source_dir` symlink that was created to add support for the installable testsuite.
=> Fix pathing for check_environment test.

CMakeLists.txt
This is a followup to #2641. 
We need to create the directory for the installable testsuite symlinks before creating the symlinks themselves. This is because `create_symlink` requires that the destination directory exists beforehand. Previously this was not an issue because the symlinks were created later on in the installation.
=> Create directory for installable testsuite's symlinks.

src/Session.cc
The constructor already does this.
=> Remove redundant on_create call.

CMakeLists.txt, src/FdTable.h, src/RecordTask.cc, src/RecordTask.h, src/Session.cc, src/Task.cc, src/Task.h, src/test/mmap_fd_reuse_checkpoint.c, src/test/mmap_fd_reuse_checkpoint.py, src/test/mmap_fd_reuse_checkpoint.run
As I understand it, this is not only about the fdtable sharing
relationships. Complete FdTables may have gotten lost if two threads
shared address spaces but not an FdTable (which AIUI can happen with
some exotic system calls, or with unshare() maybe?).
That's why I opted into eagerly cloning all fd tables during the fork
process, I don't know how we'd be able to preserve them properly
otherwise.
Fixes #2592
=> Preserve FdTables properly during a session fork.

src/test/vsyscall.c
They may be disabled by default or via the kernel command line.
=> Only run vsyscall test when vsyscalls are supported

src/test/vsyscall_reverse_next.run
For some reason, the 32-bits no-syscallbuf variant is slow.
=> Increase timeout on vsyscall_reverse_next

src/PerfCounters.cc, src/PerfCounters_aarch64.h, src/PerfCounters_x86.h
PMU_SKIP_INTEL_BUG_CHECK would previously skip check_for_bugs entirely,
although it'd be desirable to at least run check_working_counters and
probably check_for_ioc_period_bug.
This change removes PMU_SKIP_INTEL_BUG_CHECK entirely, always runs
check_for_bugs, and passes down the CPU microarchitecture down to
check_for_arch_bugs to let it decide on its own which tests to skip
based on the microarchitecture.
=> Always call check_for_bugs

scripts/zen_workaround.py
=> zen_workaround: skip non numbers in /dev/cpu

scripts/zen_workaround.py
/dev/cpu may exist without the msr module being loaded, so test for
/dev/cpu/0/msr instead.
Fixes #2673
=> zen_workaround: check for /dev/cpu/0/msr

src/RecordTask.cc, src/Task.cc
This is a minor cleanup that I thought was worth doing.
This also adds an assertion that should've been added in
685ffeae62ed588cc7eec36f1a61c9456d50d8b8.
=> Avoid some useless refcount churn when passing new tg/fds.

src/AddressSpace.cc, src/AddressSpace.h, src/DumpCommand.cc, src/FdTable.cc, src/FileMonitor.h, src/ProcMemMonitor.cc, src/ProcMemMonitor.h, src/ReplaySession.cc, src/ReplaySession.h, src/Task.cc, src/TraceStream.cc, src/TraceStream.h, src/generate_rr_page.py, src/preload/preload_interface.h, src/preload/syscallbuf.c, src/rr_trace.capnp, src/test/util.h
A number of our test cases are very jit heavy, which means the only
syscalls they do are brk/mmap (for allocation), rt_sigprocmask and
pwrite64 to /proc/pid/mem (when commiting newly emitted code. Of these,
brk, mmap and pwrite64 aren't buffered yet, but pwrite64 quite a bit
more common than brk/mmap. This PR improves the state of affairs by allowing
pwrites to /proc/<pid>/mem to be buffered. This is the `pwrite`
optimization I mentioned in #2512, but the high level overview is
that together with #2513, this cuts the total overhead for this
benchmark from around 60% to about 1%. Additionally, it cuts the total
trace size (after removing immutable binaries we already have) from a
few dozen megabytes to a few hundred kilobytes (since we no longer store
what was written in the trace).
The …
=> Syscall buffer pwrite calls to /proc/<pid>/mem

CMakeLists.txt
This adds a fair amount of link time (about a minute), but also
improves runtime performance by about 3%. Most users will be
running rr in debug mode anyway, since that's default,
but if you need performance (as we do in our deployed version of rr),
the extra link time is a low price to pay.
=> Turn on LTO for release build

src/Registers.cc, src/Registers.h, src/Task.cc
We were unconditionally setting the registers_dirty flag,
often resulting in unnecessary additional ptrace system calls
(e.g. we'd try to set the eflags on every syscall event, but
if the flags weren't touched that's usually a no-op). Track
whether modification actually happened and if so avoid marking
the registers as dirty, saving a system call. This is a backport
from our deployed branch of rr. I don't have the exact perf numbers
anymore, but I remember it being around a 15% end-to-end perf
improvement on one of our benchmarks.
=> Avoid extra ptrace call when registers aren't actually dirty

src/Task.cc, src/record_syscall.cc
Rather than the libc-specific spelling. This should have better
compatibility across libcs, as well as dealing with situations
where the kernel headers are recent, but the libc is not (which
is the case for our build environment). The opposite case (new
libc, old kernel headers), is significantly more rare, since the
glibc build generally pulls in the newest kernel headers and ships
them. I haven't yet seen such a configuration in practice. Also,
since we're emulating the Linux ABI, not the libc ABI, we using
the Linux spelling is probably correct in a technical sense (though
of course in practice, the values are identical).
=> Switch to linux spelling for NT_* regsets

src/kernel_supplement.h
Older kernel headers will be missing these.
=> add more MADV_* constants

src/EmuFs.cc, src/util.cc
I encountered a couple bugs when using rr on a deeply nested (i.e. long pathname) target. The failure I encountered was EmuFile::create() fatally exiting with the message "Failed to create shmem segment for _my long pathname_".
These changes fixed my issue, but I'm unsure how they could be effectively unit tested.
=> Fix bugs when passing long filenames to open_memory_file()

CMakeLists.txt
Without this PR/patch, my OOB experience with `rr` is as follows:
```bash
cmake ../ -G Ninja -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is Clang 10.0.0
-- The CXX compiler identification is Clang 10.0.0
-- The ASM compiler identification is Clang
-- Found assembler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile …
```
=> Help modern cmake versions deal with empty

src/util.cc
As `m` may change, update the `raw_map_line` variable, otherwise it will potentially refer to an older map.
=> iterate_checksums(): Update raw_map_line variable

src/test/util.py, src/test/x86/fxregs.py
gdb_9.2-1_amd64.deb
(rr) show architecture
The target architecture is set automatically (currently i386:x86-64)
gdb_10.1-1_amd64.deb
(rr) show architecture
The target architecture is set to "auto" (currently "i386:x86-64").
Related issue #2740
=> Improve compatibility to GDB 10.1

CMakeLists.txt, src/AddressSpace.cc, src/AddressSpace.h, src/GdbServer.cc, src/test/invalid_interpreter.c, src/test/invalid_interpreter.py, src/test/invalid_interpreter.run, src/util.cc, src/util.h
This aids compatibility with GDB 10.1.
Related issue #2740.
=> Save interpreter_base and ld_path at AddressSpace construction.

CMakeLists.txt, src/DiversionSession.cc, src/test/diversion_sigtrap.c, src/test/diversion_sigtrap.py, src/test/diversion_sigtrap.run
Changes DiversionSession to propagate a SIGTRAP received by the target
process to the client, as a signal, when it was not produced by a
debugger breakpoint, a singlestep operation or a watchpoint.
=> Propagate SIGTRAP to client during diversion

src/GdbConnection.cc
GDB transmits the length as a 16 byte hex
representation e.g. ffffffffffba6f76.
Unfortunately strtoul at i386 returns 0xffffffff
and silently ignores remaining bytes.
This leads rr to "Assertion `start_ <= end_' failed."
This seems to be because strtoul returns 'unsigned long' which
is at i386 a 32bit type but at x86_64 a 64bit type.
This patch uses strtoull which still gets casted into a 32 bit value,
but len then contains 0xffba6f76 instead of 0xffffffff.
<details><summary>Example GDB session at i386 showing the issue</summary>
<p>
```
benutzer@debian:/home/bernhard/data/entwicklung/2020/rr/2020-11-21/obj_i686$ bin/rr replay -o-n -x /home/bernhard/data/entwicklung/2020/rr/2020-11-21/rr/src/test/test_setup.gdb /tmp/rr-test-search-mrZWyYEwg/latest-trace
GNU gdb (Debian 10.1-1+b1) 10.1
... …
```
=> Use strtoull instead of strtoul to make search test succeed at i386.

CMakeLists.txt, src/preload/overrides.c, src/preload/syscallbuf.c, src/preload/syscallbuf.h, src/test/pthread_pi_mutex.c
When `PTHREAD_PRIO_INHERIT` is set, `pthread_mutex_init()` from glibc performs a test `futex()` call to probe for OS support.  This fails with RR.  Workaround by forcing `PTHREAD_PRIO_NONE`.
Attempts to address #2750
=> Override pthread_mutex_init() to force PTHREAD_PRIO_NONE

CMakeLists.txt
These were superseded by librrpage.so.
@yuyichao see if this fixes your build issue.
=> rm leftover rr_page install rules

src/preload/rr_page.ld
Apparently the binutils on Ubuntu 18.04 has a very large value of
MAXPAGESIZE. Just hardcode a 4k page instead. This might break on
aarch64, but we're not using the syscallbuf there yet anyway, so
let's revisit that when we get there.
@khuey See if this fixes things for you. Seems to work locally with 18.04.
=> Explicitly set offsets in rr_page linker script

CMakeLists.txt, src/AddressSpace.cc, src/preload/preload_interface.h, src/test/unwind_rr_page.cc
Hello, tried to run the tests on plain i386 and found most tests did fail.
With the libname in map_rr_page fixed just two tests were then failing,
therefore I wondered if the tests do not run at amd64 as _32 and tried
to change this.
Please note that the change to is_rr_page_lib got not triggered
by any issue, just finding me there just one of the libname.
The test record_replay still fails by hanging infinitely at i386,
but not sure if this is related to rrpage or not.
cc: @Keno
=> 32bit fixes related to 3aaf7920e11

src/RecordCommand.cc, src/record_syscall.cc, src/test/detach_state.c
Previously we did this manually in the child rr process, but if we
want to detach things that are not rr, don't make them repeat it.
=> Reset CPU affinity state after detaching from rr

src/preload/rr_page.S, src/preload/syscallbuf.c, src/test/detach_state.c, src/test/get_thread_list.py, src/test/step_thread.py
After detaching, librrpreload is still in LD_PRELOAD. However,
librrpreload does not like being loaded when rr is not listening
and will crash attempting to execute a system call from the rr
page. Of course it is possible to sanitize LD_PRELOAD, but that
seems a bit heavy handed to require every possible user of detach
to do. Instead, this makes librrpreload a bit more careful about
checking for the presence of rr. In the happy path, where the
load address of librrpage matches RR_PAGE_START, this only
introduces an extra pointer comparison to avoid jumping to
an unmapped address. Otherwise, we fall back to a syscall to
determine if the rr page was mapped. Of course, there is still
the case where librrpage was accidentally mapped at the correct
address, but rr isn't actually listening. To …
=> Make librrpreload lib harmless after detach

src/Task.cc, src/kernel_supplement.h
As mentioned in previous PRs, the julia production build system uses
ancient libc headers to ensure ABI compatibility with the oldest
supported linux versions. Said headers have a different type for
the RLIMIT_* flangs and don't have the libc wrapper for `prlimit`.
=> Fix build with ancient glibc versions

scripts/zen_workaround.service
For users that want to ensure that `zen_workaround.py` is run on startup, this script will automatically do so, downloading the `zen_workaround.py` script if it does not already exist.  Users are encouraged to modify the script to their needs, but the default configuration should provide a good experience for most use cases.
=> Add systemd service to automatically run `zen_workaround.py`

src/Task.cc, src/kernel_supplement.h, src/record_syscall.cc
@staticfloat and I spent a bunch of time last week trying to get rr running in our CI environment (again - it's been a long battle), and found a few minor issues in the detach code. One embarrassing typo I made in a prior commit, one kernel issue (https://lkml.org/lkml/2020/12/16/936) for which this at least gives an error message now and one workaround for old libcs. Details in the individual commits.
=> Assorted fixes for detach code

src/Task.cc, src/test/detach_state.c
Any updates that were made to the page will already be visible,
so there's no need to copy. Of course, applications that use
MAP_SHARED are quite likely to break anyway, but we might
as well let it continue here. There are some libraries that
like to map global caches MAP_SHARED, even if they generally
aren't written without manual update, which is usually fine.
=> In detach, don't try to copy MAP_SHARED pages

src/Task.cc
I found some detach tests started to fail since c512416f2.
At i386 struct rlimit is just 8 bytes while struct rlimit64 is 16 bytes, while at x86_64 both are the same size.
Therefore memory followed by the variable limit got overwritten causing a crash later.
```
(gdb) print sizeof(limit)
$3 = 8
(gdb) x/32xb &limit
0xbfffd4dc:     0x68    0xbe    0x76    0x00    0x14    0xd5    0xff    0xbf
0xbfffd4e4:     0x78    0xd3    0xff    0xbf    0x6e    0x1e    0xca    0xb7
0xbfffd4ec:     0xe0    0x58    0xb0    0x00    0xe2    0x58    0xb0    0x00
0xbfffd4f4:     0xe2    0x58    0xb0    0x00    0x70    0x1e    0xca    0xb7
(gdb) next
3599            (uintptr_t)all_rlimits[i], (uintptr_t)NULL, (uintptr_t)&limit);
1: &(((rr::AutoRestoreMem * const) 0xbfffd4e4).remote)
= (rr::AutoRemoteSyscalls *) …
```
=> Fix struct size for copying rlimits at i386.

src/RecordCommand.cc
On our CI, we are seeing recording rr tracers segfault
every couple of days (which isn't terrible we run probably
around 40 rr processes continuously 24/7). We are also
using the detach feature quite heavily, so this could
be related to #2777. However, at the moment when rr
crashes, it doesn't print any useful information
whatsoever. To help diagnose, this PR makes it at
least print a backtrace on SIGSEGV, which I think
would be generally useful. If that doesn't work,
we'll have to move on to rr-recording our rr-recordings ;).
=> Install a SEGV handler that prints a stacktrace

CMakeLists.txt, src/preload/syscall_hook.S, src/test/morestack_unwind.c, src/test/morestack_unwind.py, src/test/morestack_unwind.run
GDB has a heuristic [1] that overrides unwind info if
the current instruction is a literal `retq`. Unfortunately
this interferes with our __morestack hack because it changes
the CFA, which in response to a `fin` command, causes GDB
to believe that it did not in fact manage to step out of
the frame, but rather ended up stepping into the same function
again. This causes #2682. To work around this, we could set
the producer to "GCC 4.5" or greater, which disables the
heuristic. However, creating this information in assembly
is quite tedious because there is no native support for it,
so it would have to be entered using raw directives. Instead,
simply put a `nop` at the return of the `_syscall_hook_trampoline`.
This prevents the heuristic from kicking in, so GDB doesn't miss
the frame. GDB …
=> Work around a bad GDB heuristic in unwind

src/AddressSpace.cc, src/AddressSpace.h, src/ReplaySession.cc, src/Session.cc, src/Task.cc, src/kernel_abi.cc, src/kernel_abi.h, src/record_syscall.cc, src/test/prctl.c
This helps tests detach_state, nested_detach and nested_detach_wait
to succeed with a 32-bit rr running under a 64-bit kernel.
This iteration of the series has moved the structure definition to kernel_abi.h and replaced all uses of sys/prctl.h's definition like @khuey asked for.
Also I hope this should make my use of fflush in the commit message in the last iteration more clear.
Is it known what this fflush changes to make the prctl not to fail with EPERM?
=> WIP: Add support to run tests with 32-bit rr below 64-bit kernel (prctl_mm_map)

CMakeLists.txt, src/AddressSpace.cc, src/AddressSpace.h, src/GdbServer.cc, src/Monkeypatcher.cc, src/Monkeypatcher.h, src/ProcMemMonitor.cc, src/RRPageMonitor.h, src/RecordSession.cc, src/ReplaySession.h, src/TraceStream.cc, src/TraceStream.h, src/assembly_templates.py, src/kernel_abi.h, src/preload/rr_page.S, src/preload/rr_page.ld, src/preload/rr_vdso.S, src/preload/syscallbuf.c, src/preload/tweak_librrpage.py, src/record_syscall.cc, src/replay_syscall.cc, src/rr_trace.capnp, src/test/mmap_replace_most_mappings.c, src/test/ptrace_remote_unmap.c, src/util.cc, src/util.h
We were running into another #2721 like situation, except this time
due the vdso patch (for which we deliberately destroy the unwind info
to avoid confusing the unwinder - unfortunately, we'd not only like it
to not be confused, we'd also like it to work). To solve this, I
propose to stop patching the vdso alltogether and instead implement
a VDSO-compatible ABI in librrpage that can then a-priori do
whatever we need it to while simultaneously having correct unwind
information. As a bonus, this also lets us rip out the heuristic for
mapping librrpage, since the dynamic linker is happy to take what
it thinks of as the VDSO as a pre-relocated object in memory.
This seems to work fairly well and results in a bunch of nice simplification
of the Monkeypatcher code. There are two test failures …
=> RFC: Pretend to the tracee that librrpage is the vdso

src/AutoRemoteSyscalls.cc, src/AutoRemoteSyscalls.h
This is an attempt to fix the issue reported in JuliaLang/julia#39145.
Essentially, the gist is as follows: During execve, we try to unmap
some buffers in the parent address space by picking an arbitrary
stopped task in the parent address space and comandeering it to
do the unmapping for us. Usually this is not a problem, because
this task will likely sit at a syscall exit event or signal event,
both of which AutoRemoteSyscalls supports fine. However, in rare
circumstances, it is possible for us to instead be sitting at a
PTRACE_EVENT_SECCOMP. The sequence of events that leads to this
is approximately as follows:
1. We resume using RESUME_SYSCALL (by itself fairly unusual if
the seccomp filter is running, since we usually prefer to save the
extra trap and go straight to the EVENT_SECCOMP …
=> Handle being at PTRACE_EVENT_SECCOMP in AutoRemoteSyscalls

src/Task.cc, src/test/64bit_child.c, src/test/simple_script.run, src/test/simple_script_debug.run, src/test/util.sh, src/test/vdso_clock_gettime_stack.run, src/test/vdso_gettimeofday_stack.run, src/test/vdso_time_stack.run, src/test/vsyscall_singlestep.run
This is mostly done by detecting bitness or the name of librrpage.so.
Can we take a `which` and `file` in the environment as given?
In 64bit_child.c the following comment makes me wonder if it is still true:
```cpp
/* Fork-and-exec 'echo'.
The exec may fail if 'bash' is 64-bit and rr doesn't support
64-bit processes. That's fine; the test should still pass. We're
testing that rr doesn't abort.
*/
```
In my tests a 32-bit rr with a 64-bit shell under a 64-bit kernel, if not skipped, does abort like this:
```
$ bin/rr record bin/64bit_child
rr: Saving execution to trace directory `/home/bernhard/.local/share/rr/64bit_child-0'.
rr: /home/bernhard/data/entwicklung/2020/rr/2021-01-03/rr/src/Registers.cc:550: void rr::Registers::set_from_ptrace(const rr::X86Arch::user_regs_struct&): Assertion …
```
=> Skip some tests if run with 32-bit rr under a 64-bit kernel

src/CompressedWriter.cc, src/kernel_metadata.cc, src/kernel_metadata.h, src/util.cc, src/util.h
On older libcs, we're observing about a 0.1% crash (SIGSEGV) rate
when starting an rr process under load. With #2780, the printed
stack trace reveals that the crash is in pthread_join.
My suspicion is that the pthread_create failed and never actually
created the thread that pthread_join then tries and fails to
join. I am not sure why newer libcs would not show the same
behavior but maybe glibc gained some sort of internal retry.
=> Retry pthread_create on failure

CMakeLists.txt, src/Monkeypatcher.cc, src/Monkeypatcher.h, src/assembly_templates.py, src/record_syscall.cc, src/test/detach_threads.c
When detaching we leave the preload library in the former tracee.
We do lock the syscallbuf, so the tracee shouldn't really make use
of it, but I neglected to consider that the tracee might launch
additional threads, which, if they used a previously patched syscall,
would then share the syscallbuf stack. I considered simply setting
the stack nesting level to 1, which would force the syscallbuf
back onto the original stack, but this doesn't work because we
still use the preload thread locals for thread space and only
one thread may use these at a time. Additionally, it the tracee
may not expect to have its stack used in this way, which is why
we're switching stacks in the first place. This instead tries to
prevent the tracee from using the preload library entirely by
unpatching the …
=> Detach: Unpatch syscalls before detaching

CMakeLists.txt, src/RecordCommand.cc, src/RecordSession.cc, src/RecordSession.h, src/test/nested_detach_kill.run
Generally, when the main task being recorded exits, we proceed to
kill all other tasks. However, if the task was detached, we
intentionally keep it running such that e.g. detached rr recordings
can continue recording (just as such processes would keep running
if the main task exited without rr). However, I don't think this
policy necessarily makes sense when the user sends SIGTERM to rr,
since that is an explicit request to gracefully shut down the
recording. In this situation, I do think it makes sense to propagate
this SIGTERM to any detached tasks, so that any `--nested=detach`
recordings also gracefully exit (and moreover such that all recording
is complete by the time a SIGTERM'd rr exits). If this seems too
agressive as a default behavior, I can do it in our CI scripts instead,
but …
=> Propagate SIGTERM to detached tasks

src/test/record_replay.run
Running test record_replay takes more than the default 120 seconds
inside a VM at an i5-4210U, even when not running tests in parallel.
Related to #2765
To demonstrate I added some `echo $(date) before ...` statements to the test and got these times.
So the just_record is kind of tight at the default 120 seconds timeout.
This run was non-parallel and without any other load on that machine, except htop.
```
1176: Test command: /bin/bash "source_dir/src/test/record_replay.run" "record_replay" "" "bin_dir" "120"
1176: Test timeout computed to be: 1000
1176: Fri Jan 15 14:02:39 CET 2021 before record record_replay_subject$bitness
1176: Fri Jan 15 14:02:41 CET 2021 before just_record rr "--suppress-environment-warnings replay -a $workdir/*-0"
1176: Fri Jan 15 14:04:40 CET 2021 before replay …
```
=> Increase timeout for record_replay test.

src/log.cc
We've been turning on RR_LOG_BUFFER by default for our deployed
version of rr in the hopes of catching rare transient rr issues.
However, people have been complaining that rr then dumps the entire
log, even on completed exits. I didn't see this locally, so I was
quite confused, but after some debugging it turns out that the
`atexit` here may or may not actually work, depending on compiler,
linker and C++ standard library versions. The reason is the
sequencing with the destructor of the global log_buffer unique_ptr.
While C++ does guarantee that calls to atexit are properly sequenced
with respect to static initializers, it turns that we are calling
`init_log_globals` at static init time also, so the sequence of
the log_buffer destructor and calls to `atexit` here is undefined.
I'm …
=> Remove bad `atexit` call

src/GdbServer.cc
This might be related to commit c979313cf0.
The crash happens just when attempting to execute the
printed emergency gdb command line.
It crashes because when recording the method
timeline.current_session() returns a null reference on
which the trace_reader() method is called when initializing
the tmp_reader variable.
----
Below the attempt to attach another gdb to the rr process before the emergency gdb command is executed.
```
5.4.0-97-ga8043d16
$ /home/bernhard/data/entwicklung/2021/rr/2021-02-01/x86_64/obj/bin/rr record smb4k
rr: Saving execution to trace directory `/home/bernhard/.local/share/rr/smb4k-1'.
[FATAL /home/bernhard/data/entwicklung/2021/rr/2021-02-01/rr/src/record_syscall.cc:5811:rec_process_syscall_arch()] 
(task 93232 (rec:93232) at time 10054)
-> Assertion …
```
=> Avoid crash when recording and emergency gdb attaches.

CMakeLists.txt, src/preload/overrides.c, src/test/pthread_mutex_timedlock.c
Currently pthread_mutex_timedlock seems to always crash when recording is done in no-syscallbuf,
because `real_pthread_mutex_timedlock` never gets assigned the real function and still contains a null pointer.
The contained change just tries to do the dlsym call just before, if not yet set.
Would that be a good enough solution?
=> Avoid crash in pthread_mutex_timedlock in nosyscallbuf mode.

src/RecordSession.cc
Qt used RDRAND for the macro name but value "rdrnd":
https://github.com/qt/qtbase/commit/0829baf902dbf5982732aa54454178f55b50bdc6#diff-4828ff220a163bad0e8f0c93ecd62de669caf5feb902c436246b328a0d0fbb41R232
https://github.com/qt/qtbase/commit/cf63b0e1dfc0bf3d11a92c5bf82840ddb6bb22ac#diff-490557b780a00c7df3fbed1f2d0e2e0895360969c68e9339b6b15b85bbbedff9R36
https://github.com/qt/qtbase/commit/cf63b0e1dfc0bf3d11a92c5bf82840ddb6bb22ac#diff-d1e14cfc882ae33f370a125f43cbccc681f0e6bd68820213a5d5831e973ba84fR13
The rr issue https://github.com/rr-debugger/rr/issues/2214 that introduced the QT_NO_CPU_FEATURE line back then
seems got fixed by rdseed or rtm instead rdrand, therefore got unnoticed until today.
Related to #2804
With this applied I notice no issues any longer with my minimal Qt helloworld or …
=> Qt uses rdrnd instead of rdrand in cpu feature exclusion list.

src/preload/rr_page.ld
@sefeng reported an issue where this was dislocating .vdso.text with a .note.gnu.property section with gcc 10.2 and ld 2.36.
This fixes his immediate problem, but this is still not robust to other .note sections (or perhaps even other types of sections). Any thoughts @rocallahan @Keno
=> Shove any .note.gnu.property sections up into the header along with the other notes

src/test/memfd_create_shared_huge.c
Minor improvement to the memfd_create_shared_huge test.
(I actually was running into a mysterious SIGSEGV error when running this test in 32 bit. Adding this assert helped me figure out that the mmap was failing and the SIGSEGV was due to `p2` being accessed in the `test_assert`. Of course it turns out that running this test itself in 32 bit does not make sense due to lack of address space and @khuey fixed it in his subsequent commit fe0659f8dd67659acf5bca. However I think its still a good idea to add this test_assert)
=> memfd_create_shared_huge test: Assert that mmap didn't fail

CMakeLists.txt, src/GdbServer.cc, src/test/alternate_thread_diversion.c, src/test/alternate_thread_diversion.py, src/test/alternate_thread_diversion.run
This more-or-less fixes #2836, but there's a bit of a usability snag: this only really makes sense with `scheduler-locking` set to `on`. Otherwise, GDB asks us to resume all threads and we end up just replaying the task that was stopped in the diversion session (which is pretty much the same as the behaviour currently).
I can't think of a way in which `scheduler-locking` is set to anything but `on` makes sense in this context (funnily enough, the default is `replay` which is equivalent to `on` when using GDB's built-in trace replay machinery) so it seems sensible to change rr's default similarly to the handling of `unwindonsignal`. Unfortunately this triggers a bug in GDB, so until there's fixes upstream the user just has to be careful about surrounding alternate-thread diversions with …
=> GdbServer: handle task switching during diversions

src/kernel_abi.cc, src/kernel_abi.h, src/record_syscall.cc
I haven't written a test for this since AFAICT there's no userspace API for creating virtual serial ports on Linux (the PTY driver doesn't implement these ioctls)
=> add support for TIOC{G,S}SERIAL ioctls

CMakeLists.txt, src/RecordSession.cc, src/RecordTask.cc, src/RecordTask.h, src/preload/rrcalls.h, src/record_syscall.cc, src/test/vsyscall_timeslice.c
In rare cases we can get an inopportune TIME_SLICE_SIGNAL while trying to patch a vsyscall, confusing rr. The fix is easy - the test quite a bit harder, because it only happens if we skid into a vsyscall, but I think I managed to come up with something that reliably triggers this.
Fixes https://github.com/JuliaLang/julia/issues/39206
=> Fix interaction of desched sig and vsyscall patching

src/RecordSession.cc
On systemd systems, the latter is silently and confusingly ignored (see,
approximately, https://github.com/systemd/systemd/issues/12791). The
former is compatible with non-systemd systems according to man 5
sysctl.conf, so we should suggest it instead as it works everywhere.
=> Suggest /etc/sysctl.d instead of /etc/sysctl.conf

src/PerfCounters_x86.h
Confirmed to match on a laptop with an AMD Ryzen 7 5800HS, I expect it will also cover other 5000 H-, U- and G-series APUs.
(I haven’t actually done anything *useful* with it yet—I’m only just about to start playing with rr—but at least it *matches*.)
=> Add microarch id for Zen 3 Cezanne APUs

src/RecordTask.cc
Related to commit 5c6e992b2ad1.
----
error: invalid cast from type ‘uintptr_t’ {aka ‘unsigned int’} to type ‘uint64_t’ {aka ‘long long unsigned int’}
=> Fix 32-bit build by adding cast.

src/kernel_abi.cc, src/kernel_abi.h, src/record_syscall.cc, src/test/ioctl_fs.c, src/test/util.h
I was trying to record a whole foreign-arch debootstrap run and came accross this ioctl FS_IOC_FIEMAP / 0xc020660b.
With this patch this could be completed.
Might fix #2289.
[FATAL /home/bernhard/data/entwicklung/2021/rr/2021-04-25/rr/src/record_syscall.cc:5900:rec_process_syscall_arch()]
(task 25999 (rec:25999) at time 201)
-> Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'ioctl' but got result 0 (errno SUCCESS); Unknown ioctl(0xc020660b): type:0x66 nr:0xb dir:0x3 size:32 addr:0x7ffd80c4ba10
Testcase modelled after this:
https://github.com/coreutils/coreutils/blob/ba5e6885d2c255648cddb87b4e795659c1990374/src/extent-scan.c#L94
(Got removed from coreutils in 26eccf6c98696c50f4416ba2967edc8676870716.)
=> Add support for ioctl FS_IOC_FIEMAP.

src/ReplaySession.cc
The task object given to `ReplaySession::try_one_trace_step` gets deleted
with `TSTEP_EXIT_TASK` in `ReplaySession::exit_task` / `end_task`.
Visible in replay of accept test with asan enabled rr build.
```
==3526410==ERROR: AddressSanitizer: heap-use-after-free on address 0x619000038240 at pc 0x55ab4920de95 bp 0x7ffdf9bc83e0 sp 0x7ffdf9bc83d8
READ of size 1 at 0x619000038240 thread T0
#0 0x55ab4920de94 in rr::Task::extra_regs_fallible() /home/bernhard/data/entwicklung/2021/rr/2021-04-25/rr/src/Task.cc:1041
#1 0x55ab4911642f in rr::ReplaySession::replay_step(rr::ReplaySession::StepConstraints const&) /home/bernhard/data/entwicklung/2021/rr/2021-04-25/rr/src/ReplaySession.cc:1792
#2 0x55ab490ffc56 in rr::ReplaySession::replay_step(rr::RunCommand) …
```
=> Avoid use-after-free of task object in ReplaySession::replay_step.

src/PerfCounters_x86.h
Fixes: https://github.com/rr-debugger/rr/issues/2872
I did not compare the values at `PmuConfig` to the AMD documentation because I have no idea where to find any of these. However, trying to reuse an existing line for `AMDF15R30` worked, `rr record ls` and `rr replay` works for me, reverse execution works too.
Reason I'm marking this as WIP is because a few tests are failing and I'm not sure how to proceed here.
The exact number is `28 tests failed out of 2625`, however apparently only for 10 of them fail is not expected *(I rerun all 28 of them on another laptop with Intel CPU with the same commit my current branch is based off, and 18 of them failed there too)*.
The 10 tests whose failure is apparently not expected are:
```
vsyscall
vsyscall-no-syscallbuf
vsyscall_timeslice …
```
=> WIP: PerfCounters_x86.h: add support for AMD A8-3530MX

src/test/conditional_breakpoint_offload.run
This test, especially in the no-syscallbuf variants,
takes regularly more than 120 seconds at my Ryzen 7 1700,
when running the tests in parallel.
=> Increase timeout for conditional_breakpoint_offload test.

src/Task.cc
"int raw_status" is just 4 bytes, but PTRACE_GETEVENTMSG writes
"unsigned long" with 8 bytes at x86_64.
Visible in replay of accept test.
Included is also a patch to add a cmake option to build rr with address sanitizer.
Should that be a separate PR, or is such a option even desired?
```
==2334193==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffcd0809e54 at pc 0x7f4d61cd59ef bp 0x7ffcd0809c20 sp 0x7ffcd08093d0
WRITE of size 8 at 0x7ffcd0809e54 thread T0
#0 0x7f4d61cd59ee in __interceptor_ptrace ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:3258
#1 0x55e8eae433be in rr::Task::fallible_ptrace(int, rr::remote_ptr<void>, void*) /home/bernhard/data/entwicklung/2021/rr/2021-04-25/rr/src/Task.cc:2626
#2 0x55e8eae48cba in …
```
=> Use unsigned long instead of int for PTRACE_GETEVENTMSG.

src/LsCommand.cc, src/SourcesCommand.cc, src/log.cc, src/util.cc
Those patches are just kind of cosmetic nature.
But, unless disabled by environment `ASAN_OPTIONS="detect_leaks=0"`, the first two are disturbing the test run.
The later three are just other uses of opendir without matching closedir.
=> Avoid a few small leaks to make address sanitizer happy.

src/test-monitor/test-monitor.cc
Certain tests exceed the "internal" timeout for some tests.
Then it is tried to close any recording session by force_close_record_session.
If that fails the gdb session has to wait until it reaches the ctest timeout.
This patch attempts to just trigger the record closing, but if that does not
help the test fails immediately after a short wait.
=> Do not wait for force_close_record_session.

src/preload/tweak_librrpage.py
By the commit 38571520 two new sections get now added to librrpage.so.
Therefore the assumption to relocate sections 12 to 14 did not work
anymore.
Also, librrpage.so had one section more than librrpage_32.so.
This patch assumes now, not much better but a little, that the last three
sections are .symtab, .strtab and .shstrtab, and have to be relocated.
----
And just for informational purposes:
`readelf --headers ./lib/rr/librrpage_32.so` looked like this, notice the offset greater than 0x4000:
```
Section Headers:
[Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
...
[11] .vdso.text        PROGBITS        6ffff000 002000 00006f 00   A  0   0 4096
[12] .record.text      PROGBITS        70000000 0012b0 000023 00   A  0   0 4096
[13] .replay.text      PROGBITS …
```
=> Change tweak_librrpage.py to relocate the last three sections.

src/test/ignored_async_usr1.run, src/test/nested_detach_kill.run, src/test/term_trace_cpu.run, src/test/term_trace_syscall.run
If the test `nested_detach_kill` fails to start, it waits currently for the sync token until the timeout is reached.
With this patch, if recording fails to startup, the test fails immediately.
=> Do not wait for SYNC_TOKEN until timeout exceeds, if subshell died already.

src/RecordCommand.cc
@khuey: Seems this was somehow missed in f9d555dd1f29 ?
=> Pass asan parameter into RecordSession::create.

src/ElfReader.cc
When building for 32-bit:
ElfReader.cc:516:42: error: unused parameter ‘fd’
Related commit: 998f91090d
=> Mark parameter fd to ElfFileReader::is_x32_abi as possibly unused.

src/kernel_supplement.h, src/test/x86/pkeys.c
Tried to run the tests in a rr enabled VM with Ubuntu 16.04, but these triggered
several times a kernel issue `kernel BUG at /build/linux-3Zqs18/linux-4.4.0/mm/memory.c:3214!`.
(With `4.4.0-210-generic`, `Description:    Ubuntu 16.04.7 LTS`)
Having now the first 1300 tests run, 95% did succeed.
Doing a build and test run on my usual setup, all tests succeed with these two patches.
Related to issue: #2919
=> Fixes build on Ubuntu 16.04

src/record_syscall.cc, src/test/video_capture.c
These are used by `v4l2-ctl --all`.
Assuming that a partial support of VIDIOC_TRY_EXT_CTRLS,
that would lead to a diversion fault if an application uses it with
using the v4l2_ext_controls.controls pointer, I left that out.
In 307681ffa83 is a draft that supports just the v4l2_ext_controls.count==0 case.
=> Add a few more v4l2 ioctls.

CMakeLists.txt, src/test/64bit_child.c
A couple of commits somewhat related to #2890. I've submitted it as a draft since there was one test timeout that I want to investigate but I didn't want to wait until tomorrow to follow up on #2890.
I would appreciate some extra scrutiny around the `64bit_child` test, since I'm not familiar with the details of how the kernel decides task arch-ness.
=> Some ASan-related fixes

src/test/hello.c, src/test/nested_release.run
Otherwise tests with force32bit rr would fail with the following error:
`ERROR: ld.so: object '..../librrpreload.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
=> Call an executable matching to rr signedness for the nested-release test.

src/util.cc
```
rr/src/util.cc:1513:17: error: comparison is always false due to limited
range of data type [-Werror=type-limits]
if (rport > USHRT_MAX) {
```
=> Fix build error -Werror=type-limits

scripts/setup_travis.sh, scripts/signal-rr-recording.sh, scripts/tag-release.sh, scripts/update-gh-pages.sh
Systems may have bash in different paths, so find bash with env.
=> Avoid hard-coding bash path

src/PerfCounters_x86.h
```
The following tests FAILED:
901 - cont_race-no-syscallbuf (Failed)
1021 - perf_event_mmap-no-syscallbuf (Failed)
2262 - crash_in_function-32 (Failed)
2263 - crash_in_function-32-no-syscallbuf (Failed)
2377 - perf_event_mmap-32-no-syscallbuf (Failed)
```
[The files in Testing/Temporary: ](https://drive.google.com/file/d/15mpgeb76qvUmGACOLzcCxV2Gij0jz0LG/view?usp=sharing)
=> Add AMD Lucienne; fix error message logic.

src/ExtraRegisters.cc
Fixes the following in 32bit mode:
```
ExtraRegisters.cc:665: void rr::ExtraRegisters::reset(): Assertion `d.xsave_feature_bit == PKRU_FEATURE_BIT' failed.
```
=> Fix 32-bit exec on PKRU-capable x86 CPU

third-party/gdb/64bit-seg.xml
I was playing with making use of these from the GDB side
and just got garbage because the name was off, so there
were actually two copies of these registers (the one that
GDB allocated and the one it got from the XML). Unfortunately,
I don't really know of a good test for this from the GDB prompt.
See https://github.com/bminor/binutils-gdb/blob/master/gdb/features/i386/64bit-segments.xml
=> Correct GDB feature name for segment registers

src/test/comm.py, src/test/fcntl_misc.c
- `test_fcntl`, which failed because the pipe limit was restricted on my kernel
- `comm`, which didn't account for 32bit
=> Fix two test failures seen locally

CMakeLists.txt, src/RecordSession.cc, src/Task.cc, src/test/desched_sigkill.c
There are two issues here:
1. We shouldn't attempt to do a `waitpid` if we know the process is
dying, because our `waitpid` calling is pretty carefully choreographed
after receiving PTRACE_EVENT_EXIT and an extra waitpid messes that up.
2. `advance_to_disarm_desched_syscall` wasn't robust to the possibility
that the task could die and would infinite loop.
Fix both by adding appropriate checks. Fixes #3000.
=> Handle unexpected exits in desched processing (fixes #3000)

src/Task.cc
That's not much but allows easier checks of the event the debugger and does spare some cpu cycles (in the error case) and removes the logical check "Does this function has possible side effects?" (it hasn't, but to be sure one has to look at its code, not necessary when just comparing the previous value).
=> Task::wait_exit with less cpu cycles in error case

src/PerfCounters.cc, src/PerfCounters_x86.h
This adds the ```cpu_type``` definition, which is enough to make most 64-bits tests pass. All 32-bit tests fail with
```1358: rr: ../src/ExtraRegisters.cc:665: void rr::ExtraRegisters::reset(): Assertion `d.xsave_feature_bit == PKRU_FEATURE_BIT' failed.```
Still investigating that.
=> Add cpu_type for Intel Alder Lake.

CMakeLists.txt, src/RecordSession.cc, src/RecordSession.h, src/Scheduler.cc, src/test/detach_sigkill.c
When we detach a child, we keep around the zombie (or more accurately,
we keep it in PTRACE_EVENT_EXIT state) of the original process to
prevent the kernel from re-using it's pid and to enable
basic wait4 processing using the original child's tid to make the
detach of the child as transparent as possible to any traced parent.
However so far, we did not handle signals targeting the original tid.
That's not really a big problem, because ptrace zombies don't really have
signal handling. As an exception to this however, a SIGKILL will advance
the ptrace zombie out of PTRACE_EVENT_EXIT state and into a proper zombie
state, which our `wait_any` listener will reap. This reaping then
confuses our later handling of this process leading to #3016. Fix that
by keeping track of the detached proxies …
=> Forward SIGKILL to detached children (fix #3016)

src/preload/rr_page.ld, src/preload/rr_vdso.S
In 38571520bee9360aeb454a14be1de43e7490f324, we added symbol versioning
to our fake vdso to support Chromium which was looking for these entries
in the vdso. Unfortunately, this broke older libcs' symbol lookup which
specified LINUX2.6 as a symbol version (if the vdso isn't versioned at
all, the symbol version specifier is ignored). This got fixed in
In 8a15f2acdd39d799001c98107e72c2bed4ec63e9, where vdso versioning was
added for __vdso symbols. However, even older libs appear to be looking
for symbols without the __vdso prefix (but still versioned), so add those
as well.
=> Fix rr vdso symbols on even older libc

CMakeLists.txt, src/Scheduler.cc, src/test/detach_sigkill_exit.c
This fixes the failure seen in [1], which in relevant part looks
like this:
```
[FATAL /workspace/srcdir/rr/src/Scheduler.cc:526:find_waited_task() errno: ECHILD]
(task 6055 (rec:6087) at time 62487)
-> Assertion `npid == waited->rec_tid' failed to hold.
[INFO log_pending_events()] SYSCALL: rrcall_detach_teleport
```
This is a supplement to cfb5163c2, which was incomplete. In particular, if a
detached process has already exited, then its PID was reaped, so we
must not attempt to SIGKILL it.
[1] https://build.julialang.org/#/builders/70/builds/919/steps/5/logs/stdio
=> Fix SIGKILL racing with detached proxy exit

src/EmuFs.cc
Courtesy of the julia deployment system which wants to keep compatibility
with CentOS6 for certain HPC users ;). This is for the `SEEK_HOLE`/`SEEK_DATA`
definitions. Builds fine locally on modern libc also.
=> Fix build on old glibc

src/RecordCommand.cc, src/log.cc, src/log.h, src/main.cc
Both #3037 and #3038 are missing log output, despite RR_LOG (and RR_LOG_BUFFER)
being set. This is because they were started under another rr session with
`--nested=detach`, so their configuration variable automatically changed to
`RR_UNDER_RR_LOG`. Given the use case of `--nested=detach` to parallelize a
bunch of recordings, I don't think this behavior is particularly useful.
This tries to improve the situation by:
1. Making rr reload the logging configuration after a detach
2. Adding an `rr --log=...` cli switch to make it easier to force
a particular logging configuration for a particular rr execution
independent of which nesting level they're at.
=> Respect RR_LOG after detach / add --log cli switch

src/ReplaySession.cc, src/TraceStream.cc, src/TraceStream.h, src/rr_trace.capnp
=> Handle backwards compatibility for traces without force_tick.

.buildkite/pipeline.yml
In the Julia Project, we use Buildkite[^1] to run CI on our own machines. Most of our machines are reserved for use by Base Julia CI on the main Julia repository[^2]. However, we do have one Buildkite queue (the `juliaecosystem` queue) that is intended for use by repositories in the Julia ecosystem.
We thought it might be nice to use the `juliaecosystem` queue to offer some of our CI resources to the rr project.
[^1]: https://buildkite.com/julialang
[^2]: https://github.com/JuliaLang/julia
=> Set up Buildkite CI on the `juliaecosystem` queue provided by the Julia Project

src/test/getsid.c
`getsid` can return `0` if the session leader is not a member of the calling process's pid namespace. Don't fail the test in this case. `getsid` returns -1 on error.
=> test/getsid: 0 is a valid session ID

src/test/ioctl_tty.c
Similar to #3047, if the pgrp of the controlling tty is outside of
the current task's pid namespace, `TIOCGPGRP` will return 0, which
is not a valid argument for `TIOCSPGRP`.
=> test/ioctl_tty: Allow for 0 pid of controlling tty pgrp

.buildkite/pipeline.yml
In the Buildkite settings[^1], I've enabled the "Update commit statuses" option. So we don't need to also specify it in the pipeline YAML.
[^1]: https://buildkite.com/julialang/rr/settings/repository
=> CI: remove the duplicate commit status

.buildkite/pipeline.yml
This will allow us to use the `ctest --output-junit <file>` option in the future.
=> CI: update to `cmake` version 3.22.1

index.html
Note: the base (target) branch of this pull request is the `gh-pages` branch.
---
Currently, the navigation bar at the top of the website has a `ci` link that points to `https://ci.rr-project.org/`, which seems to no longer exist.
Therefore, I suggest removing the `ci` link from the navigation bar.
Once all tests are passing on Buildkite, I would suggest merging #3052, which adds a Buildkite badge to the README.
=> [`gh-pages`] Remove the `ci` link from the navigation bar at the top of the website

src/RerunCommand.cc
If for any reason `DIVERSION_EXITED`, then break out of `diversion_step()` loop
=> run_diversion_function: break out of loop if DIVERSION_EXITED

src/GdbConnection.cc
Hello,
In single-process mode, lldb likes to send continue packets like this:
`vCont;c:1;c:2;c:3;c:4`
That is, a list of actions and threads, but no process IDs. 
The current code in `parse_threadid` accepts either `vCont;c:1` (one single thread), or `vCont;c:1.1;c:1.2` (multiple threads, but with PID for each). It does not support receiving a list of threads without PID, and it results in aborting the session with assertion failure: `Failed to parse gdb request`.
This PR changes `parse_threadid` to accept lists of threads without PIDs, as long as they are separated by `\0`, `,` or `;`, which is what the existing code appeared to care about in the various usages of `parse_threadid`.
=> parse_threadid: Tolerate \0 or ; or ,

src/test/setuid.c
Inside a user namespace, calling setgid with an unmapped `gid` will return
EINVAL, not EPERM. Accept that in case the environemnt we're running in
is a container.
=> setuid: Allow EINVAL error code

src/test/cwd_inaccessible.c
Similar to #3069, unmapped UIDs in the container end up as
`(uint16_t)-2`. Treat that the same as the user not existing.
=> Check for unmapped uid in cwd_inaccessible test

src/test/chown.c
When a supplemental group of the current user is not mapped in a
user namespace, `getgroups` replaces the group id by `(uint16_t)-2`.
However, of course that's an invalid group id for `chown`, so filter
those out in the chown test.
=> chown: Filter unmapped container groups

.buildkite/pipeline.yml
This allows us to see what versions of `Sandbox.jl` and `UserNSSandbox_jll.jl` are being used.
=> CI: pass `verbose: true` to the sandbox plugin

src/PerfCounters_x86.h
On my Thinkpad X13 Gen 2 (with a i7-1185G7 CPU, BIOS version N35ET43W) I observe irregularities in the rr ticks counter that prevent rr from working correctly. I was able to correlate these irregularities with SMI events (as observed with MSR_SMI_COUNT). Setting IA32_DEBUGCTL.FREEZE_ON_SMM (via /sys/devices/cpu/freeze_on_smi) does fix the problem for me. Another user reported seeing the same problem, that is fixed by the same solution, on a i7-10610U.
Fixes #3045
=> Check for freeze_on_smi being set.

CMakeLists.txt
From time to time I try a force32bit build.
Today it stopped with this message:
```
.../rr/src/counters-test/counters.c: In function ‘child_wait’:
.../rr/src/counters-test/counters.c:305:3: error: the register ‘r11’ cannot be clobbered in ‘asm’ for the current target
305 |   __asm__ __volatile__ ("syscall" : : "a"(__NR_write), "D"(child_to_parent_fds[1]), "S"("x"), "d"(1) : "rcx", "r11", "flags");
|   ^~~~~~~
```
The commit message of de389f7 mentions this test just targets x86_64, but 983607124 did just limit it to x86_64 and i386.
Just for information, with this small modification all tests succeeded (a few at least in the second non-parallel attempt) with regular x86_64 build and with a force32bit build with my AMD Ryzen 7 1700 and a kernel `Debian 5.15.15-1`.
=> Skip building counters.c on non-x86_64 platforms.

.gitignore, CMakeLists.txt
Reproduced with clang11 & ninja on Ubuntu 20.04 with Ryzen 3950X
The missing `-flto` flag caused an error in final linking as binary objects are now LLVM IR. 
```
...
CMakeFiles/rr.dir/src/AddressSpace.cc.o: file not recognized: file format not recognized
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[1994/2505] Building C object CMakeFil...ss_32.dir/32/simple_threads_stress.c.o
ninja: build stopped: subcommand failed.
```
Ran the tests locally, where one test fails, but it does both for Release as well as for Debug builds:
```
99% tests passed, 1 tests failed out of 2749
Total Test time (real) = 240.37 sec
The following tests FAILED:
635 - setuid-no-syscallbuf (Failed)
Errors while running CTest
```
```
ctest -R setuid-no-syscallbuf
Test project …
```
=> Fixed Release build because of a missing `-flto` flag

src/ftrace/ftrace_helper.c
I actually thought there were two tools `trace_helper` and `ftrace_helper`, but realized this is a small typo.
=> Minor typo: trace_helper => ftrace_helper

src/PerfCounters_x86.h
This cpu_type is from an Intel J4105 [1]. Test logs can be found at [2].
Closes #3098.
[1] https://ark.intel.com/content/www/us/en/ark/products/128992/intel-celeron-j4005-processor-4m-cache-up-to-2-70-ghz.html
[2] https://github.com/rr-debugger/rr/issues/3098#issuecomment-1068920887
=> Add Goldmont Plus aka. Gemini Lake

src/PerfCounters_x86.h
Users may not realize that tmpfiles.d requires a reboot (#3103).
Tweak the message to hopfully make clear how to both enable
the setting immediately and that the tmpfiles.d mechanism applies
on reboot.
=> Tweak freeze_on_smi message

src/GdbServer.cc
fs_base and gs_base should be returned even for CPUs that do not have
AVX registers.
Originally reported as https://github.com/go-delve/delve/discussions/2934
=> Return fs_base/gs_base on CPUs that do not have AVX

src/test/vsyscall_reverse_next.run
This test has been observed to take 250s under regular conditions on CI,
which is too close for comfort. Let's see if we can at least get this test to
reliably finish.
Part of #3102.
=> Increase timeout for vsyscall_reverse_next

src/Session.cc
In rr, we have a mechanism to have several rr workers coordinate which
CPUs to pin to. However, because we have no freedom to choose the CPU
to pin to during replay, we were not marking those CPUs as in use, thus
allowing concurrent record calls to pin themselves to the same CPUs
(and even worse then causing their subsequent replay to also be bound
to the same CPU). Try to fix that by making sure to still acquire the
appropriate CPU lock in the replay path. There is still a small window
between the end of the record and the start of the replay where another
record could start on the same CPU, but let's assume that race isn't
hit for the moment.
=> Properly use cpu_lock for replay

.buildkite/pipeline.yml
We can avoid a second install of Julia (saving some precious seconds on CI) by mounting in our `/cache` directory explicitly.
Because `PATH` etc... are all inherited from the parent environment, we automatically have access to the `julia` executable within the sandbox, as long as it's mounted in the same place as it exists outside of the sandbox.
=> [ci] Don't install julia twice on CI

src/test/cont_race.run
This test has been observed on AMD to take more time than the allotted 120s for the usual AMD-specific slowdown reasons. Give it more time to avoid it failing on CI.
=> Give cont_race more time

.buildkite/capture_tmpdir.jl, .buildkite/pipeline.yml
=> CI: add an async timer to kill `ctest` before the Buildkite job times out

CMakeLists.txt, Vagrantfile, snap/snapcraft.yaml, src/ElfReader.cc, src/ElfReader.h, src/SourcesCommand.cc, src/kernel_abi.h
Closes #3125
This deserves actual review.
=> Handle both zlib-gapi and zlib-gnu compression of debug sections for `rr sources`.

.buildkite/pipeline.yml
This PR allows us to have a more readable CI job name that includes spaces, while still having a key (not displayed directly to the end user) that adheres to Buildkite's restrictions.
=> CI: more readable job names

CMakeLists.txt, src/record_syscall.cc, src/syscalls.py, src/test/close_range.c
This doesn't really fully fix #2994, but it allows to record programs
that use it and properly fall back to close(), like glib etc.
=> Emulate ENOSYS for close_range.

src/kernel_abi.h
The actual structure contains saved vector registers and is therefore 16bytes aligned.
This causes the offset of uc_mcontext in ucontext to be wrong and in particular
the address where x7 is saved is wrong when we try to read it in the kernel bug workaround.
=> Fix sigcontext alignment on AArch64

src/test/personality.c
Current apple chips and future ARM chips will drop the support for 32bit mode
=> Allow LINUX32 support to be absent on aarch64

src/test/patch_page_end.c
blr clobbers the link register causing the return from `do_call` to be completely messed up.
Similar to 8a8861a25777a444f75864a31e168ffd90799bd9, the test still doesn't pass but it should at least fail with the correct error now...
=> Fix patch page end test segfault

src/test/sysconf.c
Minor, non breaking part for https://github.com/rr-debugger/rr/issues/3143
=> Allow page size up to 64k on aarch64 in sysconf test

src/GdbServer.cc, src/util.cc
In #3129, we're hitting some assertion, but the process is dead without
printing anything before we get a GDB backtrace. Hopefully this will shed
some light on the situation.
=> Unconditionally print rr stack if something goes wrong

src/test/fcntl_rw_hints.c
This is removed in https://github.com/torvalds/linux/commit/7b12e49669c99f63bc12351c57e581f1f14d4adf which is in 5.18-rc releases.
=> Handle F_(GET|SET)_FILE_RW_HINT removal

src/test/brk2.c, src/test/mount_ns_exec2.c
Some other failing tests on apple-m1 only due to wrong page size assumptions.
=> Fix more 4k pages assumptions in tests

src/RecordCommand.cc
Automatically round it up to the page size.
This way wrapper scripts (including the tests) don't have to detect the page size...
This is mainly to fix tests, which, I know, isn't a great reason for changing the behavior of normal code... However, this is just a command line option and unless there's a good reason to throw a error about using a slightly different size than the one requested, I feel like being slightly more relaxed here is going to make everyone's life easier. (If not, I could put `getconf PAGESIZE` in the test scripts as well as figuring out a way to do division in shell script...)
=> Allow a syscall buffer size smaller than page size to be passed in

src/AddressSpace.cc, src/AutoRemoteSyscalls.cc, src/AutoRemoteSyscalls.h, src/Monkeypatcher.cc, src/Monkeypatcher.h, src/Session.cc, src/Task.cc, src/record_syscall.cc, src/replay_syscall.cc
Previously, the code uses a mixture of 4k, page_size() and rr_page_size() as unit.
We now switch to using 4k as the unit everywhere since,
1. This makes the number platform independent
2. Most of the time the caller already know the bytes offsets so it make sense to
treat the argument as a offset in a larger unit
3. This is the convension used by the mmap2 system call. Some of the users directlly calls
that so it's good to be consistent with mmap2.
This is another part of https://github.com/rr-debugger/rr/pull/3146 that should be completely non-breaking (though not so minor).
=> Consistently use 4k as the size unit for mmap2-like internal functions

src/Task.cc
Newer architectures like AArch64 does not have dup2.
dup3 was added in kernel version 2.6.27 which is older than rr's kernel requirement of 3.11
so we can just use dup3 everywhere.
=> Use dup3 instead of dup2

src/util.cc
Otherwise, on AArch64, the clone recording fails to record the write of child_tid
from the kernel with CLONE_CHILD_SETTID or CLONE_CHILD_CLEARTID.
I'm not 100% sure if this is the best fix but I believe this is a correct fix because,
* On x86, this is a no-op since the arg1 and orig_arg1 points to the same location.
* On AArch64 this makes sure we get the right value for the flags.
Out of the three current callers of extract_clone_parameters:
1. Pre-cloning one in prepare_clone(RecordTask*) always see the same value for the two
2. Post-cloning one in prepare_clone(RecordTask*) only sees the correct value in
orig_arg1. I believe arg1 is also expected to hold the return value at this point
so it cannot be modified anymore.
3. The one in prepare_clone(ReplayTask*) only sees the correct value …
=> Use orig_arg1 to get the clone flag

CMakeLists.txt, src/preload/overrides.c, src/preload/syscallbuf.c, src/preload/syscallbuf.h
Make syscallbuf and override more independent.
This allow some tests with pthread mutex to pass and I assume it'll be better for graphic programs as well (due to the x-related override)
It seems that there are some fairly delicate ordering issue here but I think the changes here are safe. No change in the test results when testing locally on x86.
=> Enable a stripped down version of librrpreload on aarch64

src/Task.cc
These are documented in the manual as x86-only.
Even if we have a version for aarch64/other arch with similar function, they'll probably have a different name.
=> Disable x86 specific prctl on aarch64

src/record_syscall.cc, src/replay_syscall.cc
* In post-processing syscall in recording, orig_arg1 is always the correct one to use
since on aarch64 arg1 holds the syscall return value at this point.
This was causing failure to register the correct BPF monitor
and logging of socket addresses.
* Similarly, for post-processing syscall in replay of clone,
we've already set arg1 to the return value and we need to get the clone flag
from the original value of arg1.
This causes rr to miss the VM cloning and failed to remove a breakpoint
in detached process, causing a hang in gdb.
* For recovering registers in replay, we should set orig_arg1.
The current code overrides syscall_result although it didn't seem to be causing any failures
=> Fix more arg1 vs orig_arg1 usage for AArch64

src/ExtraRegisters.cc
Remove incorrect assertion and implement set registers
I assume at least the assertion in the get function is simply an oversight from https://github.com/rr-debugger/rr/pull/2567 . I also don't see why the set function can't be implemented. (of course both still have the caveat that there are still more registers than these to be saved).
=> Fix get/set extra register on aarch64

src/test/get_thread_list.py, src/test/reverse_step_signal.py
* On AArch64 with glibc, raise calls `__kill_implementation`
so raise won't be in the output when the execution stopped.
This test (reverse_step_signal) is simple enough that I think looking for the symbol
in the backtrace is simpler and more general than looking for a range of
implementation dependent names.
* Add `pthread_barrier_wait` to allowed symbols within `pthread_barrier_wait`
on AArch64 as well.
It matches what x86 has, is what I observed on my system, and in this case
since we are counting occurance, is probably more preferred/simpler to do than printing
the backtraces for each thread.
=> Fix test due to difference in symbol name/glibc implementations

src/kernel_metadata.cc
Noticed when I'm dumping the ptrace calls for debugging...
=> Support PTRACE_{GET|SET}SIGMASK in ptrace_req_name

src/ProcFdDirMonitor.cc, src/ProcMemMonitor.cc, src/test/proc_fds.c, src/test/proc_mem.c, src/util.cc, src/util.h
This patch fixes the parsing of the thread ID from
the proc filesystem. Man pages for proc on linux says;
There are two paths for a running thread that is not a
thread group leader;
/proc/[tid]/.. and /proc/[pid]/task/[tid]/...
rr currently does not register to watch on the latter.
The parsing of the tid is lifted into it's own function in util.h/cc,
which ProcMemMonitor and ProcFdDirMonitor calls.
Recording and replaying (issue #3182 was specifically for GDB)
is tested and with this patch, rr does not fail.
Test cases for /proc/pid/task/tid written by @khuey
=> Fixes #3182 - Overshooting sys calls

src/preload/syscallbuf.c
Rebase error from d3c235a17d5a37accc073577f0f3fccc2f5e962a
=> Remove duplicated rrcall_init_preload call

src/AutoRemoteSyscalls.cc
AFAICT the kernel interface is the same as x64 (and other 64bit archs)
=> Handle aarch64 in infallible_lseek_syscall

src/preload/raw_syscall.S
The syscall must be made from one our the entries in rrpage.
Otherwise syscallbuf logic cannot detect it correctly.
Also add a comment regarding the extra stack arguments.
There's nothing we need to do about them ATM since we aren't doing
any post-processing, if we do, then we'll have to save/restore x30
which will require re-pushing those arguments.
This may require https://github.com/rr-debugger/rr/pull/3191 to avoid regression on aarch64. (I've never tested it without some of my WIP syscallbuf stuff)
=> Fix raw syscall for aarch64

src/AddressSpace.cc, src/Monkeypatcher.cc, src/RecordTask.cc, src/Task.cc
These are called in the syscall exit stop at which point arg1 is already overwritten.
=> Use orig_arg1 to access rrcall parameter during recording

src/RecordTask.cc, src/Registers.h
On aarch64, the return address is in lr after the call.
Not on the stack...
=> Get return address correctly on aarch64

src/GdbCommandHandler.cc, src/GdbServer.cc
Executing this command (I had that in a script) would otherwise lead to
> ERROR /tmp/install/rr/src/GdbServer.cc:631:dispatch_debugger_request()] Attempt to write register outside diversion session
Now it raises a nice user-visible gdb error
> Execution of 'jump' is not possible in recorded executions.
There are possibly more commands to "forbid", the suggested change can be easily extended to other commands.
[side note: sadly I found no way to redefine a mi command so `-exec-jump` still leads to the error above]
=> prevent use of bad commands like "jump"

CMakeLists.txt, src/AutoRemoteSyscalls.cc, src/AutoRemoteSyscalls.h, src/RecordTask.cc, src/RecordTask.h, src/Registers.cc, src/Scheduler.cc, src/Task.cc, src/preload/rrcalls.h, src/record_syscall.cc, src/test/futex_restart_race.c, src/test/util_internal.h
Fix #3141 and #3147. In essence the issue is that AutoRemoteSyscall needs to work harder to actually restore the state that it was in at the start. Details are in the individual commit messages.
=> More fully restore kernel state in AutoRemoteSyscalls

src/RecordSession.cc, src/RecordTask.cc, src/RecordTask.h, src/kernel_abi.cc, src/kernel_abi.h, src/record_syscall.cc, src/test/ptrace_exec.c, src/test/ptrace_remote_unmap.c, src/test/ptrace_seize.c, src/test/ptrace_syscall.c, src/test/ptrace_util.h
This implements two missing ptrace commands: PTRACE_INTERRUPT and
PTRACE_GET_SYSCALL_INFO. While we're here, also fix a bug where
hitting a PTRACE_EVENT_EXEC using PTRACE_SYSCALL would cause rr
to assert, because it had no mechanism by which to wait for the
ptracer to acknowledge the PTRACE_EVENT_EXEC before continuing
to the syscall exit stop. Fix that by moving the point at which
we signal the emulated PTRACE_EVENT_EXEC to when rr receives the
real PTRACE_EVENT_EXEC, after which we get a full round trip to
record_step again and can thus handle the task being suspended
just fine. One minor complication is that this conflicts with
the threadgroup exec region from ee6df921, which currently
ends only upon return from the exec syscall (which happens
after the exec stop). I don't entirely …
=> Improve ptrace emulation

src/test/patch_page_end.c
On AArch64, we only need to patch the syscall instruction to a branch so updating the test for that. I specifically removed the nops for aarch64 in this test to make sure we can achieve that.
=> Fix patch page end test on aarch64

src/preload/rr_page.ld.in, src/preload/rr_vdso.S
AFAICT the vdso on aarch64 doesn't have any alias
```
DYNAMIC SYMBOL TABLE:
0000000000000000 g    DO *ABS*  0000000000000000  LINUX_2.6.39 LINUX_2.6.39
0000000000000760 g    DF .text  0000000000000078  LINUX_2.6.39 __kernel_clock_getres
00000000000007dc g    D  .text  0000000000000008  LINUX_2.6.39 __kernel_rt_sigreturn
0000000000000740 g    DF .text  000000000000001c  LINUX_2.6.39 __kernel_gettimeofday
0000000000000720 g    DF .text  000000000000001c  LINUX_2.6.39 __kernel_clock_gettime
```
Tested locally that the vdso we put in indeed got called and I can get a backtrace from them.
=> Implement vdso replacement on aarch64

src/test/vdso_clock_gettime_stack.c, src/test/vdso_gettimeofday_stack.c, src/test/vdso_time_stack.c
On AArch64 where the page size may be as large as 64k,
it takes many more calls of the vdso function in order to guarantee we hit a overflow.
=> Increase number of vdso calls to guarantee a overflow

src/Monkeypatcher.cc
It is still not implemented yet but since the syscallbuf isn't implemented the unpatching has nothing to do anyway.
This is currently causing test failures due to the rrcall made from the tests.
(The syscallbuf implementation will of course include an implementation for unpatch as well)
=> Do not throw an error in unpatching on aarch64

src/preload/overrides.c
Of course I don't have a PR for the syscall buf just yet but I'm fairly confident that a single instruction is all what I want to patch on aarch64.
=> No need to override geteuid on aarch64

src/preload/raw_syscall.S
Turns out I was wrong in https://github.com/rr-debugger/rr/pull/3192 regarding the stack layout since I forgot about the automatic push of return address onto the stack on x86......
This makes sure the stack layout is identical to that on x86
so that we don't need to worry about this much on the host side, even though there's only one use of these parameters AFAICT.
Depending on what kernel behavior we may need to mimic here, having the return path go through here may be useful as well in the future.
=> Fix stack layout in _raw_syscall on aarch64

src/RecordSession.cc, src/ReplaySession.cc, src/record_signal.cc
These only affects AArch64.
There might be more of these but for now these are the ones that has caused problems for me (following call getting the wrong syscall number). I feel like this should probably be tracked in a central location to mimic the kernel behavior on x86 better but this seems to be the current solution used in other places as well....
=> Update origin syscallno on SYSCALL entry stop

src/RecordSession.cc
Unlike x86, the pc is already moved to before the syscall on aarch64 before the kernel inform us about it.
I have not really gone through all the code paths and confirm the state of the pc when it gets here but the change is consistent with the comment above https://github.com/rr-debugger/rr/blob/b8368dd96b7e25f4cc0b2faa6fd3eeadf6d0f22e/src/RecordSession.cc#L1614 as well as https://github.com/rr-debugger/rr/blob/b8368dd96b7e25f4cc0b2faa6fd3eeadf6d0f22e/src/ReplaySession.cc#L1786 .
I've also put in an assertion here to make sure that the instruction the ip points to is indeed the syscall instruction. There are about 40 tests that hits this path and all of them confirms the observation.
I suspect this don't usually show up because the instruction is fixed length and the instruction before …
=> Fix syscall restart after signal on aarch64

CMakeLists.txt, src/test/dev_tty.run, src/test/netfilter.c, src/test/ttyname.c, src/test/ttyname.run, src/test/util.h
These are some tweaks to improve test failure readability I ran into with ttyname and netfilter.
=> Tweaks for various test failures

src/kernel_abi.h
There are two different versions of this struct (the glibc one being larger).
We have to include the kernel headers directly to get at the correct one
and make sure that we don't include the conflicting glibc headers. The result
is a little gross but I don't see a better way to do this.
=> Use the kernel termios struct, not the glibc one.

src/Scheduler.cc, src/Scheduler.h
It was removed from C++17. Now you have to pass a random number generator into
shuffle. This initializes a PRNG (default_random_engine) with an actual entropy
source (random_device, which should be either RDRAND or /dev/urandom) and then
passes that into each shuffle call.
=> Stop using random_shuffle.

src/AddressSpace.cc, src/ExportImportCheckpoints.cc, src/PackCommand.cc, src/PerfCounters.cc, src/RecordTask.cc, src/ScopedFd.h, src/Session.cc, src/Task.cc, src/ftrace.cc, src/util.cc
`ScopedFd` has implicit conversions to and from `int`. This is
very dangerous, because patterns like:
```
void f(ScopedFd &fd) {}
void g(int fd) { f(fd); }
void h(ScopedFd &fd) { g(fd); }
```
will compile without complaint, but will actually introduce an
additional `::close` call due to the implicitly constructed
`ScopedFd`. There were a number of instances of this issue
in the codebase. Try to prevent this from happening again
in the future by making the ScopedFd constructor explicit.
Should fix #3038
=> Fix accidental double-close of fds

src/DiversionSession.cc, src/DiversionSession.h, src/PerfCounters.cc, src/PerfCounters.h, src/PerfCounters_aarch64.h, src/PerfCounters_x86.h, src/RecordSession.cc, src/ReplaySession.cc, src/ReplaySession.h, src/Session.cc, src/Session.h, src/Task.cc, src/record_syscall.cc
This is a clean up of the non-apple specific part of https://github.com/rr-debugger/rr/pull/3144 and should be applicable to other ARM cores as well. Once this is done, I think #3144 would be basically ready as well. If anyone can test this on a neoverse-n1 machine that'll be much appreciated (since I don't have access to one...). Since this mainly touches the initialization code, just run any rr command with the logging level set to at least warning would be useful enough.
Generally speaking, on aarch64, one has to read from core type specific PMU events. The kernel does not provide any support for consolidating that into a single event. This is generally available under `/sys/bus/event_source/devices/` as documented under dynamic PMU in `perf_event_open` though I cannot find any …
=> Add dynamic PMU type support for aarch64

src/PerfCounters.cc, src/PerfCounters_aarch64.h
* 140: total instruction count. (This is actually not 100% stable when running the same code)
* 141: total branch instructions (stable)
* 142: total calls (stable)
* 143: total return (stable)
* 144: total branch taken (stable)
* 147: total indirect branch (stable)
* 148/159: total conditional branch (both stable and have the same values so far)
* 179: exclusive access or cas failed (stable) (note that this includes lse atomic instruction so it can't be used to determine if llsc is used)
Also note that I've measured a significant slow down when cas fails with no contention (simply supplying the wrong comparison values) and potentionally measured a marger larger uops count so I wonder if lse instructions are actually micro coded....
* 180: exclusive access or cas success (stable) (same as …
=> Support apple M1

src/Monkeypatcher.cc
This is cherry-picked from #3235 and this is actually more of a request for clarification than useful patch.
I do not see a check for this elsewhere, the closest is the `t->is_in_traced_syscall()` above but that only cover 2 of the many syscall sites in the rr page. On AArch64 with syscallbuf and a broken syscall restart detection (i.e. https://github.com/yuyichao/rr/commit/5f6e008ec7f671dc4acf021cbc233a1b00ca27e9) I am seeing code reaching here with a rrpage address and fixing the syscall restart logic fixes it. I did the fix, which I still need to convince myself whether it's correct/complete or not, only because I see the x86 version diverges with the aarch64 from here but I don't really know what is the invariant that should prevent this from happening.
That said, I do think an …
=> Add an assertion to make sure we never try to patch syscall from rrpage

src/preload/syscallbuf.c
The initializer syntax zero initialize the rest of the members.
If we want to avoid initializing these members,
we should avoid touching them at the syntax level.
=> Suppress compile warning about uninitialized variable

src/preload/syscallbuf.c
We should not use the preload page size here since if the page size is smaller it's possible that only part of the preload page is actually mapped.
On linux, the msync implementation rounds the length argument up to page size so simply using a length of 1 works.
If people have other preferences, getting the actual page size, or just use 4096, or using `mincore` may also work. It seems that this should be the simplest fix though.
=> Fix check for existance of memory maps

src/Registers.cc
On x86 this is exactly the same as arg1 but this is not the case on aarch64
I swear that failing to update orig_arg1 accounts for at least half of the test failures that I've seen so far on aarch64......
=> Print orig_arg1 value on aarch64

src/ProcFdDirMonitor.cc
Need to use orig_arg1 on aarch64.
=> Fix proc_fd filtering

src/ReplaySession.cc
This simulate an actual syscall entry which is what later code expects.
Without this, we'll get the wrong syscall argument when we try to replay
the side-effect of this call.
=> Update the orig_* registers when we enter an assist syscall

src/kernel_abi.h, src/test/x86/ptrace.c
I discovered these because the glibc definitions don't match the bionic definitions, and it turns out our existing definitions are wrong. The test I added does fail before this change.
=> Fix a couple struct layouts

CMakeLists.txt, src/GdbServer.cc, src/GdbServer.h, src/util.cc
rr uses/integrates with three glibc specific features
1. execinfo.h's backtrace is used to dump rr's stack during assertions
2. rr supports rtld-audit (I don't actually know what this does, but it doesn't matter)
3. rr supports glibc/gdb's libthread_db.so
Bionic doesn't support any of these, so check for them at build time and disable the relevant features if necessary.
=> Disable various glibc integrations at build time if we're not being built with glibc

src/GdbServer.cc, src/ReplaySession.h, src/ReplayTimeline.cc, src/ReplayTimeline.h
This is now completely unused.
Noticed when debugging https://github.com/rr-debugger/rr/issues/3252. Not sure if this is expected / correct but AFAICT this is simply making the code confusing to read at this point...
Therefore, I think this should either be removed (this PR) or something should actually be using it....
=> Remove StepConstraints::stop_at_time

src/test/test_setup.gdb
Otherwise gdb may ask about whether it should be enabled during the test and hang forever.
This starts to happen on ArchLinux recently and is causing the debug tests to timeout.
=> Disable gdb debuginfod in test

src/ReplayTimeline.cc
Pretty much all due to the watchpoint being triggered before the instruction runs.
=> Fixes for reverse watchpoint handling on aarch64

CMakeLists.txt, src/GdbServer.cc, src/test/tick0.c, src/test/tick0.py, src/test/tick0.run, src/test/tick0_less.run
* Make sure we execute the first event that is at the desired tick
Previously, we stop before the last event that's no later than the tick.
This causes us to undershot which is especially bad when seeking to beginning
past the ticks reset.
* Also add explicit test for seeking to tick 0
when the first event happens at ticks > 0 and ticks == 0
Fix #3252
The document for `seek_to_ticks` says "during event `time`" but I'm not 100% sure if the period between frame times counts as part of the event before or after it.... The current behavior seems to be that we are seeking to the period before the event, which agrees with what `when` command says so I'm keeping it this way. As such, the frame time passed in right now should be that of the event right after where we want to seek to.
=> Fix seeking to ticks

CMakeLists.txt, src/Event.h, src/Monkeypatcher.cc, src/Monkeypatcher.h, src/Registers.h, src/ReplaySession.cc, src/ReplaySession.h, src/ReplayTask.cc, src/Session.h, src/TraceStream.cc, src/assembly_templates.py, src/preload/preload_interface.h, src/preload/rrcalls.h, src/preload/syscall_hook.S, src/preload/syscallbuf.c, src/record_signal.cc, src/record_syscall.cc, src/rr_trace.capnp, src/syscalls.py, src/test/x86/rdtsc_flags.c, src/test/x86/rdtsc_loop.c, src/test/x86/rdtsc_loop.run, src/util.h
Before:
[roc@localhost rr]$ time rr record ~/rr/obj/bin/rdtsc_loop
rr: Saving execution to trace directory `/home/roc/.local/share/rr/rdtsc_loop-19'.
EXIT-SUCCESS
real    8m15.591s
user    5m9.203s
sys     3m10.668s
After:
[roc@localhost rr]$ time rr record ~/rr/obj/bin/rdtsc_loop
rr: Saving execution to trace directory `/home/roc/.local/share/rr/rdtsc_loop-18'.
EXIT-SUCCESS
real    0m7.757s
user    0m12.862s
sys     0m3.769s
FYI, without rr:
[roc@localhost rr]$ time ~/rr/obj/bin/rdtsc_loop
EXIT-SUCCESS
real    0m0.063s
user    0m0.060s
sys     0m0.003s
=> Implement syscall buffering for RDTSC

CMakeLists.txt, src/Monkeypatcher.cc, src/Monkeypatcher.h, src/preload/syscall_hook.S, src/preload/syscallbuf.c
The syscallbuf code itself is fine but the signal handling is still bad... In the mean time, this should make it easier to rebase in the future....
Note that I disabled a compile time error on aarch64 that was just added for `rdtsc_recording_only` since it's not used on non-x86.
=> Cherry pick some refactoring for aarch64 syscallbuf

src/PerfCounters.cc, src/PerfCounters.h, src/PerfCounters_aarch64.h, src/util.cc
Hardware tested is a snapdragon 865 with cortex-a77 and cortex-a55 (do note that the linaro rb5 kernel has CONFIG_CHECKPOINT_RESTORE disabled so a custom kernel is needed). Other cores added are based on the technical reference manual.
As noted in the comment, I don't think cortex-a55 contains any usable counters so when running on a big.LITTLE system with cortex-a55, we'll only run on the big cores. This shouldn't be a problem from cortex-a510 on anymore (SVE would be a problem though....)
The skid size is based on observation in the test (I saw up to ~3-4000 so I give it twice that to be safe...)
This almost reaches test passing parity as an M1 system. @Keno, do you have your patch for interrupt on the LL/SC counter available somewhere? I'm seeing related failure from the sysconf_conf …
=> Add support for a few more consumer ARM cores

src/RecordSession.cc, src/Task.cc
Single stepping of an aborted syscall will cause us to go back to
right before the syscall instruction on aarch64. Make sure the single step code
can handle this during recording.
Also make sure that the trace records that the signal will also be delivered
before the syscall instruction since the same pc unwinding happens during replay
as well.
I'm 90% sure I understand what's happening in the failed tests that this fixes and I'm reasonably confident that I'm using the right function to check for these conditions.
I'm less sure how this interacts with normal (unpatched) syscalls and what's the best way to fix the issue....
=> Handle single step of syscall restart on aarch64

src/RecordTask.cc
Similar to the use of original_syscallno for x86, the arg1 may also be overwrites
at this point when the syscall got interrupted.
=> Use the correct arg1 when checking for syscall restart

src/AddressSpace.h, src/ElfReader.cc, src/ElfReader.h, src/GdbServer.cc, src/TraceStream.cc, src/TraceTaskEvent.h, src/kernel_abi.h, src/record_syscall.cc, src/replay_syscall.cc, src/rr_trace.capnp
bionic doesn't use the glibc linker and it doesn't follow the same naming convention. This seemed like a good opportunity to bite the bullet and use PT_INTERP here. This is complicated slightly by the fact that the GdbServer can also be invoked during _recording_ by the emergency debugger if rr asserts. In practice the emergency debugger won't use --serve-files so it shouldn't matter, but it's easy enough to put the interpreter name/base address on AddressSpace, which is the natural place to smuggle this information from the task exec event to GdbServer, in both recording and replay.
=> Use PT_INTERP to find the dynamic linker/program interpreter and record that information in the trace, for later use by --serve-files.

src/PerfCounters_aarch64.h
Allow **single** PMU type to use RAW event, not **zero** PMU types...
Typo from #3265
This is related to the current CI failure on aarch64 since it broke the PMU detection on neoverse-n1 when there's no sysfs.
@DilumAluthge @Keno It seems that sysfs isn't available/accessible on CI. I added a command that print out the warning and it seems that the reading of sysfs for CPUID and PMU types both failed. https://buildkite.com/julialang/rr/builds/674#0181787e-8097-44f0-ba1d-349522b98b87/395-2280
=> Fix PMU count check

src/test/sigrt.c
To make sure that the GDB reverse-finish stops properly.
This fixes the reverse_step_signal test.
Wasted an hour tracing through gdb before realizing that the hint is right in the test itself ....................
=> Manually make the tgkill syscall in test on aarch64

src/PerfCounters_aarch64.h
They are different from M1 for some reason. Everything else seems to work fine.
=> Add part numbers for M1 Pro

src/ReplaySession.cc
`perform_interrupted_syscall` uses the original syscall number (presumably for x86) so we need to set it correctly on aarch64.
=> Apply syscall entry before restarting interrupted syscall

src/AutoRemoteSyscalls.cc, src/RecordTask.cc, src/Task.cc, src/Task.h
Especially in the verifier.
This fixes the intermittent test failure in `unexpected_exit_pid_ns` on aarch64 where previously an unexpected exit is first noticed by the verifier and subsequently asserts in `enter_syscall` since it can't handle exited process. The signal status verifier was also not able to handle this after the memory verification passed.
I didn't check if any the other callers should receive the same treatment but for now I've made this optional and the return value is consistent with that of `exit_syscall`.
=> Be more robust against unexpected exit

src/test/nested_detach.run, src/test/nested_detach_kill.run, src/test/util.sh
By waiting for the incomplete file to disappear
This is more likely to happen on asymmetric cores with very different performance.
On my M1 MBA, this happens ~20 times for `nested_detach` in 80 runs of the full test suite. This can also be easily reproduced by adding a sleep in `simple.c` or in `TraceStream.cc` before `incomplete` is renamed to `version`.
=> Wait for detached nested record to finish before replaying it

src/preload/overrides.c, src/preload/syscallbuf.c
These were causing the signal handler to defer signal delivery
when it shouldn't have.
These were probably more likely to happen on aarch64 since the counter
we use counts all the branches and not just conditional ones.
These causes test failure in `exit_race` about 2-3% of the time.
=> Fix two cases of unexpected entrance/exit to syscallbuf code range

CMakeLists.txt, src/AutoRemoteSyscalls.cc, src/Task.cc, src/Task.h, src/test/futex_restart_clone.c
In #3148, I fixed #3141 by having AutoRemoteSyscalls perform an extra
PTRACE_INTERRUPT when restoring state to a task that has may-restart
register state. However, I failed to appreciate that this would cause
extra GROUP-STOP-SIGTRAP stops that need to be ignored. Fortunately,
we do already have a solution to this, since we sometimes use
PTRACE_INTERRUPT during `wait()`. Simply factor out that mechanism
and make sure to use it here.
=> Fix #3289 - Spurious PTRACE_INTERRUPT stops not ignored

src/test/util.sh
From a quick test https://buildkite.com/julialang/rr/builds/724#0181ad32-977e-4124-b5df-5eb17b7c122a/362-368 it seems that the file `pidof` is available on the file system and it is in the PATH. It is in fact a symlink to `/sbin/killall5` which agrees with the content of the package I downloaded and is probably just a arg0 trick. However, it seems that `/sbin` does not contain `killall5` which is why the command cannot be found.
This can probably be fixed properly on the CI. In the mean time, this version should work well enough to get the relevant tests to pass.
=> Add a fallback implementation of pidof for the aarch64 CI

src/Task.h, src/record_signal.cc
Also add comment about the slightly different logic used on aarch64 in is_safe_to_deliver_signal.
Went back and forth on the correct check for this a few time and the final version is actually quite clean... With the test pass after #3293 I'm fairly confident about this logic now.
=> Tweak syscall PC check on aarch64 in signal stop

src/RecordSession.cc, src/RecordTask.cc, src/Task.cc, src/Task.h
There are a few related issues being fixed here. Fixing some of these exposes other ones so I'm putting them in the same PR. I've got a few complete test pass on both M1 and Cortex-A77 with this so I think this is reasonably complete. The issues that I've seen includes,
1. Recording of completed untraced syscall.
We had no way to recover original x0 value AFAICT and the replay isn't happy about this. Fix by just ignoring any untraced syscalls.
2. Getting killed after the syscall is already started but before we got a syscall exit stop.
Make sure `orig_x0` is always updated and use that for `x0` in the record.
3. In `ptrace_singlestep` test, we were recording two entry of the same syscall, which I assume is related to ptrace/SIGCHLD handling
Add a check to see if the entry is already …
=> Fix recording of syscall entry for killed processes on aarch64

src/test/record_replay.run
This is getting very close to timeout on the M1 E core (>250s)
when running alone and sometimes actually time out in parallel test run.
=> Increase timeout for record_replay test

src/Flags.h, src/main.cc, src/util.cc
This was requested by the Julia CI team for situations where rr
itself crashes on Julia CI. The CI system uses a pty, so rr thinks
the terminal is interactive, but in reality it isn't, so this causes
the build to time our rather than triggering the usual failure handling.
cc @staticfloat @DilumAluthge
=> Add a command line option to override interactivity detection

src/GdbServer.cc, src/ReplayTimeline.cc, src/ReplayTimeline.h
The current event might be a syscallbuf reset if the syscallbuf
is enabled. What we're really interested in is what kind of signal
we're about to report to GDB, which can be found in break_status,
so pass that to stop_filter instead.
Fixes gdb_qpasssignals on aarch64 CI.
=> Use break_status rather than replay event in stop filter

src/test/early_error.c
On x86, the syscall we expect to veto here is the prctl that sets
PR_SET_TSC (and thus happens before the SIGSTOP that indicates
completion of the intial setup code). However, on aarch64 this
prctl doesn't exist. Depending on ordering of events, we
somtimes see the subsequent prctl which sets up the seccomp
filter and that happens to make the test work, but this is
unreliable and can lead to a weird situation where that prctl
got veto'd and thus rr's usual seccomp filter never got installed,
confusing rr down the line.
Fix all of that by switching the veto'd syscall to be the kill(SIGSTOP)
instead, which is present on all architectures.
=> Try fixing early_error test

src/RecordSession.cc
I changed this in #3019, but I'm not sure why. The commit message doesn't make a mention of it
and the test passes without. I also don't see why the new code would have affected the task_map,
so this is definitely just a behavior change. Let's undo this and if something breaks downstream,
let's make sure to add a test for it, but in the meantime, this fixes #3310 (I believe).
=> Wait for detached processes again

src/AutoRemoteSyscalls.cc, src/RecordSession.cc, src/RecordTask.cc, src/RecordTask.h, src/Task.cc, src/Task.h
What appears to be happening in #3312 is that the daemon child is
being killed at the end of the recording session, but we don't
notice until a `set_sigmask` we're performing because the child
has stashed signals. In theory there isn't really anything problematic
with the child dying here, so just improve the robustness of set_sigmask
against this occurrence, which should hopefully fix #3312.
=> More robustness for process dying before set_sigmask

src/test/x86/rdtsc.c, src/test/x86/step_rdtsc.py
The test was depending on gdb setting the breakpoint for the my_rdtsc
function at the first non-prologue instruction (and expecting that to
be the rdtsc). However, some compilers emit DWARF info that causes
gdb to set a breakpoint at the first instruction of the prologue
instead. Work around that by setting a label in the place we want
and using that for the breakpoints.
Fixes a locally observed failure.
=> Fix compiler-dependent failure of step_rdtsc test

src/PerfCounters.cc, src/PerfCounters_aarch64.h
Tested on Amazon Graviton3 (V1). N2 support is based on known perf counter info and isn't tested on hardware.
SVE (registers and first/non fault load) not yet supported.
=> Add initial Neoverse V1 and N2 support

src/preload/overrides.c
=> Print a useful error message if we can't interpose libstdc++ symbols correctly because the library was likely loaded with RTLD_LOCAL.

src/preload/syscallbuf.c, src/test/sock_names_opts.c
The syscallbuf would crash if `ptr` was NULL, e.g. because the fd
was traced by a file monitor. Fix that by moving the input memcpy
to the correct place and add a simple test.
=> Fix syscallbuf for getsockopt

src/test/tgkill.c, src/test/util.h
applying 7044c5c6a8e64c737ba3cdb97187ff5c406e5162 to this file to not call the system function which is only available in newer glibc, but to always use the syscall instead
that file did not compile with
> g++ (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
> GNU C Library (GNU libc) stable release version 2.28.
bailing out with
~~~
./rr/src/test/futex_restart_clone.c: In function 'child':
./rr/src/test/futex_restart_clone.c:23:3: error: implicit declaration of function 'tgkill'; did you mean 'kill'? [-Werror=implicit-function-declaration]
tgkill(parent_tid, parent_tid, SIGUSR1);
^~~~~~
kill
~~~
before, but does afterwards.
=> fix compile with old glibc

src/preload/preload_interface.h
The Android NDK contains `#define __unused __attribute__((__unused__))`
in `sys/cdefs.h`, so it can't be used as an identifier.
=> Fix build failure on Android

src/RecordCommand.cc, src/RecordSession.cc, src/RecordSession.h
Following up the discussion from #3296, this is a less intrusive approach to force enable TSan.
=> Force enable TSan support with a flag

src/kernel_abi.h, src/kernel_supplement.h
Older libcs may lack references to compressed ELF sections. Add
the requisite constants and skip verification for structs that
may not be defined.
=> Fix build on older libcs

src/DiversionSession.cc
As suggested in https://github.com/rr-debugger/rr/issues/3343
=> suppress some syscalls in diversion sessions which will cause Gdb to exit

src/PerfCounters.cc
Empirical testing shows this is necessary on an i9-12900K.
=> Raise the skid count on Alder Lake slightly.

src/PerfCounters_x86.h
This small PR allows me to run `rr` on a very new Ryzen 6000 series Laptop -- specifically Ryzen 6800U.  
I, of course, needed to follow [tips](https://github.com/rr-debugger/rr/wiki/Zen) in the wiki to disable the SpecLockMap interfering optimization. FYI I had 27 test failures. I'll open a separate issue on those.
BTW, I've assumed that `cpu_type == 0x40f40` represents Rembrandt in the PR. It's quite possible there are other `cpu_types` which also represent Rembrandt -- in which case future PRs can correct the C++ comment that I added.
=> Add support for Rembrandt (Zen 3+)

src/RecordTask.cc, src/preload/preload_interface.h
This used to be used in the interception of _SC_NPROCESSORS_{CONF, ONLN}.
However, we are no longer intercepting these queries. Instead, we are
emulating the underlying OS featuers that glibc reads these values from.
As a result, the `globals.pretend_num_cores` field is no longer used.
Remove it for cleanup. Note that there is no corresponding replay
code for this field, so no compatibility code is required.
=> rm unused globals.pretend_num_cores

CMakeLists.txt, src/AddressSpace.cc, src/replay_syscall.cc, src/test/madvise_fracture_flags.c, src/test/madvise_fracture_flags.run, src/test/syscall_bp.c, src/test/util.h, src/test/util.sh
This is an incomplete PR, because although the test case passes as included (with replay -a), it does not pass when running from the debugger prompt. I do not know what the difference between the two scenarios is. rr's logs are identical, there are no spurious debugger traps or anything. I did trace the kernel and there is a minor difference, but it is not particularly helpful. Anyway, I'll look at this some more, but if anybody has bright ideas what difference running with GDB attached vs not makes, I'm all ears.
The core issue I'm trying to fix here is the following, when replaying the included test case, which emulates some (questionably sound) asan behavior:
```
[FATAL src/AutoRemoteSyscalls.cc:734:check_syscall_result()] 
(task 1144611 (rec:1088200) at time 1206)
-> Assertion `false' …
```
=> Fix madvise fracture during replay

src/Monkeypatcher.cc
clang 14 gives me this build error for rr trunk:
```
src/Monkeypatcher.cc:749:77: error: 'static_assert' with no message is a C++17 extension [-Werror,-Wc++17-extensions]
static_assert(ExtendedJumpPatch::size < FakeSyscallExtendedJumpPatch::size);
```
This patch fixes this by promoting the static_assert's code-comment to be its actual assertion-message instead.
=> Add message to static_assert in Monkeypatcher.cc to fix clang build error

src/test-monitor/test-monitor.cc
In GCC 12, ctime is no longer included indirectly, and needs to be
included explicitly (for time()).
See https://www.gnu.org/software/gcc/gcc-12/porting_to.html for
details.
Signed-off-by: Stephen Kitt <steve@sk2.org>
=> Include ctime explicitly

src/RecordTask.cc
If the process is dead, there's no point trying to set its sigmask. We'll notice the process died next time we try to do something with it, so there's nothing to do here other than to ignore the ptrace failure.
Should address CI failure seen in [1].
[1] https://buildkite.com/julialang/rr/builds/860#018314dd-a7ee-4dd4-a133-109c7ee0ada1
=> Use ptrace_if_alive rather than xptrace for PTRACE_SETSIGMASK

src/GdbConnection.cc
Without this, we were a bit surprised to find rr segfaulting when we started building/installing it in a new way (and bungled the placement of those xml files).  The DEBUG_ASSERT check only happens in debug builds of course, so it cannot catch this mis-installation issue.
=> Minor change to error if the expected share/rr/*.xml file is missing.

src/kernel_abi.h
Got this error (when uncommented):
```
src/kernel_abi.cc:68:55: error: type/value mismatch at argument 2 in template parameter list for ‘template<rr::SupportedArch a, class system_type, class rr_type> struct rr::Verifier’
src/kernel_abi.cc:68:55: note:   expected a type, got ‘statx’
```
=> Use the explicit variant, because statx is also known as function name.

src/Task.cc, src/Task.h, src/record_syscall.cc
=> Rather than guessing where the BSS pages are, use /proc/<pid>/pagemap to see which pages the kernel modified.

.android/cloudbuild.yaml
Forks shouldn't be attempting to push their artifacts to the upstream bucket. Make this location configurable in the cloud build config so each repository can have their own storage location.
This does also change the storage layout to avoid clobbering stored artifacts with each build. The output path as well as the bucket name could probably be made configurable instead if that behavior should be kept.
=> Make the artifact storage location configurable.

src/PerfCounters.cc, src/PerfCounters_x86.h
This seems to address this issue: https://github.com/rr-debugger/rr/issues/3397
I am not sure about the values that I added to pmu_configs, but it seems reasonable? Sorry if I've missed anything as well. I apologize as I would run the tests, but apparently WSL still doesnt work :( (error is: `[FATAL src/PerfCounters.cc:308:start_counter()] Unable to open performance counter with 'perf_event_open'; are hardware perf events available? See https://github.com/rr-debugger/rr/wiki/Will-rr-work-on-my-system`)
=> Add the IntelRaptorLake CpuMicroarch

src/test/util.h
The mount_ns_exec test needs it to call the mount function.
=> test: Include <sys/mount.h> in util.h

src/util.cc
This mainly fixes #3415 and extends support for "current directory" to format a la `_RR_TRACE_DIR=mydir`. The `ensure_dir()` with directory creation code and the `access()` call commented out passes the following testing combinations for me:
```
ensure_dir(std::string("/tmp/foo/bin///"), "", 0777);
ensure_dir(std::string("/tmp/"), "", 0777);
ensure_dir(std::string("/tmp/bar"), "", 0777);
ensure_dir(std::string("/boo/bar"), "", 0777);
ensure_dir(std::string("/"), "", 0777);
ensure_dir(std::string("///"), "", 0777);
ensure_dir(std::string("./foo"), "", 0777);
ensure_dir(std::string("./"), "", 0777);
ensure_dir(std::string("."), "", 0777);
ensure_dir(std::string("foo"), "", 0777);
ensure_dir(std::string("foo/bar"), "", 0777);
```
Fixes: https://github.com/rr-debugger/rr/issues/3415
=> Improve handling of _RR_TRACE_DIR variable

src/RecordSession.cc
=> Add environment GIO_USE_VFS to avoid diversion due to mapped files.

CMakeLists.txt, src/record_syscall.cc, src/test/ioctl_br.c
These are rather-undocumented syscalls related to bridge configuration, which are used in Connman. Fixes #3421
=> Implement ioctl(SIOCGIFBR) syscalls

src/ReplayTask.h
This fixes the following clang warning (treated as a build error):
```
src/ReplayTask.h:91:16: error: 'post_vm_clone' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
```
This warning only cropped up recently; I'm guessing it was from https://github.com/rr-debugger/rr/commit/7361bbfe30162f36dd6c0019c511ef4a19fd54f0 which added the first mention of `override` in this header, which is what made this already-implicitly-overriding declaration "inconsistent" (per the clang warning).
=> Annotate ReplayTask::post_vm_clone with `override`

src/preload/syscallbuf.c
Fixes build in scenarios when it isn't defined.
=> Guard for SYS_rseq

src/record_syscall.cc
A git bisect leads to commit 1cf13c629.
Also a build shows this warning:
```
src/record_syscall.cc:5648:25: warning: left shift count >= width of type [-Wshift-count-overflow]
5648 |         if (pfn & ((1UL << 63) | (1UL << 62))) {
```
With this patch a 32bit and a 64bit build succeeds all tests for me.
(Except detach_sigkill because of issue 3385.)
=> Fix the force32bit build by using a longlong constant.

src/test/x86/rdtsc_loop2.run
Currently with skip_if_test_32_bit it is just skipped with a 64-bit rr running the 32-bit test.
This test `x86/rdtsc_loop2` finishes for me just in time near 120 seconds,
when running at bare metal and below a 64-bit kernel with 32-bit rr.
But it fails when running inside a qemu VM running a 32-bit kernel - there it needs near 240 seconds.
So this patch adds the `skip_if_rr_32_bit` to avoid running below a 32-bit rr.
Or would it be better to change `skip_if_test_32_bit` to match this case too?
Because `skip_if_rr_32_bit` just checks bitness based at `$bitness`, which seems not set for a 32-bit rr.
=> Skip rdtsc_loop with a 32-bit rr.

src/test/invalid_jump.c
The function invalid_jump_here is initialized with zeros which get seen as two `add %al,(%eax)` instructions.
Unfortunately $eax contains the function pointer itself, and because for some reason this function is mapped to rw memory running at an i386 kernel, this instructions succeed. Therefore the test fails as the reverse-stepi just stays inside invalid_jump_here.
This was at least observed inside a i386 qemu VM with a Ryzen host, both running Debian testing.
The patch does three things:
* change that `add %al,(%eax)` into `add %al,(%ecx)`
* attempts to clear register ecx right before the invalid call
* changes the function storage to const (that would also fix the issue alone already)
Also, I am uncertain if this change would still work with arm64.
This is an example gdb session to …
=> Fix invalid_jump running at i386 kernel.

src/RecordSession.cc
In 64 bit mode, ASAN takes two additional pages to store RegionInfo structs (via the AdditionalSize() method). Account for that here so we don't hand them out.
=> Reserve two more pages for ASAN.

CMakeLists.txt
Building with cmake 3.10 fails with this error
CMake Error at CMakeLists.txt:341 (add_compile_definitions):
Unknown CMake command "add_compile_definitions".
add_compile_definitions was added in 3.12, which should be reflected in the cmake_minimum_version requirement
=> Require cmake that has add_compile_definitions

src/AutoRemoteSyscalls.cc
Aid debugging of the `Syscall mmap failed with errno ENOMEM` issue.
=> Add parameters to failure logging of mmap in AutoRemoteSyscalls.

.buildkite/pipeline.yml
The script that schedules the actual CI jobs is currently required to run on x86_64. When the x86_64 queues are backed up (like today), it would be nice to be able to run this on aarch64, to at least get some indication of whether the PR works. Try this and see if everything just magically works.
=> CI: Try relaxing architecture restriction on generator script

.buildkite/lib/generate.jl
By default, retry is only enabled for failed builds. When investigating intermittent failures, it can be useful to retry successful builds also, so enable that in the UI.
https://buildkite.com/docs/pipelines/command-step#retry-attributes-manual-retry-attributes
cc @staticfloat @DilumAluthge
=> CI: Allow manual retry of succesful builds

src/TraceeAttentionSet.cc
This fixes issue #3472. In the detach tests, it is possible for run_initial_child to happen while the TraceeAttentionSet thread is processing a SIGCHLD and is holding the attention_set_lock. run_initial_child then queries `TraceeAttentionSet::get_original_sigmask`, which attempts to acquire this lock, resulting in a deadlock.
However, the locking here is unnecessary. The `attention_set` pointer is only ever written from the main thread and in fact only written once prior to the creation of the child thread. As such, neither locking nor memory barriers are required for access to the `attention_set` pointer. The contents of the `attention_set` itself do still need to be protected by the lock, but `TraceeAttentionSet::get_original_sigmask` does not look at it.
=> Fix deadlock in TraceeAttentionSet

CMakeLists.txt, src/RecordCommand.cc, src/RecordSession.cc, src/Task.cc, src/test/nested_detach_kill_stuck.c, src/test/nested_detach_kill_stuck.run
Fix https://github.com/rr-debugger/rr/issues/3464
- Allow `result.code == WAIT_NO_STATUS` when waiting for exit and retry
since we could have gotten EINTR'd (in this case by the SIGTERM)
- Increase the timeout for the kernel and rr to cleanup after shooting down
the tracees to 5s. I'm still not convinced this is necessarily sufficient for
huge tracees under load, but 1s was observably insufficient, so set it to 5 for
now and we can increase further if required. After 1s, it will print the user to
reassure that something is happening still and the wait is deliberate.
- Once a detached tracee has been waited for, make sure to actually delete it,
otherwise we might get confused trying to wait for it later.
=> Improve robustness of SIGTERM with detached tasks

src/AddressSpace.cc, src/PackCommand.cc, src/Task.cc
=> Avoid some warnings about possible uses of unintialized variables.

src/Session.cc
This last byte gets written in the next line anyway.
```c++
.../rr/src/Session.cc: In static member function ‘static const rr::AddressSpace::Mapping& rr::Session::steal_mapping(rr::AutoRemoteSyscalls&, const rr::AddressSpace::Mapping&, rr::MonitoredSharedMemory::shr_ptr)’:
.../rr/src/Session.cc:579:10: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 4056 equals destination size [-Wstringop-truncation]
579 |   strncpy(name, m.map.fsname().c_str(), sizeof(name));
|   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Use one byte less in strncpy to avoid warning.

src/test/nested_detach.run, src/test/nested_detach_kill.run, src/test/nested_detach_kill_stuck.run, src/test/nested_detach_wait.run
This got visible for example when downloading buildkite artifacts.
Currently workdir gets set to the inner recording directory, therefore just the inner directory get removed.
=> Cleanup outer temporary directory in nested_detach tests on success.

src/test/sioc.c
Error message:
SIOCGIFADDR(ret:-1): eth3 SIOCGIFDSTADDR(ret:-1): eth3 FAILED at src/test/sioc.c:123: !(0 == ret) errno:99 (Cannot assign requested address)
Fault shows up in CI, just when run at exclusive-amdci1.0:
https://buildkite.com/julialang/rr/builds/1061
https://buildkite.com/julialang/rr/builds/1063
https://buildkite.com/julialang/rr/builds/1065
https://buildkite.com/julialang/rr/builds/1084
https://buildkite.com/julialang/rr/builds/1085
https://buildkite.com/julialang/rr/builds/1086
[https://buildkite.com/julialang/rr/builds/1087](https://buildkite.com/julialang/rr/builds/1087#01877f2a-e02d-4924-8e81-6fc150c3a7b1/3905-6044)
I guess this is related to a different configuration of exclusive-amdci1.0,
but I have no way to reproduce it and threfore cannot test this change.
What do …
=> Allow SIOCGIFDSTADDR in sioc tests to return EADDRNOTAVAIL.

src/AutoRemoteSyscalls.cc, src/TraceeAttentionSet.cc
clang version 16.0.0 (Fedora 16.0.0-2.fc38)
```
src/TraceeAttentionSet.cc:71:12: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
result = move(*attention_set);
^
std::
src/AutoRemoteSyscalls.cc:674:10: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
return move(fds[0]);
^
std::
```
=> Change move() to std::move() as clang++ 16 on fc38 errors during compilation

src/PerfCounters_aarch64.h
This adds support for arch ARM Cortex A78C and ARM Cortex X1C.
They are the ARM Cortex A78 and X1 variants used by Snapdragon 8cx Gen 3,
and the differences are small enough that I don't think a new arch type is needed.
The relevant manuals can be found here.
https://developer.arm.com/documentation/102226/0002/Debug-descriptions/Performance-Monitoring-Unit/PMU-events?lang=en
https://developer.arm.com/documentation/101968/0002/Debug-descriptions/Performance-Monitoring-Unit/PMU-events?lang=en
https://developer.arm.com/documentation/101968/0002/Register-descriptions/AArch64-system-registers/MIDR-EL1--Main-ID-Register--EL1?lang=en
Tested on Thinkpad X13s.
=> Add Snapdragon 8cx Gen 3 support

src/TraceInfoCommand.cc
Add the path of the entry program to the json returned by `rr traceinfo`, this will allow consumers to know exactly which program is being debugged as part of a trace, which may be useful for tools that use another debugger on top of RR.
Fixes #3507
=> Add the entry program file to 'rr traceinfo'

CMakeLists.txt, src/AddressSpace.h, src/Task.cc, src/Task.h, src/record_syscall.cc, src/test/detach_huge_mmap.c
ASan creates a "shadow" of the used memory.
This is done in a mapping of around 20 TB address space, but most of it is not yet used.
This patch aids an ASan-enabled rr build in following tests:
```
nested_detach
nested_detach_kill
nested_detach_kill_stuck
nested_detach_wait
nested_release
```
Avoids error message:
```
ERROR: AddressSanitizer: requested allocation size 0x20000000000 (0x20000001000 after adjustments for alignment, red zones etc.) exceeds maximum supported size of 0x10000000000 (thread T0)
```
=> ASan: Copy just used pages from ANONYMOUS mappings.

src/AddressSpace.cc
Looks like `LOG(error)` aborts rr. Therefore the information about the mappings gets not written out.
Example without this patch:
https://buildkite.com/julialang/rr/builds/1197#0187b750-3714-416f-aa7f-59d2aca36716/2342-2421
```
24/1341 Test  #902: cont_race ..............................................***Failed  Error regular expression found in output. Regex=[FAILED]  4.84 sec
source_dir/src/test/util.sh: line 254: 26153 Aborted                 _RR_TRACE_DIR="$workdir" test-monitor $TIMEOUT record.err $RR_EXE $GLOBAL_OPTIONS record $LIB_ARG $RECORD_ARGS "$exe" $exeargs > record.out 2> record.err
Test 'cont_race' FAILED: : error during recording:
--------------------------------------------------
[ERROR src/AddressSpace.cc:1532:assert_segments_match()] cached mmap:
=== Start rr …
```
=> Fix assert_segments_match to really output information.

.android/Dockerfile, .android/README.md, .android/build.sh, .github/workflows/build.yml, CMakeLists.txt
Remove the "works on my machine" guesswork. This keeps all the Android parts of the build in build.sh, but moves all the host dependencies (including the capnproto fetch) into the Dockerfile.
This cleans up some of the header/library directory handling as well, which was necessary for making the build script work when the host and target builds are separate (CAPNP_CFLAGS doesn't actually exist, so the build was previously finding the host's includes by coincidence?)
@khuey wdyt? This was a byproduct of me trying to debug https://github.com/rr-debugger/rr/pull/3432. It's helpful to me as someone that doesn't actually know much about building rr, but if it's just going to be in your way we should probably just close this :)
(in any case, it's not ready to submit yet as the Android CI script …
=> Restructure Android build with a Dockerfile.

src/GdbCommandHandler.cc
Force gdb to re-acquire state by flushing the register cache; because the `back`/`forward` command never tells GDB that something has actually happened.
=> Fixes the problem of non-updated gdb state after back/forward

src/GdbServer.cc
When debugging a (truly) remote debug session using gdb command; `gdb -ex "target extended-remote host:port"` gdb will complain about file not found, example:
```
Reading /home/cx/.local/share/rr/testapp-2/mmap_clone_4_testapp from remote target... 
warning: File transfers from remote targets can be slow. Use "set sysroot" to access files locally instead. 
warning: "target:/home/cx/.local/share/rr/testapp-2/mmap_clone_4_testapp": could not open as an executable file: No such file or directory. 
Reading /home/cx/.local/share/rr/testapp-2/mmap_clone_4_testapp from remote target... 
warning: `target:/home/cx/.local/share/rr/testapp-2/mmap_clone_4_testapp': can't open to read symbols: No such file or directory.
```
After going through GdbConnection code it does reply with a -1 not found.
The …
=> Fixes bug of not sending over symbols in (true) remote session

src/GdbServer.cc, src/test/seekticks.py
Before this, `seek-ticks` would go to an incorrect tick if the current event and target tick event are the same, easiest reproducible by running `seek-ticks` with the same argument twice (where there isn't an event on exactly that tick).
This patch passes manual testing seeking back, forward, over events or not, and on tick numbers immediately before/after an event.
=> Fix seek-ticks when already at the target event

.buildkite/lib/generate.jl
This could avoid occupying CI infrastructure
when all tests fail like here:
https://buildkite.com/julialang/rr/builds/1221#01882e04-ac8c-4566-94fd-357bc3466d5b
=> buildkite: Skip the tests when a very simple rr run already fails.

src/PerfCounters.cc, src/PerfCounters_x86.h
This adds support for Intel Xeon 4th gen codename SapphireRapids. Let me know if there are any issues.
=> support for Intel SapphireRapid

src/PerfCounters.cc, src/PerfCounters_aarch64.h, src/Registers.cc, src/Registers.h
These changes allow `rr` to _mostly_ work on asahi linux on the M2 chip (we currently support only M1).
<details>
<summary>95% tests passed, 65 tests failed out of 1345</summary>
```
95% tests passed, 65 tests failed out of 1345
Total Test time (real) = 5502.27 sec
The following tests FAILED:
228 - grandchild_threads_main_running (Failed)
229 - grandchild_threads_main_running-no-syscallbuf (Failed)
230 - grandchild_threads_thread_running (Failed)
231 - grandchild_threads_thread_running-no-syscallbuf (Failed)
294 - kill_ptracee (Failed)
295 - kill_ptracee-no-syscallbuf (Failed)
412 - no_mask_timeslice (Failed)
413 - no_mask_timeslice-no-syscallbuf (Failed)
433 - pid_ns_kill_child-no-syscallbuf (Failed)
442 - pid_ns_reap (Failed)
488 - ptrace_attach_running (Failed)
489 - …
```
=> [WIP] rr support on M2

src/PerfCounters_aarch64.h
Fixes https://github.com/rr-debugger/rr/issues/3550
=> Add missing M1 part numbers to PerfCounters_aarch64.h

src/test/large_file.run
Because 32-bit rr is compiled without `-D_FILE_OFFSET_BITS=64`. Therefore the open of the large file fails with EOVERFLOW.
[FATAL src/record_syscall.cc:5531:process_execve() errno: EOVERFLOW]
(task 2019470 (rec:2019470) at time 14)
-> Assertion `fd.is_open()' failed to hold.
------
My attempts to either use `-D_FILE_OFFSET_BITS=64` or open64/stat64 were leading to a row of changes involving size_t/off_t or struct stat, which I guess are not desired for the fading 32-bit architecture?
=> Disable test large_file on 32-bit rr.

CMakeLists.txt, src/LsCommand.cc, src/MvCommand.cc, src/RmCommand.cc, src/TraceStream.cc, src/TraceStream.h, src/util.cc, src/util.h
As discussed in #1415, this pull request implements `rr rm` and `rr mv` commands to manage traces.
See #3558 for a similar pull request using `std::filesystem` that was closed because that library caused build errors.
=> Add rr commands to remove and move traces

CMakeLists.txt, src/Monkeypatcher.cc, src/test/x86/rdtsc_interfering.c, src/test/x86/rdtsc_interfering.run
The interfering branch check was assuming that the syscall (or rdtsc instruction) is at the start of the patch region. As a result, it was incorrectly ignoring interfering branches for
PATCH_SYSCALL_INSTRUCTION_IS_LAST hooks (as well as detecting interfering branches that actually do not interfere).
=> Fix detection of interfering branches for syscall at end of patch

src/Monkeypatcher.cc, src/preload/preload_interface.h, src/preload/syscall_hook.S, src/preload/syscallbuf.c, src/test/x86/rdtsc_interfering.c
I was looking some disassembly that looked like this:
```
0x00007f5d7d0e7ffd <+29>:	48 89 7c 24 10	mov    %rdi,0x10(%rsp)
0x00007f5d7d0e8002 <+34>:	4c 8d 64 24 20	lea    0x20(%rsp),%r12
0x00007f5d7d0e8007 <+39>:	eb 37	jmp    0x7f5d7d0e8040 <_ZN5tracy8Profiler14CalibrateDelayEv+96>
0x00007f5d7d0e8009 <+41>:	0f 1f 80 00 00 00 00	nopl   0x0(%rax)
0x00007f5d7d0e8010 <+48>:	e9 03 8b 1a 3c	jmpq   0x7f5db9290b18
0x00007f5d7d0e8015 <+53>:	90	nop
0x00007f5d7d0e8016 <+54>:	4c 8d 2c 02	lea    (%rdx,%rax,1),%r13
0x00007f5d7d0e801a <+58>:	e8 31 60 fc ff	callq  0x7f5d7d0ae050 <_ZN5tracy28HardwareSupportsInvariantTSCEv@plt>
0x00007f5d7d0e801f <+63>:	84 c0	test   %al,%al
0x00007f5d7d0e8021 <+65>:	74 4a	je     0x7f5d7d0e806d <_ZN5tracy8Profiler14CalibrateDelayEv+141>
=> 0x00007f5d7d0e8023 <+67>:	0f 31 …
```
=> Create a known-patchable sequence for rdtsc trapping

src/test/util.sh
The testsuite should run on any system with different settings, so create a reasonable default for all tests.
fixes #3545
=> testsuite: add LC_ALL default to util.sh

CMakeLists.txt
-fno-integrated-as tells Clang to use whatever "as" happens to be. For an Android build that will end up being whatever /usr/bin/as is, and whatever it is, it's the wrong assembler for Android, because Android only supports the Clang assembler.
=> Do not use -fno-integrated-as for Android.

src/test/vfork_done.c
for test vfork_done, copied from test ptrace_kill_grandtracee (34a9f5d8cc3a95899b1a2ce3a98664406e3972f0)
=> fix compilation without PTRACE_EVENT_STOP

src/counters-test/counters.cc
I haven't actually checked the logic for what these pseudo-bools mean, but seeing as how `PMU_TICKS_RCB` is a constant (that isn't 0), comparing it to `not 0` will always yield `true`.
foo & bar != baz, will evaluate bar != baz, then foo & ...
This can be verified by building with clang which will catch this error (`-Wparentheses`)
=> Fixes precedence bug in counters-test/counters.cc

src/AddressSpace.cc
=> Limit address space in 32-bit rr to avoid interfering with kernel space.

src/test/unicode.run, src/test/util.sh
The current used en_US.UTF-8 is not guaranteed to be available in e.g. Debian, which has for this reason C-UTF-8.
The Debian downstream maintainer has for this a patch in the [rr sources](https://sources.debian.org/src/rr/5.7.0-2/debian/patches/test-locale.patch/).
But this C.UTF-8 seems not to be guaranteed to be available on systems with GNU libc < 2.35, [link](https://unix.stackexchange.com/questions/597962/how-widespread-is-the-c-utf-8-locale).
Therefore this attempt to select an existing UTF-8 locale.
This changes also the default from `LC_ALL=en_US.UTF-8` to `LC_ALL=C`.
See discussion at the end of https://github.com/rr-debugger/rr/issues/3545.
CC: @GitMensch
=> Be more flexible selecting an UTF-8 locale.

CMakeLists.txt, src/GdbServer.cc, src/test/seekticks_threads.c, src/test/seekticks_threads.py, src/test/seekticks_threads.run, src/test/tick0.py, src/test/util.sh
This fixes two bugs:
- `seek-ticks` to a tick exactly on a `SCHED` event goes to the other thread, not the current one (the `>=` → `<` change);
- `seek-ticks` to within the current event skips too far if the next event is for a different `tid`.
Additionally, this extracts the logic for tick→time conversion to a function (first commit doing nothing but that).
=> Another batch of seek-ticks fixes

src/PerfCounters_x86.h, src/counters-test/counters.cc
I've done minimal testing to ensure that this works (using the usual Zen workaround).
This covers (at least) the Ryzen 7840U.
=> amd: Add Phoenix (Zen 4) CPU ID

src/PerfCounters_x86.h
This change addresses error when running on newer Icelake CPU sku:
[FATAL ...] Intel CPU type 0x80660 unknown
$ cat /proc/cpuinfo | grep name | uniq
model name      : Intel Xeon Processor (Icelake)
=> Adding support for Intel Icelake cpu_type 0x80660

.github/workflows/build.yml
Currently this job shows up as "Build", which I think is a little confusing. So this PR renames that job to "Build Android", which is what that job is specifically testing.
=> CI: use a more specific name for the "Build Android" job

src/GdbCommand.cc, src/GdbCommandHandler.cc, src/GdbServer.cc, src/GdbServer.h, src/test/restart_invalid_checkpoint.py, src/test/seekticks.py, src/test/seekticks_threads.py, src/test/x86/explicit_checkpoints.py
This fixes a couple things:
- `delete checkpoint` without an argument reads outside array bounds
- Checkpoints created at the end state, or when the process has finished, cannot be functionally restored, so disallow those
- After a failed `run`, gdb generally doesn't query anything, except `info threads` (perhaps there are more, but I haven't looked). And if rr responds with any threads, things soon break. Perhaps there's a better way to check for/handle this than my introduced `bool failed_restart;`?
=> Various fixes for invalid things

src/record_syscall.cc
rec_process_syscall_arch: when the old brk is the same as new brk avoid writing a zero length mapped region into the trace
=> rec_process_syscall_arch: deal with old_brk == new_brk case

src/GdbServer.cc, src/GdbServer.h
initialize the GdbServer::failed_restart variable in constructors otherwise random values will cause problems
=> initialize the GdbServer::failed_restart variable in constructors

src/RecordTask.cc
This got introduced in 7bd2d4ab2.
=> Fix 32-bit build of RecordTask::try_grow_map.

src/test/transient_fault_replay_all.run
The test uses the `seq` utility, which is most probably 64-bit, and can therefore not be recorded by a 32-bit rr.
=> Skip test transient_fault_replay_all when built with force32bit.

CMakeLists.txt, scripts/rr-gdb-script-host.py, src/ElfReader.cc, src/SourcesCommand.cc
This is relatively straightforward, just ugly. One notable difference in the behavior from gdb is that when multiple paths are provided gdb will try them all in sequence but this code just tries the last one. That works for the use case that's motivating this PR but may cause issues down the line.
I'm reasonably confident I didn't regress anything but there's no automated testing for `rr sources`.
=> Support interposing a (very basic) gdb script that sets debug file paths in the `sources` command.

src/PerfCounters.cc, src/PerfCounters_x86.h
This adds support for Intel Xeon 5th gen codename EmeraldRappids. All tests pass locally.
=> Intel EmeraldRappids Support

src/PerfCounters_x86.h
observed on i7-13700HX. I was able to run a basic real-world debugging job after applying this patch, including reverse execution.
=> Add additional Raptor Lake microarchitecture type

src/StdioMonitor.cc, src/Task.cc, src/Task.h
FrameTime is a long (int64 in the trace) while trace_time() casts it to a u32. Preserve the original type by making the function return type FrameTime.
=> Preserve the type of the trace time in Task::trace_time()

src/PerfCounters_x86.h, src/counters-test/counters.cc
I noticed that it does not support my AMD Ryzen™ 7 8845HS.
(I also ran a `make check` in local environment.)
=> AMD: Add Hawk Point (Zen 4) CPU ID

CMakeLists.txt
This causes ctest to be given direct access to the terminal when using the ninja generator.
=> Set USES_TERMINAL on check/fastcheck custom commands

CMakeLists.txt, src/record_syscall.cc, src/test/memfd_create_efault.c
Hi! I tried running Azul Prime JVM under rr, and as it seems that it's using memfd_create with NULL to check whether the kernel supports it, it broke rr. So here's a fixie, I hope it's reasonable 😄
=> Allow invalid memfd_create *name arguments

src/test/util.py, src/test/watchpoint_unaligned.c, src/test/watchpoint_unaligned.py, src/util.h
DCZID_EL0.BS contains the the log2 of the DC ZVA block size in words (defined as 32 bits), not bytes, so the block size calculation in dczid_el0_block_size() was incorrect. As a result we would sometimes fail to trigger watchpoints. Fix it.
=> Fix block size calculation in dczid_el0_block_size()

src/AddressSpace.cc, src/test/watchpoint_unaligned.c, src/test/watchpoint_unaligned.py
The language from the ARM manual previously quoted in the comment in fact only pertains to Memory Copy and Memory Set instructions. According to the section describing the behavior for "other instructions", the recorded address can be > the watchpoint address. Therefore, remove the check that the watchpoint address >= the recorded address, and update the comment for accuracy.
Fixes #3736
=> Fix the condition for watchpoint matching on arm64

src/record_syscall.cc, src/test/sioc.c
When recording `gnome-nettool` or `mii-tool` rr throws assertions like these:
```
$ bin/rr record /sbin/mii-tool enp7s0
rr: Saving execution to trace directory `/home/bernhard/data/entwicklung/2023/rr/rr-recordings/mii-tool-1'.
[FATAL src/record_syscall.cc:6564:rec_process_syscall_arch()] 
(task 537273 (rec:537273) at time 139)
-> Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'ioctl' but got result -1 (errno EPERM); Unknown ioctl(0x8947): type:0x89 nr:0x47 dir:0 size:0 addr:0x5607c41203e0
```
```
[FATAL src/record_syscall.cc:6565:rec_process_syscall_arch()] 
(task 596577 (rec:596577) at time 742)
-> Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'ioctl' but …
```
=> Add support for SIOCGMIIPHY and SIOCGMIIREG ioctls.

src/record_syscall.cc
While using `rr` to debug a program that uses the libzbd library, I found that `rr` could not successfully capture the ioctl system calls related to blkzone devices. Therefore, I modified `record_syscall.cc` and submitted this PR. 
I will try to add related test programs in `src/test` later.
=> Add support for capturing blkzone IOCTL system calls in rr

src/test/breakpoint.py, src/test/breakpoint.run, src/test/util.py, src/test/util.sh, src/test/watchpoint_unaligned.py
=> Make breakpoint.run test run against LLDB as well as GDB

src/test/util.py, src/test/util.sh
I received a failure with the new test `alternate_thread_diversion` when running below my Debian Bookworm system.
This not overly elegant modifications would make the test work with this old lldb version.
Another option would be to define a minimum lldb version and check this before running the tests?
=> Modifications for old lldb version.

src/StdioMonitor.cc
```
src/StdioMonitor.cc:16:46: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘rr::FrameTime’ {aka ‘long long int’} [-Wformat=]
16 |     snprintf(buf, sizeof(buf) - 1, "[rr %d %ld]", t->tgid(), t->trace_time());
|                                            ~~^               ~~~~~~~~~~~~~~~
|                                              |                            |
|                                              long int                     rr::FrameTime {aka long long int}
|                                            %lld
```
=> Avoid warning about format string in 32-bit build.

src/PerfCounters_x86.h
Commit ca5c4d9 split out the Zen microarches by generation, but did not update the check for the presence of the Zen SpecLockMap workaround. The issue is applicable to all Zen generations, so adjust the check accordingly.
=> Check for zen microarch bug on all Zen microarches

src/PerfCounters_aarch64.h
Part numbers taken from:
https://github.com/AsahiLinux/m1n1/blob/main/src/chickens.c
=> Add part numbers for M2 Pro and M2 Max

src/AddressSpace.cc, src/AddressSpace.h
On arm64, mapping protection flags can include PROT_BTI and PROT_MTE, but they are not shown in /proc/pid/maps, so if a mapping has one of these the assert_segments_match() check will fail. Fix it by masking out flags that are not shown in /proc/pid/maps when doing the check.
=> Only check for PROT_{READ,WRITE,EXEC} in assert_segments_match()

CMakeLists.txt, src/PerfCounters.cc, src/PerfCounters.h, src/ReplaySession.cc, src/Task.cc, src/bpf/async_event_filter.c, src/fast_forward.cc, src/fast_forward.h
Starting in kernel 6.10 BPF filters can choose whether or not to trigger the SIGIO behavior for a perf event that becomes readable. We combine that with a hardware breakpoint and a BPF filter that matches the GPRs to produce an accelerated internal breakpoint type that can fast forward through loop iterations to deliver async signals. On one trace this reduced rr's replay overhead by 94%.
This adds a runtime dependency on libbpf and a compile time dependency on clang --target bpf. rr also needs CAP_BPF and CAP_PERFMON to use this feature. Because of all of that, this isn't really suitable for wide use at this point and is instead a CMake feature usebpf. Set -Dusebpf=ON to test it.
(I think we should wait until the kernel side hits Linus's tree to merge this.)
=> Add a path for BPF-accelerated async signal emulation.

src/test/pack.run
pack test: be explicit about using `/bin/chmod` as there is also a test binary named `chmod`
=> pack test: be explicit about using /bin/chmod

src/RecordSession.cc, src/RecordTask.cc, src/RecordTask.h, src/ReplayTask.cc, src/Task.cc, src/Task.h, src/TraceStream.cc, src/TraceStream.h, src/rr_trace.capnp
When handling a signal in a tracee, the kernel will spill some data to the stack (the "sigframe"), and this data needs to be recorded in the trace for replaying. However, we don't actually know how much data the kernel will write. Instead, we take a conservative estimate which is guaranteed to be at least that size, and record that amount of memory.
However, that range might cross a memory mapping, and during replay, part of that range might not be mapped. Currently that raises an assertion error because the write is smaller than the read.
In this patch, we record whether a memory "write" is actually this kind of conservative capture, and mark it as such in the trace. During replay, we then do not fail that assertion.
Should fix https://github.com/rr-debugger/rr/issues/3779
=> Record that the sigframe write recorded is conservative

src/PerfCounters.cc, src/PerfCounters_x86.h, src/counters-test/counters.cc
Extends existing Family 15h Model 30 (Steamroller) support for Piledriver. Piledriver supports PMCx0C4 (Retired Taken Branch Instructions) and PMCx0C6 (Retired Far Control Transfer), just like Model 30h. [1]
Note that PMCx0C4 counts all control flow changes, including exceptions and interrupts. AFAICT on 15h, there is no PMC for just retired conditional branches.
[1]: https://www.amd.com/system/files/TechDocs/42301_15h_Mod_00h-0Fh_BKDG.pdf
Tested:
1) counters-test:
vsrinivas@ubuntu:~/tmp/rr/src/counters-test$ cc -O2 counters.c
vsrinivas@ubuntu:~/tmp/rr/src/counters-test$ sudo ./a.out
Ticks mismatch; got 1003, expected 1002
Aborted
Varying the number of volatile matches, we always see one more
tick than expected, which I think is a RET instruction.
2) ctest:
97% tests passed, 45 tests …
=> PerfCounters: Add support for AMD Family 15h Model 2 (Piledriver)

src/record_syscall.cc, src/test/ioctl_hidraw.c
I haven’t investigated where the other one comes from.
=> add support for HIDIOCGRDESC and an unrecognized ioctl (from a driver?)

src/test/nested_detach.run, src/test/nested_detach_wait.run
fixing test runs on some environmments that stumble over those
=> suppress environment warnings in nested_detach tests

CMakeLists.txt, src/AddressSpace.h, src/AutoRemoteSyscalls.cc, src/AutoRemoteSyscalls.h, src/RecordSession.cc, src/Task.cc, src/Task.h, src/record_signal.cc, src/record_signal.h, src/test/clone_syscallbuf_cleanup_blocked.c, src/test/clone_syscallbuf_cleanup_blocked.run, src/test/clone_syscallbuf_cleanup_cpu.c, src/test/clone_syscallbuf_cleanup_cpu.run
This should be :crossed_fingers: a fix for https://github.com/rr-debugger/rr/issues/3807
It does two things to address that issue:
Firstly, moves the code for doing syscallbuf unmap after `vfork`/`exec` out of `Task::post_exec`, and instead defers doing that until we next run a task in that address space. This means we should never leak address space just because there were no available threads to perform the unmapping. This doesn't actually do anything to technically fix the issue, but it means we can write some reliable tests around the syscallbuf unmapping stuff, so it seemed worthwhile.
Secondly, we now look at the desched signal state in AutoRemoteSyscalls. If the desched signal is armed, we temporarily disarm it (and mask it too, in case the signal was pending but unprocessed). This …
=> Fix a deadlock in syscallbuf unmapping after vfork

src/PerfCounters.cc
On AMD, we regularly overshoot the programmed ticks counter. We print this as a warning earlier in the function. However, the warning is ineffective, because we have an assert with the same condition later in the function. Adjust the check for that error condition to only fire during replay, not record (where it is supposed to be non-fatal).
=> Don't assert on ticks overshoot during record on AMD

CMakeLists.txt, src/PackCommand.cc
When packaging traces from CI, it's fairly commong to have hundreds of traces that all basically share the exact same files. This can lead to some fairly large traces after packing. Of course, some file-systems support block-level deduplication and a compression library would certainly be able to dedup it back down as well, but it'd be faster to not create trace directories that big on disk in the first place.
This adds a `--pack-dir` command to `rr pack <traces...>`, which is used as a the common pack dir for all traces. Rather than packing files into their own trace dirs, they will be packed into the `pack-dir`, with relative symlinks from the original trace directories to the pack dir. An unmodified rr will be able to replay these as long as the pack dir is moved along with the trace …
=> pack: Add support for using a common pack dir for multiple traces

src/kernel_supplement.h
For building with older kernel headers.
=> kernel_supplement: Add additional NT_ARM_ definitions

src/ContextSwitchEvent.cc, src/PerfCounters.cc, src/util.cc, src/util.h
This came up with a Mozilla user today.
=> Print a useful error message for perf_event_paranoid == 4

CMakeLists.txt, src/RecordSession.cc, src/test/exec_shared_as.c, src/test/exec_shared_as.run, src/test/exit_fast.c, src/test/util.h, src/test/util_syscall.h
Fixes #3831. Using AutoRemoteSyscalls is not permitted after the signal injection check, since it could cause additional signals to be stashed. The fix is simple - reorder the syscallbuf unmapping before the signal injection check. A test is slightly tricker, but is quite reliable when exec'ing an executable that just exit's immediately. Notably this does not reproduce with executables that are dynamically linked, because there is enough time for rr to do things in the parent while the dynamic linker is running. In the original reproducer, it's more of a scheduler artifact than a fast exiting exec, but the latter makes for a more reproducable test.
=> Fix #3831 - incorrect ordering of effects in new syscallbuf unmapping code

CMakeLists.txt, src/AddressSpace.cc, src/RecordCommand.cc, src/RecordSession.cc, src/RecordSession.h, src/record_syscall.cc, src/test/mmap_shared_extern.c, src/test/mmap_shared_extern.run
In its current state it just calls lsof with the pids inside the the recording excluded.
It would show the mapping that caused the issue in #3417,
but the others are probably just read-only mappings due to /proc/pid/maps.
```
$ rr record --lsof -n atril sshfs/home/benutzer/test2.pdfrr: Saving execution to trace directory `/home/bernhard/data/entwicklung/2022/rr/rr-recordings/atril-14'.
Warning: /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache seems to be mapped by a process outside of the recording. Diversions might happen when replaying this trace.
Warning: /home/bernhard/.cache/fontconfig/a6050266-6adb-4e1c-8a1d-f55d18a3f9c3-le64.cache-7 seems to be mapped by a process outside of the recording. Diversions might happen when replaying this trace.
Warning: /run/user/1000/dconf/user …
```
=> Add parameter to check if files are mapped in processes not part of the recording.

src/test/util.sh
A failed test leaves currently two directories, one in tmp and one in the build directory. The latter seems to stay for most tests empty. Therefore attempt to remove this directory if it is empty.
=> Cleanup empty nontmp_workdir.

src/AddressSpace.cc
A default build (no additional cmake options) in a 32-bit Debian Bookworm was observed to use the constructor MemoryRange(addr, size) instead of MemoryRange(addr, end).
This triggered a crash of the chaos_oom test, because it tried to use the last part of the address space,
which results later in following fatal message, because end_ wraps over to the value 0.
[FATAL src/MemoryRange.h:20:MemoryRange()] start_ <= end_
-----
Following is a debug session showing the end_=0xe0000000 instead of the expected end_=0x70001000.
Are there any performance concern about the additional assert?
```
$ gdb -q --args bin/rr --check-cached-mmaps record --chaos bin/chaos_oom
Reading symbols from bin/rr...
(gdb) run
Starting program: /home/bernhard/data/entwicklung/2023/rr/2022-09-11/i686/obj/bin/rr …
```
=> Convince compiler to use constructor MemoryRange(addr, end).

CMakeLists.txt, src/PackCommand.cc, src/test/pack_dir.run, src/test/util.sh
This follows up the recently merged #3735 by:
1. Adding --pack-dir to the help
2. Allowing `pack` to take multiple directories to pack to make the argument useful.
3. Adding a test for the option.
=> Follow up addition of --pack-dir

src/test/pack_dir.run
Otherwise the test may fail because the file attributes (mtime in particular) changed.
=> Don't save the exe twice in pack_dir test

src/ContextSwitchEvent.cc, src/ContextSwitchEvent.h, src/PerfCounterBuffers.cc, src/PerfCounterBuffers.h, src/RecordTask.cc
The tracee may have died unexpectedly or been killed.
This commit allows the `cont_race` test to consistently pass when the test is run under all the following conditions:
(a) kernel.perf_event_paranoid = 2
(b) kernel supports PERF_RECORD_SWITCH (Linux kernel >= 6.10) 
(c) syscallbuf is enabled (so here we're talking only about `cont_race`
and NOT `cont_race-no-syscallbuf` which doesn't need switch events anyways)
Without this commit, I noticed the occasional failure in (syscallbuf enabled) `cont_race`:
```
[FATAL src/PerfCounterBuffers.cc:32:allocate() errno: EBADF] Can't allocate memory for PT DATA area
```
=> When using `PERF_RECORD_SWITCH`, allow ContextSwitchEvent initialization to fail

src/DiversionSession.cc, src/ReplaySession.cc, src/Task.cc, src/Task.h, src/record_signal.cc, src/util.cc, src/util.h
There were some code paths where trapped_instruction_at() was callable on non-x86 platforms; as a result it may have been possible to reach x86-specific handling of trapped instructions in cases where the instruction bytes happened to match. Fix it by adding an architecture check to said code paths, renaming the function to x86_trapped_instruction_at() (likewise for trapped_instruction_len() and TrappedInstruction) and adding an assertion that checks the architecture.
=> Make trapped_instruction_at() explicitly x86-specific

src/util.cc
We're supposed to run this check only on x86_64/i386 (I think), but the current logic is running the check on all architectures _except_ x86_64/i386. Oops.
```
(gdb) disassemble cpuid_faulting_works
Dump of assembler code for function _ZN2rr20cpuid_faulting_worksEv:
0x00000000005d3a60 <+0>:     xor    %eax,%eax
0x00000000005d3a62 <+2>:     ret
End of assembler dump.
```
=> Use the correct logic for CPUID faulting check skipping

src/RecordSession.cc
Since https://github.com/llvm/llvm-project/commit/fb77ca05ffb4f8e666878f2f6718a9fb4d686839 they actually moved the region that ASAN uses for its allocator, it seems. I guess we need to add a second reserved range? (Or else can we probe which range is actually in use somehow?)
=> Add a new ASAN exclusion range

src/PerfCounters.cc, src/PerfCounters_x86.h
> Remove "untested" CPUID family comments for Zen
> I cleaned up the list on the wiki and added the generations and their codenames.
> It turned out a couple were claimed as working there; lets update the code comments too.
> Ref: https://github.com/rr-debugger/rr/wiki/Zen/bca014d54c29480750ff63899c648ac2906710bd
----
> Add CPUID lists links to PerfCounters.cc
> Due to the apparent and constant churn when adding "confirmed working" CPUIDs, I 
decided to clean up the comments here. Take a hint, this means many CPUs aren't 
explicitly added to the list of known processors.
> Updated Intel's link and gave directions where exactly to find CPUIDs.
> AMD doesn't appear to have a single source of truth for those, as they are 
scattered in individual revision guides and are hard to find.
=> Update comments relating to CPUIDs

src/test/arm/arch_timer.c
This makes us compatible with pre-2.38 versions of binutils, including 2.35.2 which is used in RHEL 9.
Fixes #3858
=> Refer to the cntvctss_el0 system register by number.

src/AutoRemoteSyscalls.cc, src/AutoRemoteSyscalls.h, src/Task.cc
During record, safe_pwrite64() should not be infallible if the process is dying, otherwise `check_syscall_result()` `ASSERT`s
=> safe_pwrite64() should not be infallible if the process is dying

src/Session.cc
While unmapping a Mapping `local_addr`, take into account that the Mapping `m` passed in as a method parameter may come from a Task that differs from the remote.task() so the Mapping at `m.map.start()` for `remote.task()` may be different to `m`.
=> Session::recreate_shared_mmap fixes

src/launch_debugger.cc
fixes #3859 warnings during startup
=> wrap rr macros restart and jump in python

src/test/pack.run
`pack` test: dont hunt for `mmap_pack_*` files in `latest-trace/` if the fs supports cloning
Otherwise the `pack` test can incorrectly fail on, for example, btrfs:
```
ls: cannot access 'latest-trace/mmap_pack_*': No such file or directory
```
=> pack test: dont hunt for `mmap_pack_*` files in `latest-trace/` if the fs supports cloning

src/AutoRemoteSyscalls.cc
In various places in the codebase, file descriptors are sent to the tracee. Those file descriptors are often used in remote syscalls like mmap. The file descriptors are received using the system call `recvmsg`. The fd is sent/received using `SCM_RIGHTS` functionality in the control message part of the message payload.
It is possible for the kernel to NOT send the file descriptor to the receiving process if the per process max number of open files limit has been currently reached.
What is interesting is that the recvmsg system call will be successful: the single byte sent as part of the "data plane" of the message is received successfully but for all purposes this is a failure because the fd in the control message is the real payload but it will *not* be present if the max open files limit …
=> child_recvmsg: check if the control message was not truncated before trying to extract the child fd

src/AddressSpace.cc
AddressSpace::verify() should not be infallible
=> AddressSpace::verify() should not be infallible

CMakeLists.txt, src/RecordTask.cc, src/Scheduler.cc, src/test/sigcont_threaded.c
If a process receives a SIGSTOP, we emulate the group-stop by:
* Leaving the thread which happened to receive the SIGSTOP signal ptrace-stopped
* Refusing to schedule any other thread until the group-stop is over
The whole group-stop is therefore emulated by rr and not actually enforced by the kernel.
When a SIGCONT is received, we need to end the group-stop. However, we can't actually _know_ that a ptrace-stopped thread received a signal until we try and resume it. To work around this, we check /proc/tid/status's `SigPnd` and `ShdPnd` fields in the scheduler to detect when a thread that's in a group-stop has a pending SIGCONT, and so needs to be PTRACE_CONT'd so we can actually `wait` and receive that SIGCONT.
A problem however arises in the following case:
* A process has at least two …
=> Fix SIGCONT handling on threads blocked in syscalls

CMakeLists.txt, scripts/rr_completion.zsh, src/util.cc
This also fixes `rr ls` not to list pre-installed files as traces.
cc https://github.com/rr-debugger/rr/issues/3681
=> Add support for zsh shell completions

src/Scheduler.cc
If we see the PTRACE_EVENT_EXIT for a task while running a different task in unlimited-ticks mode in `Scheduler::reschedule`, it looks like nothing ever actually calls `handle_ptrace_exit_event` on it, and so nothing ever PTRACE_CONT's the task out of the exit-stop and into the zombie state.
This seems to manifest itself as rr not reaping processes properly when they receive asynchronous core-dumping signals (e.g. SIGSEGV sent by `raise` or `kill`).
Fix this issue by checking if there's a pending PTRACE_EVENT_EXIT to deal with on the task in `Scheduler::is_task_runnable`, and allowing the task to be executed if so.
Fixes #3882
=> Schedule tasks where we've seen but not processed PTRACE_EVENT_EXIT

src/Event.h
`should_retry_patch` must be initialized otherwise random syscall patch retrying errors happen even on aarch64
=> should_retry_patch must be initialized

src/test/x86/arch_prctl_xstate.c
Ordinarily I'd just push something like this but it's not clear to me why the test is doing ARCH_GET_XCOMP_PERM before ARCH_REQ_XCOMP_PERM in the first place ...
=> Repeat ARCH_XCOMP_GET_PERM if necessary as the relevant bit may be newly enabled.

src/kernel_abi.cc
This is needed to verify the sched_param type.
The header is no longer transitively included via libc++ after https://github.com/llvm/llvm-project/commit/699f19605579f25083152a9ad21e14c2751d5d66
=> Add missing #include <sched.h>

src/AddressSpace.cc, src/AddressSpace.h, src/Task.cc, src/record_syscall.cc
I don't follow the logic in `unmap_all_but_rr_mappings` but I did the logical thing assuming it's correct.
=> Treat [vvar_vclock] the same way we treat [vvar].

src/preload/syscallbuf.c
I don't see any reason we can't do this, and it's worth a 6x improvement on a customer-provided testcase.
=> Buffer epoll_ctl.

src/kernel_abi.cc, src/kernel_abi.h, src/record_syscall.cc
Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/mtd/mtdchar.c?h=v6.13#n822
A limited subset of these ioctls can be tested without a physical MTD device by running:
sudo modprobe nandsim
sudo chown "${USER}" /dev/mtd1
git clone --depth 1 --recurse-submodules https://github.com/kempniu/yafut.git
cd yafut/
cmake -Bbuild && cmake --build build
dd if=/dev/urandom bs=32k count=1 | tee garbage-in | rr record build/yafut -d /dev/mtd1 -v -v -w -i - -o /garbage   
rr replay -a -M
rr record build/yafut -d /dev/mtd1 -v -v -r -i /garbage -o garbage-out
rr replay -a -M
sha256sum garbage-in garbage-out
=> Add support for MTD ioctls

src/PerfCounters.cc, src/PerfCounters_x86.h
This commit adds `0xc0660` as Intel Arrow Lake.
=> Added PmuConfig for Intel Arrow Lake

src/Scheduler.h, src/record_syscall.cc, src/test/ptrace_seize.c
The current code is completely untested because it will always call syscall_state.emulate_result twice and fatally assert. The ptrace_seize test does not yield between PTRACE_CONT and PTRACE_INTERRUPT, so rr will not switch to the emulated ptracee and resume execution, and the PTRACE_INTERRUPT will always find the emulated ptracee already stopped. Additionally, the test does not wait on the emulated ptracee again after interrupting it, so the following assertion about the value of status is bogus.
Fix all of that by adding the appropriate waitpid, tweaking the status assertion, duplicating the PTRACE_CONT/PTRACE_INTERRUPT sequence but with an intervening sched_yield() to force the emulated ptracee to resume, and fixing rr's PTRACE_INTERRUPT emulation to emulate_result only once and to …
=> Fix PTRACE_INTERRUPT to actually work if the tracee is not already stopped.

CMakeLists.txt, src/RecordTask.cc, src/RecordTask.h, src/Scheduler.cc, src/test/ptrace_group_stop.c
Firefox's minidump writer expects to be able to attach to tasks in group stops and invoke ptrace commands on them (e.g. PTRACE_GETREGS)
Fixes #3741.
=> Improve support for ptrace emulation during group stops.

third-party/gdb/32bit-avx512.xml, third-party/gdb/64bit-avx512.xml
Add copyright headers that were missing from target description xml files.
=> Add missing copyright headers

src/test/readv.c, src/test/writev.c
Recent versions of GCC complain about the string
buffers in some tests being too short to fit a NULL terminator. This causes the build to fail due to -Werror.
Observed on Fedora 42 with GCC 15, probably also affects others.
=> Fix build with recent GCC

src/launch_debugger.cc
fixing #3838 by disabling it in case system or user init files enabled it until non-stop mode may be supported #488
=> disable non-stop mode

src/SourcesCommand.cc
This is required to be able to automatically discover debuginfo on Nix based systems, as we need to know what got loaded.
Fixes: https://github.com/rr-debugger/rr/issues/3944
=> rr sources: expose loaded elves

src/test/priority.run
fixes #3963
`nice ctest` will run as 10, so only root could run a "nice ctest" and pass this test before - fixed by "using higher than 10".
Obviously would still fail with `nice -n 15 ctest`, but that's at least much rarer than running tests next to something else by "nice". If wanted I could also use something like 16+17...
Edit: please manually add the reference to the issue before merging.
=> test adjustment: priority working under "nice"

CMakeLists.txt, src/AutoRemoteSyscalls.cc, src/Task.cc, src/record_syscall.cc, src/test/fd_leak.run
We are pretty good about setting CLOEXEC on most file descriptors. However, we were missing them on the pagemap fd and the tty fd. With lots of nested detaching, this can start filling up fd space, which manifested as a CI failure on julia CI: https://github.com/JuliaLang/julia/issues/58979
Fix this by setting CLOEXEC as appropriate and add a test to make sure this doesn't regress.
=> Don't leak extra fds into recorded processes

src/preload/syscallbuf.c
glibc (and others) defines msg_iovlen in struct msghdr as size_t while POSIX defines it as int
=> fix type warning on iovlen in syscallbuf.c

CMakeLists.txt, src/ContextSwitchEvent.cc, src/Registers.h, src/ReplayTask.cc, src/ReplayTask.h, src/Session.h, src/Task.h, src/WaitManager.cc
I know > c++17 is not officially supported by rr, but these changes do not change behavior in any way, so I figured it'd be nice to make it possible to just drop rr into a c++23 setting and it building with no issues.
Also added some minor const thing.
=> Tiny changes needed for building with c++23 support

src/test/privileged_net_ioctl.c
* glibc has that as a define
* muslc and others have that as a function, which leads to a build failure, as seen in the #4009 build log.
* Android API level 20 misses it
=> only define htonl where missing
